### ISSUE TITLE
request.client may be null

### ISSUE THREAD

**Issue by ronag** [github/fetch#1013]
The spec says that `request.client` may be null.

> A request has an associated client (null or an environment settings object).

However, the spec does not take this into account in some parts of the spec, e.g.

>   8. If request’s window is "client", then set request’s window to request’s
>   client, if request’s client’s global object is a Window object; otherwise
>   "no-window".
 
>   9. If request’s origin is "client", then set request’s origin to request’s
>   client’s origin.

**Comment by KVROHITH098** [comment]
Pls do the client part and get back to me. 



Thank you
