### ISSUE TITLE
What is this good for? It doesn' t seem to run on IE11. 

### ISSUE THREAD

**Issue by carlo-cs** [github/fetch#1027]
It is using modern features, like:
export function Request

Which are not supported on IE:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

Outside of IE11, I see no need for a polyfill.

Besides, why are you putting variables and functions into the global space when the polyfill is not required?

**Comment by Shah8018** [comment]
Opp sory mr carlos. Wrong person. 
that is my mistake
have a gd day

**Comment by JakeChampion** [comment]
The published package has a UMD bundle which will work in older browsers -- https://unpkg.com/browse/whatwg-fetch@3.6.2/dist/
