### ISSUE TITLE
How to send GET request with headers and serialized values?

### ISSUE THREAD

**Issue by jiyinyiyong** [github/fetch#103]

**Comment by dgraham** [comment]
Setting headers on the GET request works the same as for POST. There's an example in the [README](https://github.com/github/fetch#post-json).

Serializing query parameter values can be done with [`window.encodeURIComponent()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) or jQuery's [`$.param()`](http://api.jquery.com/jQuery.param/).

**Comment by jiyinyiyong** [comment]
Thanks for pointing out anyway.

**Comment by pke** [comment]
This seems not to work in the current version.

```
fetch(`https://server.com/api/cities.json`, {
      method: "get",
      mode: 'no-cors',
      headers: {
        'X-API-Key': '`XXXXX',
        'Accept-Version': 'v2'
      }
    })
```

The headers are not set (in Chrome 48.0.2564.109).

**Comment by mislav** [comment]
@pke I'm sorry you're having problems. If `fetch()` doesn't work for you in Chrome, you should report it to the Chromium issue tracker, since the bug would be with their native implementation. Our polyfill only takes effect in other browsers like Safari and IE which don't implement `fetch()` yet.

**Comment by pke** [comment]
I have [reported the bug ](https://bugs.chromium.org/p/chromium/issues/detail?id=588830)to Chromium
