### ISSUE TITLE
Minified distribution

### ISSUE THREAD

**Issue by jh3y** [github/fetch#104]
Hey.

For me personally, if I'm using the fetch polyfill I'm probably going to use a task runner to package it up with others and minify it myself but wasn't sure if you envisioned having a `dist` folder or the likes and providing a minified version also?

@jh3y

**Comment by josh** [comment]
I think what you're already doing is good. You'll get the best minification results if you bundle fetch with your other scripts rather than minifying it standalone.

Thanks for the question.

**Comment by jh3y** [comment]
Ah yeah for sure. Just figure some people once they latch on to the use of fetch will most likely be looking for cdnjs(or similar) options or being able to grab a release version.

@jh3y
