### ISSUE TITLE
This should fix it for you if you are on NodeJS 12 or higher -- https://github.com/github/fetch/pull/822

### ISSUE THREAD

**Issue by ZhaoTim** [github/fetch#1057]
This should fix it for you if you are on NodeJS 12 or higher -- https://github.com/github/fetch/pull/822

_Originally posted by @JakeChampion in https://github.com/github/fetch/issues/821#issuecomment-670573273_

**Comment by ZhaoTim** [comment]
Sorry, I don't know why must works on nodejs 12 .
My project bases on Nodejs 10.

**Comment by Gara312** [comment]
> Извините, я не знаю, почему должен работать на nodejs 12. Мой проект основан на Nodejs 10.

**Comment by Gara312** [comment]
> Это должно исправить это для вас, если вы используете NodeJS 12 или выше - [# 822](https://github.com/github/fetch/pull/822)
> 
> _Первоначально опубликовано @JakeChampion в [# 821 (комментарий)](https://github.com/github/fetch/issues/821#issuecomment-670573273)_



> Извините, я не знаю, почему должен работать на nodejs 12. Мой проект основан на Nodejs 10.

**Comment by Gara312** [comment]
> Извините, я не знаю, почему должен работать на nodejs 12. Мой проект основан на Nodejs 10.

**Comment by Gara312** [comment]
> Извините, я не знаю, почему должен работать на nodejs 12. Мой проект основан на Nodejs 10.
