### ISSUE TITLE
Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

### ISSUE THREAD

**Issue by bboyball008** [github/fetch#1078]
Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

_Originally posted by @welcome[bot] in https://github.com/github/docs/issues/11594#issuecomment-956483304_

**Comment by pornte07** [comment]
🤨🤨🤨

ในวันที่ อ. 2 พ.ย. 2021 1:36 AM PORNSAK ***@***.***> เขียนว่า:
