### ISSUE TITLE
Streams

### ISSUE THREAD

**Issue by josh** [github/fetch#108]
They're coming.

![](https://cloud.githubusercontent.com/assets/137/6809170/c44e79c8-d215-11e4-815b-8581c79e5613.png)

I think @domenic has the pieces of a Stream polyfill around somewhere. We'll have to decide if we should make that an external dependency or just bundle the minimal stream implementation we need here. I think we mainly need the readable stream stuff, so maybe its not too much code. I dunno.

Also, all test coverage around this. This will probably help the FF folks check there upcoming implementation as well.

/cc @dgraham @jakearchibald @domenic

**Comment by thomasboyt** [comment]
Unsure why this was closed, would love to see this feature added to the polyfill :)
