### ISSUE TITLE
Chrome leaves a tmp file on every request fetch does

### ISSUE THREAD

**Issue by lanwin** [github/fetch#115]
Each time we do a request with fetch Chrome creates a tmp file in %LOCALAPPDATA%\Temp on Win8 x64. End never seems to remove that file after that. With this, the temp folder is full pretty soon.

We tried it on different machines with different configuration, with and without debug mode on and its allays the same. 
The tmp files containing the full content of our request.

Example request
```javascript
    return config.get()
      .then(()=>fetch(`${config.api}/v1/account`,{headers:{Authorization:this.token}}))
      .then(res=>res.json());
```
config.get returns a promise which ensures the config is loaded before we can do any request.

The requested api uses cors headers. 

Any idea?

**Comment by mislav** [comment]
Yikes. Is this known by the Chrome team?

Are you reporting a problem with the polyfill or with Chrome's native implementation? Sounds like Chrome's native implementation might be doing something wonky on Windows. Check the Chrome version and please share here.

The polyfill simply uses XMLHttpRequest behind the scenes. So if there is a problem with the polyfill, then Chrome on Windows has a problem with CORS XMLHttpRequest.

In either case, there's little that we can do. But thanks for letting us know!

**Comment by lanwin** [comment]
Uh I dont even considered Chrome could have a working impl of fetch yet. Need to check that.

Yes I looked at that code and did not see anything what could produce that.

**Comment by mislav** [comment]
Note: `fetch` is natively implemented starting with Chrome 42 and Firefox 39 http://caniuse.com/#feat=fetch

**Comment by lanwin** [comment]
Ive checked that. 42 does not seems to be released. I have 41 and its up to date. So the code uses the polyfill.

Ive created a small example to reproduce it. Create an empty HTML5 body, include fetch.js and add this snippted:

```javascript
		function getIt() {
			fetch('http://server.cors-api.appspot.com/server?id=1516545&enable=true&status=200&credentials=false')
				.then(function(res){return res.json();})
				.then(function(x){ console.log(x); });
		}
		
		setInterval(getIt,1000);
```

**Comment by dgraham** [comment]
Since JavaScript has no access to the file system, this sounds like a Chrome bug.

Try using Chrome's native `fetch` implementation in the latest [Canary build](https://www.google.com/chrome/browser/canary.html) to see if the temporary files are still created.

You might also try copying this [`fetch` function](https://github.com/github/fetch/blob/654c94f2585e799c802d1cbc8a2894c939213c22/fetch.js#L259-L315) and commenting things out, until the temporary files are no longer created, to narrow down the root cause.

**Comment by mislav** [comment]
> Ive created a small example to reproduce it. Create an empty HTML5 body, include fetch.js and add this snippted:

Thanks for the snippet. Since the polyfill using using XHR internally, I would suggest that you try to reproduce it by using a XMLHttpRequest for your CORS request. Once you got down to the simplest possible code to reproduce it, share it with the Chrome team. Also worth exploring is whether tmp files get created for non-CORS requests. Thanks!

**Comment by lanwin** [comment]
Interesting. It seems using a simple xhr request with and without cors does not has this problem:

```javascript
        var xhr = new XMLHttpRequest();
        xhr.open('GET', 'http://server.cors-api.appspot.com/server?id=1516545&enable=true&status=200&credentials=false', true);
        xhr.onload = function(s){console.log(s)};
        xhr.send();
```

**Comment by lanwin** [comment]
I got it. The problem is forced by this line in fetch.js. If i comment it out, the tmp files disappear.

```javascript
xhr.responseType = 'blob'
```

**Comment by lanwin** [comment]
Raised a bug request on chromiums issue tracker https://code.google.com/p/chromium/issues/detail?can=1&q=responseType%20blob&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&id=475444&thanks=475444&ts=1428573201

**Comment by mislav** [comment]
> I got it. The problem is forced by this line in fetch.js

Nice catch; thanks for finding that and filing an issue.

One thing you could try is undefining `window.Blob`. Then `fetch.js` will detect that Blob is not supported and never set that xhr property. You should be fine if you'll only be using text responses.

**Comment by lanwin** [comment]
I can confirm that this problem doesnt exists on Chrome 42 with native fetch, which is now stable.

**Comment by mislav** [comment]
Thanks for checking @lanwin. I see that you've got some attention on the bug report. Let us know of any updates.
