### ISSUE TITLE
SyntaxError at JSON.parse due to status=204 (no content)

### ISSUE THREAD

**Issue by ne-spal** [github/fetch#123]
Because of
```javascript
else if (!body) {
          this._bodyText = ''
```
and
```javascript
this.text().then(JSON.parse)
```

**Comment by mislav** [comment]
I think this is expected. If you try to parse content with JSON, but the response body isn't valid JSON (such as an empty body) then the exception should be thrown.

**Comment by ne-spal** [comment]
Yeah, but is it better than just getting "null"?

**Comment by mislav** [comment]
Yes it's very much better. Because when you're expecting JSON, you won't be expecting `null`. So it's better to have a descriptive exception that you can handle in exception-handling code, instead of trying to iterate over properties of `null` and get a more cryptic error.

**Comment by ne-spal** [comment]
Oh, I got it.
And moreover, it's the same behaviour as the native implementaion.
But I thought it could be an exception for status 204...
