### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by tcurdt** [github/fetch#125]
I have an isomorphic react app. So while this the code is not running on node, still babel complains that "self is not defined". A quick hack that makes things work is to add "self = this;" to fetch.

Would be really nice to have a proper fix for this.

**Comment by tcurdt** [comment]
just found https://github.com/matthew-andrews/isomorphic-fetch and then https://github.com/matthew-andrews/fetch/blob/master/fetch.js#L3 which has:

    if (typeof global !== 'undefined') {
      var self = global.self;
    }

**Comment by mislav** [comment]
Yes please use that project instead. #31

**Comment by tcurdt** [comment]
I don't want to really use it in isomorphic way - I just have an isomorphic setup. That's a bit of a different thing. (Which is why those projects are not really what I am after)

Ideally `require("whatwg-fetch")` would just export what it's offering.
What I ended up doing is:

    if (process.env.IS_BROWSER) {
      require('whatwg-fetch');
    }

Not nice - but works.

**Comment by mislav** [comment]
Your workaround looks good. I would suggest applying the same conditional to all requires in your app that load libraries that are only useful in browsers.

**Comment by tcurdt** [comment]
I will.

As a side note - I would much prefer this style of use

    var blafetch = require('whatwg-fetch');
    blafetch('/users.html')
      .then(function(response) {
        return response.text()
      }).then(function(body) {
        document.body.innerHTML = body
      })

or even better

    var Fetch = require('whatwg-fetch');
    Fetch.get('/users.html')
      .then(function(response) {
        return response.text()
      }).then(function(body) {
        document.body.innerHTML = body
      })

Maybe for the next major version.

**Comment by mislav** [comment]
> As a side note - I would much prefer this style of use

Perhaps you're missing the point of this project. We're trying to create a polyfill for a future standard feature of browsers. The API for that feature is `window.fetch`. We're not trying to create anything more or other than that.

**Comment by tcurdt** [comment]
I see.

**Comment by billinghamj** [comment]
Unfortunately in React Native, the workarounds mentioned don't seem to be sufficient. Due to the way React packages JS files assuming they support AMD/CommonJS modularization properly, this library ends up running anyway - even if it isn't required.

**Comment by mislav** [comment]
@billinghamj We welcome a PR that solves this while keeping in mind that the code must also be able to run in a web worker environment. See https://github.com/github/fetch/pull/239#issuecomment-160598283 for context

**Comment by billinghamj** [comment]
@mislav That was the purpose of #252. I'll make a PR for it.
