### ISSUE TITLE
👋 Hey there spelunker. It looks like you've modified some files that we can't accept as contributions. The complete list of files we can't accept are:

### ISSUE THREAD

**Issue by Taylerpaul** [github/fetch#1269]
👋 Hey there spelunker. It looks like you've modified some files that we can't accept as contributions. The complete list of files we can't accept are:
.devcontainer/**
.github/actions-scripts/**
.github/workflows/**
.github/CODEOWNERS
assets/fonts/**
data/graphql/**
Dockerfile*
lib/graphql/**
lib/redirects/**
lib/rest/**
lib/webhooks/**
package*.json
scripts/**
content/actions/deployment/security-hardening-your-deployments/**

You'll need to revert all of the files you changed in that list using [GitHub Desktop](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit) or `git checkout origin/main <file name>`. Once you get those files reverted, we can continue with the review process. :octocat:

_Originally posted by @github-actions[bot] in https://github.com/github/docs/issues/23189#issuecomment-1414580066_

**Comment by Taylerpaul** [comment]
If you will take a screenshot of the contributions so I can verifyTaylerpaulOn Mar 31, 2023, at 9:27 PM, Jake Champion ***@***.***> wrote:﻿
Closed #1269 as completed.

**Comment by Taylerpaul** [comment]
Taylerpaul


Begin forwarded message:

> From: Paul Whisnant ***@***.***>
> Date: April 16, 2023 at 9:16:17 PM EDT
> Subject: [Shared Post] Credit Karma Editorial Guidelines
> 
> ﻿https://www.creditkarma.com/advice/i/editorial-guidelines
> 
> 
> Taylerpaul
>

**Comment by OmarSayah793** [comment]
https://github.com/github/fetch/assets/130795421/3c8a94e2-4927-40ba-926f-30047f501a09
