### ISSUE TITLE
When doing POST requests with CORS and {credentials: 'include'}, the pre-flight OPTIONS does not send credentials

### ISSUE THREAD

**Issue by vasa-chi** [github/fetch#128]
I've prepared a small example: http://jsbin.com/kevomilasa/2/edit?html,js

Basically, if you set headers: {'content-type': 'application/json'}, the pre-flight OPTIONS does not have any credentials. 
If you remove the header, there is no OPTIONS.

Browser: Chrome 42.0.2311.90 (64-bit), OS X

**Comment by wereHamster** [comment]
Have you tried `{credentials:'cors'}` ? fetch.js doesn't follow the spec, see #109.

**Comment by dgraham** [comment]
Fixed in #113.
