### ISSUE TITLE
IE10 throws on withCredentials

### ISSUE THREAD

**Issue by Naddiseo** [github/fetch#129]
A trimmed down way to reproduce:
```javascript
try {
var xhr = new XMLHttpRequest()
xhr.withCredentials = true;
}catch(e) {
    alert("There was an error:" + e);
}
```

More information: http://stackoverflow.com/questions/19666809/cors-withcredentials-support-limited

Moving:
```javascript
if (self.credentials === 'cors') {
    xhr.withCredentials = true;
}
```
until after the `xhr.open` fixes this for me.

**Comment by dgraham** [comment]
Fixed in #113.
