### ISSUE TITLE
cannot read response body when status is 400

### ISSUE THREAD

**Issue by hummlas** [github/fetch#133]
I have a service that returns a custom error message in the response body.
But when I try to call `response.json()` i only get a rejected or pending promise, I've tried a bunch of stuff but I can't seem to read the json sent back from the service if it's not a 200-response.

**Comment by dgraham** [comment]
It's difficult to help without seeing a code sample, but this is working for me with a 400 response status:

```js
fetch('/')
  .then(function(response) {
    console.log(response.status)
    return response.json()
  })
  .then(function(value) { console.log(value) })
```

**Comment by dgraham** [comment]
You might also try testing with Chrome's native `window.fetch` implementation to isolate the problem to just the server response and your response handling JS code.

**Comment by hummlas** [comment]
Ehrm.. Just realized I did all my testing in Chrome, my bad..

But for the sake of completeness, here's my code:
```
            fetch(API_BASE_URL + "oauth/token", {
            method: "post",
            headers: {
                "Accept": "application/json",
                "Content-Type": "application/x-www-form-urlencoded"
            },
            body: `username=${encodedEmail}&password=${encodedPassword}&grant_type=password`
        }).then(status)
            .then(json => AuthActions.handleLoginSuccess(json.access_token))
            .catch(error => AuthActions.handleLoginError(error));

``` 

And here's a screengrab from my dev-tools when inspecting what's going on in the `status` function.

![image](https://cloud.githubusercontent.com/assets/830794/7446275/7d6feafe-f1d3-11e4-9ebf-26f478f0ea9b.png)

And here's the actual response data I'm trying to output in my error-handler:

![image](https://cloud.githubusercontent.com/assets/830794/7446293/ffd351d4-f1d3-11e4-8643-20400164cd7a.png)

**Comment by dgraham** [comment]
The `response.json()` method call returns a Promise object, not the actual parsed JSON object. So, `json.errorDescriptions` is an error because a Promise does not have an `errorDescriptions` attribute.

To handle the parsed JSON object:

```js
fetch('/')
  .then(function(response) { return response.json() })
  .then(function(json) { json.errorDescriptions })
```

**Comment by hummlas** [comment]
I see, thank you for the clarification :)
