### ISSUE TITLE
Ability to influence XMLHttpRequest object creation

### ISSUE THREAD

**Issue by t3hmrman** [github/fetch#134]
While using fetch to write a FirefoxOS app, I've realized that I need to be able to pass in creation params to the underlying `XMLHttpRequest`. 

I apologize if there is already a way to do this that I missed, but in my case I need the XMLHttpRequest creation (on line 245) to actually look like this: 
```javascript
var xhr = new XMLHttpRequest({mozSystem: true});
```

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest
(See the CORS section)

**Comment by dgraham** [comment]
The XMLHttpRequest instance is an implementation detail that is not included as part of the public [Fetch API](https://fetch.spec.whatwg.org/).
