### ISSUE TITLE
Don't repeat _initBody definition

### ISSUE THREAD

**Issue by wheresrhys** [github/fetch#135]
Would you be open to a PR to avoid the duplication between here https://github.com/github/fetch/blob/master/fetch.js#L129 and here https://github.com/github/fetch/blob/master/fetch.js#L178, or is there a good reason for it?

**Comment by Naddiseo** [comment]
It's not duplicated, it's inside an `if/else` clause...

**Comment by mattking17** [comment]
The difference is an additional check for `support.blob` here https://github.com/github/fetch/blob/master/fetch.js#L133 but from what I can tell this patch would cover both cases. There's no reason to have similar blocks of code in here twice when it can live in one place.

**Comment by wheresrhys** [comment]
Yep, and _initBody checks for support.blob internally anyway before it
tries to create a blob

**Comment by josh** [comment]
>  is there a good reason for it?

The second clause defines support for IEs that don't support blob.
