### ISSUE TITLE
Disable follow redirect

### ISSUE THREAD

**Issue by vslinko** [github/fetch#137]
Quote from standard:

```
A request has an associated redirect mode, which is one of "follow", "error", and "manual". Unless stated otherwise, it is "follow".

A request has an associated redirect count. Unless stated otherwise, it is zero.
```

**Comment by josh** [comment]
I don't think this is going to be possible to polyfill on top of XHR.

**Comment by domenic** [comment]
I don't think this is exposed in the API anyway. Those sentences have no bearing on `window.fetch`.

**Comment by SaschaNaz** [comment]
@dgraham Hi, can you reopen this issue?

https://www.chromestatus.com/features/4614142321229824

https://fetch.spec.whatwg.org/#requestredirect

JS use:

```javascript
fetch(new Request(url, {redirect: 'manual'}))
```

**Comment by dgraham** [comment]
This is a nice addition to the Fetch API, but we won't be able to polyfill it with `XMLHttpRequest`. The browser navigates all redirects before returning a result, so there is no opportunity to interrupt the redirect flow.

> If the response has an HTTP status code of 301, 302, 303, 307, or 308…Set the request URL to the URL conveyed by the Location header…transparently follow the redirect…

—[XMLHttpRequest specification](http://www.w3.org/TR/XMLHttpRequest/#infrastructure-for-the-send()-method)

**Comment by SaschaNaz** [comment]
That's right but I think we can at least mimic `redirect: error` using responseURL attribute, (unfortunately) after redirection.

**Comment by mislav** [comment]
@SaschaNaz We *could* make a clumsy support for `redirect: error`, but that would only provide a partial and imperfect support for the `redirect` setting. I'd rather that we don't support this at all in the polyfill.

**Comment by SaschaNaz** [comment]
@mislav That's reasonable, thanks :)

**Comment by axelson** [comment]
Is this difference from the standard documented anywhere?

**Comment by mislav** [comment]
@axelson I don't think so. You're welcome to add it to our documentation in the "gh-pages" branch [seen here when published](http://github.github.io/fetch/).

**Comment by khanibal88** [comment]
Yeyo
