### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by emroot** [github/fetch#141]
Even when I disable my chrome web-security ``` open -a Google\ Chrome --args --disable-web-security ``` I get this error:
```
Fetch API cannot load https://.... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost...' is therefore not allowed access.
Uncaught (in promise) TypeError: Failed to fetch {stack: (...), message: "Failed to fetch"}
```

Is there a way to skip this check?

**Comment by emroot** [comment]
so looks like the npm version doesn't have the [latest](https://github.com/github/fetch/commit/227652292490dbcff3bfd66fc1385dc0125ddaee) changes yet.

So after pointing my package.json to the github directly, not the options request is successful, no more errors, but the GET request doesn't happen :(

**Comment by dgraham** [comment]
Are you sure you're using the polyfill code and not Chrome's native `fetch`?
