### ISSUE TITLE
Unclear about how to deal with cookies

### ISSUE THREAD

**Issue by crispen-smith** [github/fetch#142]
I think my cookies are not being sent automatically, I'd expect this should happen as it's a request to the same-origin as the page from which I'm calling Fetch.

This is resulting in my sessions disappearing for requests made via fetch.

**Comment by mislav** [comment]
Unfortunately, the spec requires you to explicitly set the `credentials: 'same-origin'` option for every `fetch()` invocation in order to get this behavior. https://github.com/github/fetch/pull/56#issuecomment-69113848

**Comment by crispen-smith** [comment]
I don't mind doing that, know that I know it's in the spec.   Problem for me was I wasn't clear on how to even google for a driver of this issue.  Thanks for a super quick response.
