### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by bennybennet** [github/fetch#145]
Given Testdata:

```
var data = {
  "name": "Jürgens"
}

fetch("https://...", {
    method: "POST",  
    headers: {  
        "Accept": "application/json",
        "Content-Type": "application/json;charset=UTF-8"  
    },
    body: JSON.stringify(data)
});
```

The Request-Body seems to have a encoding issue:

```
{"name":"JÃ¼rgens"}
```

Am I doing something wrong? Can't figure out what to do here. Should I encodeUri() my data?

**Comment by mislav** [comment]
You shouldn't need to `encodeUri` your data. `JSON.stringify` takes care of making the payload safe for POST body. Your header value also looks alright. My first guess would be that you're not verifying the resulting Request-Body correctly, i.e. that the tool you're using is mangling the string which is otherwise properly UTF-8 encoded.

**Comment by bennybennet** [comment]
Thanks for your reply. That was also my assumption, that JSONstringify should take care of that. I'm using fetch in a cordova project and do debugging via Safari Dev Tools. I do really have no clue at all at the moment where to find the issue. :( Really every help appreciated, do have some time pressure here.

**Comment by domenic** [comment]
It's likely just a dev tools problem. Can you verify on your server? (Assuming your server is set up to do UTF-8 decoding correctly.)

**Comment by dgraham** [comment]
JSON allows any valid Unicode character so no escaping will be done by `JSON.stringify`.

**Comment by dgraham** [comment]
You can try using `XMLHttpRequest` directly to try and eliminate fetch as a possible cause.

```js
var request = new XMLHttpRequest()
request.open('POST', '/some/url')
request.setRequestHeader('Content-Type', 'application/json;charset=utf-8')
request.send(JSON.stringify(data))
```

Then check the request body that appears on the server.
