### ISSUE TITLE
Form upload 

### ISSUE THREAD

**Issue by jmejias** [github/fetch#148]
I am getting this error when I am trying to do a simple FormData upload

`Uncaught Error: unsupported BodyInit type`

```javascript
let data = new FormData();
data.append('name', 'test');

fetch(`${ENV.apiURL}/portfolios`, {
        method: 'post',
        headers: {
          'Authorization': token
        },
        body: data
      });
```

**Comment by domenic** [comment]
I am pretty sure FormData is not supported in Chrome yet :-/

**Comment by dgraham** [comment]
We use a FormData fetch request body on github.com for image uploads. This works from the Chrome web console too:

```js
form = new FormData()
form.append('name', 'hubot')
fetch('/bogus', {method: 'post', body: form})
```

**Comment by dgraham** [comment]
@jmejias Which browser are you using? This is the [polyfill line](https://github.com/github/fetch/blob/0b3e1d7c41c75359a3e0b771741ebc2a8823da38/fetch.js#L140) throwing this error.

**Comment by jmejias** [comment]
@dgraham I am using lastest Chrome

**Comment by dgraham** [comment]
Chrome 43 has a native `window.fetch` implementation that [bypasses the polyfill](https://github.com/github/fetch/blob/0b3e1d7c41c75359a3e0b771741ebc2a8823da38/fetch.js#L4-L6) code entirely. The polyfill is only active in Firefox, IE, and Safari.

You might try running your code in the web console to isolate the problem.

**Comment by jmejias** [comment]
@dgraham cannot reproduce the error from the console. I am using a framework on top maybe it is conflicting in the FormData object
