### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by ai** [github/fetch#152]
I think every project should have ChangeLog, because users should have a quick way to find what was changed in new release.

And many users think so too: http://keepachangelog.com/

/cc @josh @dgraham

**Comment by mislav** [comment]
How would you feel if we maintained Release notes instead ([example](https://github.com/github/hub/releases/tag/v2.2.1))?

**Comment by ai** [comment]
@mislav yeap, GitHub Release are nice too :).

**Comment by mislav** [comment]
It's done.

**Comment by dgraham** [comment]
Thanks, @mislav!
