### ISSUE TITLE
Add documentation for query parameters

### ISSUE THREAD

**Issue by eranimo** [github/fetch#153]

**Comment by masaeedu** [comment]
Did this get completed? Can't see anything in the README on how to do a GET with query parameters (not body).

**Comment by dgraham** [comment]
Building URLs, including query parameters, is outside the scope of the Fetch API. We use jQuery's `$.param` and `window.encodeURIComponent` to build a URL before passing it into `window.fetch`.

**Comment by niftylettuce** [comment]
My API wrapper handles this here <https://github.com/glazedio/frisbee/blob/673cff2b6887af026330e45bdaad9d4dbdeb41ea/src/frisbee.js#L91-L95> if you want some inspiration.  I think I need to `encodeURIComponent` though if it's a browser.

**Comment by eranimo** [comment]
Why is it outside the scope of the fetch API? Query parameters are part of the URL spec.

**Comment by dgraham** [comment]
You can use [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) via [`URL.searchParams`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/searchParams) or `new URLSearchParams()` to construct the query string content.

**Comment by niftylettuce** [comment]
Related https://github.com/Fyrd/caniuse/issues/2213
