### ISSUE TITLE
Timeout/End-user abort

### ISSUE THREAD

**Issue by ahutchings** [github/fetch#16]
How would I implement a timeout similar to jQuery's $.ajax `timeout` option? The fetch standard mentions an "end-user abort", but I don't see any detail on how it would be triggered.

**Comment by adambene** [comment]
@dgraham 
Hey fetch community, is there any practice or even proposal to handle timeout/end-user abort using  the fetch API?

Not being able to do this there may be memory leaks and inconsistencies.

Anyway thumbs up for fetch, really cool stuff.

**Comment by ianstormtaylor** [comment]
FWIW, I've opened an issue https://github.com/whatwg/fetch/issues/951 with a proposal for a `timeout` option that solves 90% of use cases, in case anyone's interested. I think it's super important to add to make sure calls to `fetch` (or `res.json()`) don't hang indefinitely.
