### ISSUE TITLE
Document the un-polyfillable parts.

### ISSUE THREAD

**Issue by jdalton** [github/fetch#160]
It's my understanding that relying on XHR alone leaves some `fetch` functionality missing/under-supported. It would be good to call out the limitations of the polyfill in the readme.

**Comment by mislav** [comment]
Good idea.

**Comment by phistuck** [comment]
Is the no-cookies-by-default supported, for example?
If not, this is especially confusing, since it is mentioned in the Caveats section, which makes the reader think it is supported. Looks like it is a section for general Fetch API specification caveats and not polyfill caveats.

**Comment by stereokai** [comment]
@phistuck @mislav wait, no-cookies-by-default is **not** supported? I thought it was.

**Comment by phistuck** [comment]
@stereokai - I think it is only supported for cross domain. I believe XMLHttpRequest always sends cookies for same origin requests.

**Comment by stereokai** [comment]
@phistuck Thanks.

**Comment by Mouvedia** [comment]
document responseType
- ✓ xhr
- × fetch
formData method
- × xhr
- ✓ fetch

**Comment by nfcampos** [comment]
also, maybe it's be good to point out in the readme that this being a xmlHttpRequest-based polyfill it's liable to the cross-browser inconsistencies of xmlHttpRequest (eg. IE caching GET requests to the same address)

**Comment by mislav** [comment]
Some documentation about the parts of the fetch spec that this polyfill provides is up on http://github.github.io/fetch/ now and hosted in the `gh-pages` branch in this repo. Suggestions and improvements via pull requests welcome!
