### ISSUE TITLE
A better polyfill for Promise

### ISSUE THREAD

**Issue by ysmood** [github/fetch#166]
The biggest problem of es6-promise is that it will hide the errors inside the promise, for example:

```javascript
var Promise = require('es6-promise');
new Promise(function() {
  a();
});
```
It will not warn the user about the unhandled error.

Try this one [Yaku](https://github.com/ysmood/yaku), it's smaller, faster, and more error friendly.

**Comment by dgraham** [comment]
Any Promise polyfill may be used with fetch. Thanks for letting us know about this library.
