### ISSUE TITLE
GET with parameters not just in the URL

### ISSUE THREAD

**Issue by shelling** [github/fetch#167]
In some http clients, e.g. `jQuery.ajax`, it's possible to not just put the params in the URL but an object. The client will mix/concat the params into the URL later. Is that possible to give params independently like 
``` javascript
fetch("foo.json" {
  method: "get",
  params: {
    param1: "value1",
    param2: "value2",
  }
}).then(response => response.json())
```
to come up with a URL `/foo.json&param1=value1&param2=value2`?

Also, sometimes the params may be longer than the length limitation, so that some APIs accept GET requests with a body of parameters. So I don't understand the reason `fetch` couldn't *GET* with the body like

``` javascript
fetch("foo.json" {
  method: "get",
  body: {
    param1: "value1",
    param2: "value2",
  }
}).then(response => response.json())
```

Are these behaviors allowed in the future? Maybe I can submit a pull request for these.

**Comment by dgraham** [comment]
It's best to ask for this support at the https://github.com/whatwg/fetch specification repository.

**Comment by dgraham** [comment]
[URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) is accepted as a `body` value, but it's only supported by Firefox right now.

**Comment by shelling** [comment]
@dgraham That is, if we create a polyfill for URLSearchParams it should work with this fetch polyfill?

**Comment by shelling** [comment]
@dgraham not exactly accepted. fetch polyfill is still complaining `TypeError: Body not allowed for GET or HEAD requests` 
![screen shot 2015-06-24 at 2 27 47 pm](https://cloud.githubusercontent.com/assets/4980/8341933/74b058fe-1a7d-11e5-8a75-521306012b49.png)

**Comment by fingermark** [comment]
How is this solved today?

**Comment by dgraham** [comment]
Query parameters may be encoding natively with [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) or with [jQuery.param](http://api.jquery.com/jQuery.param/).
