### ISSUE TITLE
File upload includes WebKitFormBoundary header and footer

### ISSUE THREAD

**Issue by ryancole** [github/fetch#168]
I think this is probably me doing something wrong, because I don't recall this always happening to me, but when I follow the example file upload from the readme, the resulting file that is uploaded contains the form data header and footer. Below is some client-side javascript that makes the `PUT` request to Amazon's S3 ...

```js
function putToDestination (file, signed) {

  let form = new FormData();

  form.append('file', file);

  return fetch(signed.url, {
    body: form,
    method: 'put',
    headers: {
      "Content-Type": "application/octet-stream",
      "Content-Disposition": "attachment"
    }
  });

};
```

The `signed.url` is the pre-signed S3 destination URL that I need to make the `PUT` request to. Uploading a simple text file, and then viewing the content in S3, results in the following ...

```
------WebKitFormBoundaryaxpyiPgbbPti10Rw
Content-Disposition: form-data; name="file"; filename="pgadmin.log"
Content-Type: application/octet-stream

foo bar baz

------WebKitFormBoundaryaxpyiPgbbPti10Rw--
```

Any idea why this is happening? I'm technically using fetchival, which is a wrapper around whatwg-fetch, but I distilled this down to an example using directly whatwg-fetch.

**Comment by dgraham** [comment]
A couple things you can try to narrow down the problem:
- Use the native Chrome, or Firefox Nightly, implementation of `window.fetch` without any polyfills.
- We use `fetch` to upload images that are dropped onto github.com issue comment fields. Drag an image onto a comment field and use the browser's network inspector to compare github.com upload requests to S3 with your own.

**Comment by ryancole** [comment]
Happening without any polyfills, so it's definitely just something I'm doing. With that said, I will close this as it's definitely not an issue with anything other than my code somewhere. Also noted that the request github makes to S3, when uploading images, looks quite a bit different than the one I make - notably github uses `POST` which I did not realize was an option with S3. Also no content disposition specified in the request, from github.

**Comment by ryancole** [comment]
Looks like it was because I was specifying a content type of `application/octet-stream`, which I intended to be the type of the upload, not for the request. Makes sense!

**Comment by mislav** [comment]
@ryancole Glad you solved it and followed up!
