### ISSUE TITLE
Ship minified version

### ISSUE THREAD

**Issue by kdex** [github/fetch#169]
At the moment, all that's shipped is an overly verbose (that is, unminified) version.

Most package maintainers therefore minify their scripts for browsers so that users can use tools such as `wiredep` to automatically hook up all bower modules into their markup and tools such as `usemin` to bundle them into one big file. This has one big advantage: Users can have their dependencies minified in a file without having to minify even one line themselves. Build time will therefore dramatically decrease for everyone.

Someone already mentioned this issue in #104, but it seems that this hasn't been tackled yet.

So, erm: Pretty please? :)

**Comment by mislav** [comment]
No, sorry; I'm afraid that this resolution will be the same as for the referenced issue. We don't think that users having to minify their own assets is a big hurdle when using this polyfill. Also, some users might want to use their own minifiers and minify settings. Finally, checking in a minified version in source code is a lot of work for us maintainers.

So in conclusion: you'll have to minify your own assets, including this library. And if minifying this simple 330-line program with no dependencies is bringing down your minifying tool to a halt so much that you feel having a pre-minified version would speed it up, then maybe you could try other minifying tools that might be faster.

**Comment by franciscop-invast** [comment]
For those looking for the minified version that is not provided, you can use [polyfill.io](https://polyfill.io/v2/docs/) instead, with the advantage that it will only load for the browsers that need it:

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch"></script>
```
