### ISSUE TITLE
POST + headers forces OPTIONS

### ISSUE THREAD

**Issue by maerzhase** [github/fetch#171]
if i specify the headers as you say in the readme:

```
fetch('/users', {
     method: 'post',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: 'Hubot',
        login: 'hubot',
      })
    })
```

the fetch get's executed as OPTIONS.

any ideas?

**Comment by mislav** [comment]
What is the actual URL you're posting to and does the hostname differ from the hostname of the current page?

**Comment by maerzhase** [comment]
I am working local. So both hostnames are localhost. I am also tsking care of CORS

**Comment by dgraham** [comment]
What browser are you using? Chrome and Firefox have native `fetch` implementations that cause the polyfill code to be skipped. You can compare the behavior of native `fetch` with the polyfill in a different browser.

**Comment by maerzhase** [comment]
ok that explains the behaviour! is there any workaround?

**Comment by dgraham** [comment]
Without more specific information there isn't much we can do. An OPTIONS request only occurs before making a cross-origin request to a domain that is different from the document's domain. The fetch request is not performed as OPTIONS, just the request prior to it.

**Comment by maerzhase** [comment]
jeah it works in safari but doesnt work in chrome. is there any workaround for that? the hostname ist the same. i am calling from localhost:8000 to localhost:9999 .

**Comment by dgraham** [comment]
Port number is considered part of the origin: https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by maerzhase** [comment]
so you cant use fetch with polyfill in chrome?

**Comment by mislav** [comment]
@maerzhase You can use fetch in every browser, but if you're going to make cross-domain requests, first you'll have to get yourself educated about CORS, and then you won't be surprised by the OPTIONS requests which is called a "preflight" and is normal to see in a CORS scenario.

**Comment by Kielan** [comment]
It would be nice as this is a common issue to explain how to remove OPTIONS when using fetch from browser

**Comment by maerzhase** [comment]
@Kielan did you take a look at the link from @mislav ? he quoted mozilla on CORS explaining the OPTIONS preflight. i didn't understand the preflight thing when i first opened the issue.
cheers.
