### ISSUE TITLE
Make response.json() reject the promise with the error rather than throwing

### ISSUE THREAD

**Issue by keirlawson** [github/fetch#172]
From what I can see the [Fetch spec](https://fetch.spec.whatwg.org/#concept-body-consume-body) decrees that should JSON parsing fail with a response.json() call then the resulting promise should be rejected with the error. This does not currently appear to be the case, the error instead being thrown.

**Comment by dgraham** [comment]
When an error is thrown inside a Promise's `then` handler, the `catch` handler is invoked with the error.

```js
Promise.resolve('{"a":1').then(JSON.parse).catch(function(e) { console.log(e) })`
```

**Comment by mislav** [comment]
Keep in mind that the error from `JSON.parse` using the above syntax might be wrong in Firefox: https://github.com/github/fetch/pull/157
