### ISSUE TITLE
Add entry to cdnjs

### ISSUE THREAD

**Issue by bendi** [github/fetch#173]
I can see that cdnjs has moved to github and they accept pull requests, so I'm wondering if there's any reason for not doing it?

**Comment by dgraham** [comment]
It looks like cdnjs polls git tags to find the latest releases. We semantically version each [fetch release](https://github.com/github/fetch/tags), so this should work automatically.

The preferred deployment technique is to bundle and minify all assets into a single JS file to be served to the browser. But there's no harm, other than the performance penalty, in hosting this library as a separate file in a CDN.

**Comment by bendi** [comment]
Yes but what if I'd like to use it in 2 of my web-components? Isn't this a preformance penalty to bundle fetch polyfill twice?
