### ISSUE TITLE
how do i access this from inside a then block?

### ISSUE THREAD

**Issue by pvinis** [github/fetch#178]
i would like to access this from where the fetch begins. is that possible?

**Comment by dgraham** [comment]
With [Function#bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind):
```js
var done = function(value) { console.log(this, value) }
Promise.resolve(42).then(done.bind(this))
```

Or by capturing `this` in a variable to be referenced in the function:
```js
var self = this
var done = function(value) { console.log(self, value) }
Promise.resolve(42).then(done)
```
