### ISSUE TITLE
How to set Authorization and Timeout 

### ISSUE THREAD

**Issue by sunnybogawat** [github/fetch#181]
I am doing a get request and I need to pass the authorization token in the request also I need to override the timeout setting. I haven't found any way to do that in the documentation.

**Comment by dgraham** [comment]
See [this section](https://github.com/github/fetch#post-json) of the readme for header syntax. See #175 for timeout discussion.

**Comment by sunnybogawat** [comment]
I am following the same way but when I debugged the ajax request I am not able to see the authorization token. I am doing cross origin request. 


fetch('/users', {
  method: 'post',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Authorization': 'Token token=xxxxx'
  }})

**Comment by dgraham** [comment]
The Chrome Network panel can help debug cross-origin requests.

First, disable the cache so the OPTIONS pre-flight request will occur for each cross-origin request.

![screenshot 2015-07-29 10 51 19](https://cloud.githubusercontent.com/assets/122102/8964010/6aee8ac4-35e0-11e5-9989-242c427ef021.png)

Then in the Network panel you can see both the OPTIONS pre-flight and the subsequent actual request. It's likely that OPTIONS is failing so your request is never made.

![screen shot 2015-07-29 at 10 57 06 am](https://cloud.githubusercontent.com/assets/122102/8964045/96989cd2-35e0-11e5-82f5-6028c4b02a87.png)

**Comment by sunnybogawat** [comment]
Thanks for a quick reply. I have the same setting in my chrome agent and I am passing the token to the fetch request also but somehow it failing at OPTIONS request.  Please find below screen shot to understand the workflow 

1. The Fetch Request Code - 

![capture2](https://cloud.githubusercontent.com/assets/250483/8976870/a08160aa-36b0-11e5-8f41-3ff5583fc8cb.PNG)

2. My Chrome Setting

![capture](https://cloud.githubusercontent.com/assets/250483/8976903/d6e3f158-36b0-11e5-8b9d-767900f0ee8b.PNG)

3. Get Request Created and Error Received With Request Header

![2015-07-30_1140](https://cloud.githubusercontent.com/assets/250483/8976911/f4da5c42-36b0-11e5-8efa-e6d0438ab8d6.png)


![2015-07-30_1139](https://cloud.githubusercontent.com/assets/250483/8976912/f4dd00e6-36b0-11e5-9b8c-684222d2e9ef.png)


![capture1](https://cloud.githubusercontent.com/assets/250483/8976913/f4e11172-36b0-11e5-9ab5-cae6bff9ab81.PNG)

**Comment by dgraham** [comment]
The server is returning a 401 Unauthorized response to the OPTIONS request. [HTML 5 Rocks](http://www.html5rocks.com/en/tutorials/cors/) has a good tutorial on how cross-origin requests work on the client and server.
