### ISSUE TITLE
What are the oldest browsers and mobile browsers that this polyfill (w/promise polyfill) will work on?

### ISSUE THREAD

**Issue by jeffbski** [github/fetch#183]
I see in the readme that it mentions latest chrome, ff, IE9, Safari and there is another comment at top about having some older browser support if you add a promise polyfill.

I guess my question is more about what browsers won't it work on if we include the promise polyfill. Or said differently what are the oldest browsers and mobile browsers that this will work with?

I would like to use fetch as my new http client, but I just need to know what limitations that is placing on that use, especially mobile browsers.

**Comment by dgraham** [comment]
[Can I use](http://caniuse.com/#feat=promises) is a good reference for browser `Promise` support, including mobile browsers.

**Comment by jeffbski** [comment]
@dgraham are you saying that this fetch API will polyfill and work on all browsers that I can polyfill Promises? or did you not really understand my question?

**Comment by jeffbski** [comment]
I'm asking about where this fetch polyfill will work. If I include a promise polyfill, then how old of browsers can I use with fetch?

Are promises really the only limitation here?

**Comment by dgraham** [comment]
The readme lists the browsers that we test on and support in production. We don't use fetch on mobile because the Promise polyfill is so large (we use XMLHttpRequest instead). But, if you want to try it out and report back, we can update the supported browser list.

**Comment by jeffbski** [comment]
ok. I'll have to leave that to someone else since I don't have nearly enough hardware to test with. I guess I'll stick with XMLHttpRequest libs until promise support is popular enough.

**Comment by hbrls** [comment]
@dgraham I have enough page views from a static site and where I did insert a stats script for the resolution. What should I test to make sure:

1. native OK for fetch and promise
2. or OK after the es6-promise polyfill

**Comment by dgraham** [comment]
Safari in iOS 8.4 and the browser in Android 4.4.4 are the first to support the `Promise` API. Previous mobile operating system versions will require the es6-promise polyfill in order to use `fetch`.

The percentage of your visitors using versions older than that will determine when fetch is viable.

**Comment by hbrls** [comment]
Do you have deps other than Promise?

**Comment by mislav** [comment]
No deps other than Promise and XMLHttpRequest 2.
