### ISSUE TITLE
Support cloning of Responses

### ISSUE THREAD

**Issue by kirill-konshin** [github/fetch#185]
According to MDN https://developer.mozilla.org/en-US/docs/Web/API/Response/clone and the spec https://fetch.spec.whatwg.org/#dom-response-clone `Response` class should have a `clone()` method, which seems to be missing now.

**Comment by mislav** [comment]
Good catch. Care to make a pull request?

**Comment by kirill-konshin** [comment]
Cloning of `Headers` is trivial -- just call `new Headers(this.headers)`, primitives can be easily cloned as well, the biggest question is how to clone body's Blob or FormData instances and whether it is needed.

It seems that `Blob` can be cloned by calling `blob.slice(blob.size)` which returns a new blob. But `readBlobAs*` functions in polyfill can read same blob multiple times and since blobs are immutable, it should be safe to just pass the same blob as new body.

From what I see in https://developer.mozilla.org/en-US/docs/Web/API/FormData there is no way to get keys/values and iterate through them filling a new FormData instance with values... But based on implementation nuances and lack of ability to actually read `FormData` I think it's fine to pass the same instance of FormData body too.

The new `Response` will have `bodyUsed = false` anyway, so even if source `Response` has been read already, new one will still be readable...

If you agree with passing non-cloned bodies then I can make a PR in the next few days.

P.S. Method `Body.formData()` should resolve with a `FormData` object, not with a text:

```js
this.formData = function() {
    return this.text().then(decode)
}
```

In polyfill `text()` with `FormData` body will throw an exception anyway. I should probably file a separate bug for that.

**Comment by mislav** [comment]
> Method `Body.formData()` should resolve with a FormData object, not with a text:

Thanks for looking into this. One thing that baffles me is that Chrome's fetch implementation doesn't have the `formData()` method for some reason.

**Comment by kirill-konshin** [comment]
I suppose that `Body.formData()` is not implemented because `FormData` is totally useless so far. You can write but you cannot read.

I'll make a PR.

**Comment by kirill-konshin** [comment]
After quite a while I finally had time to implement PR: https://github.com/github/fetch/pull/209
