### ISSUE TITLE
Should fetching local files always results in a TypeError?

### ISSUE THREAD

**Issue by presstube** [github/fetch#186]
Hi there,

When loading local files I bump into `TypeError: Network request failed` right away due to the `response.status` of local requests being `0`, thus getting rejected by [fetch's initial status handling](https://github.com/github/fetch/blob/master/fetch.js#L313-L316).

In the README I see the portion on [Handling HTTP error statuses](https://github.com/github/fetch#handling-http-error-statuses), but that would only work if fetch's initial `xhr.onload` didn't reject with a TypeError first.

Would it be reasonable to change fetch's initial status handling to something like this so that local fetches could make it through?
```
if ((status !== 0 && status < 100) || status > 599) {
    reject(new TypeError('Network request failed'))
    return
}
```

For context. I'm working on a project in which the same codebase runs:
1. In Browser, loading local files via a local dev server (no problems here)
2. [Ejecta](https://github.com/phoboslab/ejecta) in iOS, loading purely local files (which is where I'm getting my `status === 0`)

Thanks!

**Comment by mislav** [comment]
I would be down to treating `0` status as success but only if the URL scheme was `file:`. How does native fetch implemented in Chrome and Firefox behave with regard to local files?

**Comment by presstube** [comment]
I took a look and  it turns out that the native implementations of fetch don't like loading local files either.

Chrome:
```
Fetch API cannot load file:///Users/someuser/someproject/some-local-file.json. URL scheme "file" is not supported.
```

Firefox (only when I explicitly catch, otherwise it's silent)
```
TypeError: NetworkError when attempting to fetch resource.
```

**Comment by dgraham** [comment]
Closing because the polyfill behaves the same as native browser implementations when loading local files.

**Comment by mislav** [comment]
> the polyfill behaves the same as native browser implementations when loading local files.

I don't think that's true. I think our polyfill allows loading local files, but native implementations don't.

**Comment by dgraham** [comment]
The following rejects with an `Error` in Chrome, Firefox, and the polyfill.

```js
fetch('file:///tmp/test.txt').catch(function(e) { console.log(e) })
```

Is something else being requested in this issue? I may be misunderstanding it.

**Comment by mislav** [comment]
This code works on Safari:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Fetch Tests</title>
</head>
<body>
  <script>
    nativeFetch = window.fetch
    window.fetch = undefined
  </script>
  <script src="../fetch.js"></script>
  <script>
    fetch('../package.json')
      .then(function(res){ return res.text() })
      .then(function(text){ console.log('polyfill', text) })
  </script>
</body>
</html>
```

**Comment by mislav** [comment]
Even though Safari allows XMLHttpRequest using the `file:` protocol (and we do nothing in the polyfill to prevent it) Chrome and Firefox access restrictions disallow it. Still, the error thrown as a result of that XHR restriction doesn't match the TypeError thrown when native fetch is used.

But, we might not want to care about this mismatch. "Fixing" the type of the error thrown would be too much work since detecting `file:` protocol URLs may be tricky.

**Comment by LMLB** [comment]
Firefox does allow XMLHttpRequest and Fetch on local files if they are in the same directory (or a subdirectory) relative to the HTML file.
