### ISSUE TITLE
Document usage instructions with popular module loaders (Webpack, Browserify, etc.)

### ISSUE THREAD

**Issue by thomasboyt** [github/fetch#193]
It looks like the README used to have instructions on usage with Browserify, but it has been removed for reasons I don't understand: https://github.com/github/fetch/commit/01797bceb6e07d0a0b2090915c4cd0df52f7bb5d

It can be difficult to figure out how to use a global-attaching polyfill in Webpack or Browserify. Adding these instructions to the README would be very helpful. I'd be happy to contribute updated instructions if the PR would be accepted :)

Previous PRs:

- Webpack instructions (closed for unknown reasons): https://github.com/github/fetch/pull/110
- Browserify instructions (potentially still accurate, outside of module name): https://github.com/github/fetch/blob/4b9e44493cfcab97077dd2d7be6a8364292ea03a/README.md#using-with-npm-and-browserify

**Comment by mislav** [comment]
> It can be difficult to figure out how to use a global-attaching polyfill in Webpack or Browserify.

With no JavaScript loaders it's as simple as:

```html
<script src="fetch.js"></script>
```

(Replace `fetch.js` with the appropriate name of bundle file when all dependencies are concatenated as a single JS bundle.)

If the equivalent is difficult to achieve with Webpack or Browserify, we expect that users of these module loaders know how to load source files in their web pages. If they don't, that have a bigger problem than our lack of installation instructions.

**Comment by matiassingers** [comment]
@thomasboyt in regards to Webpack I wrote a small little post about how to use `fetch`: http://mts.io/2015/04/08/webpack-shims-polyfills/

**Comment by dgraham** [comment]
@matiassingers :sparkles:
