### ISSUE TITLE
IE8 and IE9 support

### ISSUE THREAD

**Issue by mariusGundersen** [github/fetch#2]
What is the reason this does not work in IE8 and IE9? Could it be made so a shim or polyfill is all that is needed for older browsers to work?

**Comment by tobireif** [comment]
"The browsers listed in the support matrix are guaranteed to work well with this polyfill because we support them at GitHub. IE9 can be made to work by adding the Promise polyfill listed at the top of the readme."

This needs to be mentioned in the readme.

**Comment by mnpenner** [comment]
So has anyone actually tested this in IE8? I've got all the polyfills.

**Comment by mislav** [comment]
@mnpenner The latest stable release 1.0 only supports IE10+. If you need to support IE9 you can use v0.11.x. If you need IE8 support you will need to fork the "0.11" branch and make your changes appropriately.
