### ISSUE TITLE
Append blob size to Content-Length headers

### ISSUE THREAD

**Issue by tresdin** [github/fetch#200]
[Response class](https://fetch.spec.whatwg.org/#response-class) mentions about appending `Content-Type` but `Content-Length`. I wonder what makes `Content-Length` not possible for being appended.

**Comment by dgraham** [comment]
Questions about the specification can be asked at the [whatwg/fetch](https://github.com/whatwg/fetch) repository.

**Comment by domenic** [comment]
StackOverflow is better. whatwg/fetch is for reporting bugs in the specification. Asking questions about using the API should be on StackOverflow.
