### ISSUE TITLE
Body.document()

### ISSUE THREAD

**Issue by Mouvedia** [github/fetch#204]
To be on par with xhr you need that method.
https://fetch.spec.whatwg.org/#body vs https://xhr.spec.whatwg.org/#xmlhttprequestresponsetype

related: slightlyoff/ServiceWorker#462

**Comment by mislav** [comment]
This library is just the polyfill for the functionality described in the fetch spec. Nothing of the sort is described in the spec right now. If you want this functionality added to the spec, you'll have to [suggest it there](https://github.com/whatwg/fetch/issues). Sorry!

**Comment by Mouvedia** [comment]
@mislav the suggestion existed but it was closed.
If you think it would be useful ask to reopen.

**Comment by mislav** [comment]
I'm not sure what `document()` does, but if you think it's useful, please do suggest that it gets reconsidered for the fetch standard. It's just that you'll have to do it in the other repo rather than here. Thanks!
