### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by lancecarlson** [github/fetch#206]
I'm assuming if I want to use browserify, I should just require this package? Is there a better way to do a check on whether or not the browser already has fetch, then require if it doesn't?

**Comment by mislav** [comment]
We used to have Browserify instructions [#21], but now link only to Webpack instructions from our README. I'm not sure what the proper way to load with Browserify would be, but if you want to check if a browser supports fetch before loading this polyfill, just check for existence of `window.fetch`.

However, the polyfill is small enough to simply load unconditionally and let it figure out whether there's browser native support of not.

Details of loading with various module loaders is left as an excercise to the reader and outside the scope of this repo. Thanks!
