### ISSUE TITLE
Error: Incorrect Header Check

### ISSUE THREAD

**Issue by designermonkey** [github/fetch#207]
>Uncaught (in promise) Error: invalid response body at: http://xxx/latest?from=11&size=10 reason: data error: incorrect header check(…)

I'm very confused by this. I can get this working fine through PHP's local server, but as soon as I run it through an nginx server, I get this error message. The browser (both Chrome and Firefox) show me the correct request and response headers, and even returned content in the Network panel, but the request is still discarded in favour of an error by this JS.

Any insight as to what this may be?

**Comment by designermonkey** [comment]
I think this may be related, but sadly I am not a node person, so don't know what it means for this library.

The only header difference between the servers is the content encoding being gzip on nginx.

http://stackoverflow.com/questions/19438884/incorrect-header-check-when-using-zlib-in-node-js

**Comment by designermonkey** [comment]
I'll add that this code is packaged together using Browserify to be used in a browser, if that helps.

**Comment by dgraham** [comment]
Chrome and Firefox [don't use the polyfill](https://github.com/github/fetch/blob/1afa3d27bb5098abcc5b3282783ec3dc34213e4b/fetch.js#L4-L6) code, so this must be something in the browser or server. You might try using `curl -i` to test the URL and view the response headers.

**Comment by rossthedevigner** [comment]
@designermonkey Did you ever find a solution? I started running into the same situation today.

> Error: invalid response body at: reason: data error: incorrect header check
    at Gunzip.at Gunzip.<anonymous>
    at Gunzip.EventEmitter.emit
    at Zlib.mode._binding.onerror 
    at Zlib._error)
    at Zlib._write)
    at Item.run at drainQueue

**Comment by matejsvajger** [comment]
@rossthedevigner How did you get around the problem with isomorphic-fetch? I keep getting the same error.

**Comment by josephrocca** [comment]
In case this is useful to anyone else: I was accidentally setting the `content-encoding` header on the server to an encoding (`gzip`) that was different to the actual response (`br`). So then the client (which in this case is `node-fetch`) tries to decompress a `br`-encoded response using `gzip`.
