### ISSUE TITLE
How do you get JSON body from a 400 bad request?

### ISSUE THREAD

**Issue by tkiethanom** [github/fetch#210]
The API I'm working with responds with 400 Bad Request, with the specifics of the error in the body as JSON. How do I extract this from response? response.statusText just gives me 'Bad Request'.

```
{
    "message": "(psycopg2.IntegrityError) duplicate key value violates unique constraint \"accounts_name_key\"\n"
}
```

**Comment by matthew-andrews** [comment]
I suggested this: https://github.com/matthew-andrews/isomorphic-fetch/issues/36#issuecomment-144851958
