### ISSUE TITLE
Does not work for cors requests on IE9

### ISSUE THREAD

**Issue by robin-barnes-triptease** [github/fetch#211]
Cors requests on IE9 fail with 'Access Denied'.

**Comment by matthew-andrews** [comment]
IE9 doesn't support CORS properly.  At the FT we ended up using jsonp in this case and built a little library to help with that:- https://github.com/Financial-Times/n-jsonp-fetch

It's _possible_ get the polyfill working with IE9's CORs but it's really not a nice development experience and there's a lot of gotchas.  Highly recommend against that.  Here's a PR that kind of works:- https://github.com/github/fetch/pull/79
