### ISSUE TITLE
Should not restrict the status code

### ISSUE THREAD

**Issue by micky2be** [github/fetch#214]
At the following lines it's clear that the status code is enforced to be between 100 and 599.
https://github.com/github/fetch/blob/master/fetch.js#L313-L316

But in some cases servers/APIs can return a custom status code higher than 599.

**Comment by mislav** [comment]
I'm not sure if we should officially support status codes higher than 599, since those don't seem to be part of the HTTP spec. [HTTP/1.1 only defines](https://pretty-rfc.herokuapp.com/RFC2616#status.code.and.reason.phrase) the first digit to be in the range of 1–5.

**Comment by micky2be** [comment]
That should be up to the developers using the fetch library. 
We already have to check for 2xx anyway. 
Getting blocked beforehand doesn't do any good for the people expecting receiving this status.

**Comment by mislav** [comment]
We do this check mostly because of IE, which returns large error codes to signal various network errors. If you want to support status codes > 599, you have to come up with an idea of how to detect IE network errors in another way.

**Comment by micky2be** [comment]
Why would fetch need to filter it??
Like I said, let the developers using fetch do it. 
Fecth on Chrome doesn't filter. Node doesn't filter. So why this library do?
Why adding limitation?
Doing the following by a user/developer should be enough to me. 


```js
function checkStatus(response) {
  if (response.status >= 200 && response.status < 300) {
    return response
  } else {
    var error = new Error(response.statusText)
    error.response = response
    throw error
  }
}
fetch(api).then(checkStatus);
```

**Comment by ronkorving** [comment]
This is a polyfill, so I would expect it to stick to standards (the standards for the fetch API, not HTTP), or if those are lacking in clarity, to do what the majority of browsers do. If that is to let the 6xx go through, I think this library should too, right? Limiting developers from receiving these codes can be a blocker. The opposite case cannot be made.

**Comment by mislav** [comment]
> Why would fetch need to filter it??

@micky2be Please read my above comment again:

> We do this check mostly because of IE, which returns large error codes to signal various network errors. If you want to support status codes > 599, you have to come up with an idea of how to detect IE network errors in another way.

So if we find a reliable way to detect IE network errors, we can remove the filter.

**Comment by dgraham** [comment]
Good discussion about two competing concerns: passing *intentionally* invalid status codes from the server through to the client vs supporting IE 9's invalid client status codes. I'm closing this out though, because supporting IE 9 is more important right now.

In a few months we can consider removing the IE 9 support in a 2.0 release. Those needing legacy support could still use the 1.x line. Fetch has been stable for enough time that supporting a 1.x and 2.x line wouldn't be too much work.

**Comment by micky2be** [comment]
Do we still need to support IE9?

**Comment by ronkorving** [comment]
v1 can support it, if someone could just release a v2 that removes that support?

**Comment by mislav** [comment]
We can drop IE9 support going forward. :+1:

**Comment by ronkorving** [comment]
\o/

**Comment by ronkorving** [comment]
\o/

**Comment by micky2be** [comment]
Yeah!! Thanks guys
