### ISSUE TITLE
Polyfill for URL() constructor?

### ISSUE THREAD

**Issue by onlywei** [github/fetch#215]
Hello,

Is this part of `window.fetch` somehow? I notice it's in one of the spec examples, but it's not available in all browsers: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

Should the polyfill get added here?

Thanks.

**Comment by dgraham** [comment]
The URL polyfill can be added to projects as needed. The fetch polyfill does not use URL so we don't need to reference it here.
