### ISSUE TITLE
Publish new npm version

### ISSUE THREAD

**Issue by wtfil** [github/fetch#221]
Hi!
I am using `whatwg-fetch@0.9.0` and found this error in Safari
`TypeError: null is not an object (evaluating 'value.toString')`
 
But this bug already fixed in master https://github.com/github/fetch/commit/527a0945f69935e6cd4de840567a551e7eeb1cf3.

Can you please publish latest code to npm?
Thank you!

**Comment by jonastebbe** [comment]
+1

**Comment by mislav** [comment]
It's done! :shipit:

**Comment by wtfil** [comment]
@mislav Thx:)
