### ISSUE TITLE
Custom response headers problem 

### ISSUE THREAD

**Issue by byterussian** [github/fetch#222]
Hi,

After a Sign Up/login I send auth details in header response(with [devise-token-auth](https://github.com/lynndylanhurley/devise_token_auth)), example:

```
access-token: 0JWKgHr13QOGVK_dxKv8lg
token-type: Bearer
client: CnU3V37QLLovcEr_oslIDg
expiry: 1446038562
```

but `headers.get` returns null for these keys:
```
> response.headers.get('access-token')
null

> response.headers.get('client')
null
```

It's a know issue? 

<img width="475" alt="screen shot 2015-10-14 at 15 39 51" src="https://cloud.githubusercontent.com/assets/72166/10485348/efe58184-7289-11e5-882a-76bf2d120115.png">
<img width="505" alt="screen shot 2015-10-14 at 15 39 20" src="https://cloud.githubusercontent.com/assets/72166/10485356/f4746378-7289-11e5-911b-faf45f529745.png">

**Comment by byterussian** [comment]
Nevermind, I missing the `Access-Control-Expose-Headers` header in my CORS settings.

**Comment by lynndylanhurley** [comment]
@byterussian - can you show me how you're making the requests to devise-token-auth?

When I try, the preflight (OPTIONS) goes through, but the actual request isn't sent.
