### ISSUE TITLE
is there an "always" function?

### ISSUE THREAD

**Issue by chovy** [github/fetch#223]
I want to execute when either a .then or a .catch is called. Typically this is handled with a `.always`

**Comment by dgraham** [comment]
```js
var done = function(response) { console.log('response', response) }
var fail = function(error) { console.log('error', error) }
var always = function() { console.log('always') }
Promise.resolve(42).then(done).catch(fail).then(always, always)
```

**Comment by mislav** [comment]
@chovy Unfortunately, Promises don't have an `.always()` method. You need to attach an `always` handler as both resolve and error handler to cover both cases. Clumsy, I know!

**Comment by rustanacexd** [comment]
So how do we execute an always call?

**Comment by mislav** [comment]
@rustanacexd: See @dgraham's code above.

**Comment by leorojas86** [comment]
I did this:

class Platform {
  static init() {
    if(Platform.isiOS()) {//.finally is not supported by promise for iOS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
      Promise.prototype.finally = function(callback) {
        return this.then(callback)
          .catch(callback);
      };
    }
  }

  static isiOS() {
    return /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
  }
}

and just called Platform.init() from the application, then I can use .finally for promises as normal on iOS :)
