### ISSUE TITLE
finally?

### ISSUE THREAD

**Issue by clearly** [github/fetch#226]
Add support for Promise finally? Or is there a workaround?

**Comment by TrySound** [comment]
@clearly finally is not standard promise api. So not :)

**Comment by mislav** [comment]
Please see https://github.com/github/fetch/issues/223#issuecomment-148927226

**Comment by sandstrom** [comment]
If anyone else stumble on this, `.finally` is making its way into the spec. Until then wrapping the response from `.fetch` in a shim-library that support finally should work.

https://github.com/tc39/proposal-promise-finally

**Comment by TrySound** [comment]
@sandstrom proposal is not spec yet. In any case it's not related to this package. Polyfill for this feature will work with any codebase.

**Comment by sandstrom** [comment]
@TrySound yes I know and agree with you on all points.

My comment above was written to help people who end up here after googling `fetch + finally`.

**Comment by kytwb** [comment]
Annnnnnnd it's 2017.

**Comment by TrySound** [comment]
@kytwb What and? It's not related to this project.

**Comment by leorojas86** [comment]
I did this:

```
class Platform {
  static init() {
    if(!Promise.prototype.finally) {//.finally is not supported by promise for iOS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
      Promise.prototype.finally = function(callback) {
        return this.then(callback)
          .catch(callback);
      };
    }
  }
}
```
and just called `Platform.init()` from the application, now I can use `.finally` for promises as normal on iOS :).

**Comment by AndyOGo** [comment]
@TrySound Please reopen this

**Comment by TrySound** [comment]
I'm can't.)

**Comment by AndyOGo** [comment]
I'm convinced you can, seems you are a smart fellow 👍

**Comment by TrySound** [comment]
I'm not collaborator of this project and it's not my issue.

**Comment by AndyOGo** [comment]
Oh, I see

**Comment by AndyOGo** [comment]
@mislav Please reopen

**Comment by TrySound** [comment]
@AndyOGo I don't think it makes any sense. This package uses global `Promise` constructor. There is nothing you could do here. Just use polyfill for `finally`.

**Comment by mislav** [comment]
Like @TrySound said: the `fetch` polyfill doesn't implement any aspect of Promises. If you want access to `finally`, you will have to use a Promise polyfill that implements `finally` even if a native browser implementation of Promise already exists.
