### ISSUE TITLE
Using this library in commonjs environment

### ISSUE THREAD

**Issue by IonicaBizau** [github/fetch#231]
This library is :cool:!!! I'm using it in one of my projects and I want to `require` it in my code, bundling everything with Browserify.

The `fetch.js` file doesn't `module.exports` anything currently. I would suggest to make it export the `fetch` function (even it's the native one or not).

Then we could do:

```js
var fetch = require("whatwg-fetch")

fetch(...)
```

Just an idea. I'm not sure if it's good to be implemented or not since the `fetch` function is anyway a global, but the code looks better and clearer this way than just `require("whatwg-fetch")` (without a variable name) in my file. :memo: 

Looking forward for your feedback. :smile:

**Comment by dgraham** [comment]
See https://github.com/github/fetch/issues/184#issuecomment-126774267 for a discussion of module loaders.

**Comment by IonicaBizau** [comment]
@dgraham Ohhh, totally understand! Thanks! :innocent:
