### ISSUE TITLE
include a header on the output file

### ISSUE THREAD

**Issue by lukeapage** [github/fetch#234]
So that its possible to see what version is fetched and where the code is from, it would be useful to add a little header with the version number

**Comment by dgraham** [comment]
I'm not sure what this is referring to. Can you explain in more detail?

**Comment by lukeapage** [comment]
Sorry bad wording considering this is fetch.
on the output file (i.e. https://github.com/github/fetch/blob/master/fetch.js)
add a header e.g.
```
/*  fetch.js polyfill
*  https://github.com/github/fetch
*  v0.10.1
*/
```

We include the file directly in our project and do not want to modify it, but it is nice to see the version of the file and where it came from within the file without adding our own header..

**Comment by dgraham** [comment]
> We include the file directly in our project and do not want to modify it, but it is nice to see the version of the file and where it came from within the file without adding our own header..

A good solution here is for your script, that pulls the fetch.js file into your repository, to add the git tag to the top of the file.

Doing this from our end would complicate the build process, and we use bower and npm to pull in dependencies, so their version and source is traceable via the package manager.
