### ISSUE TITLE
rename self to window

### ISSUE THREAD

**Issue by niftylettuce** [github/fetch#238]
otherwise we can't have tests that run on a node runtime environment simulating a browser (e.g. using jsdom or jsdomify)

**Comment by stkrzysiak** [comment]
@niftylettuce  I keep stumbling on your comments, I think we've been having some of the same grievances lately.  Have you considered using isomorphic-fetch as a work around?   That is my current plan of attack with this.

**Comment by niftylettuce** [comment]
yes I have and check out my pull request and project called Frisbee

**Comment by niftylettuce** [comment]
@stkrzysiak https://github.com/niftylettuce/frisbee/blob/master/test/unit/browser.test.js#L28-L33 because of this

**Comment by niftylettuce** [comment]
@stkrzysiak ignore this -- I have to patch and use `jsdom` instead of `jsdomify` per <https://github.com/tmpvar/jsdom/issues/1203#issuecomment-160730614>
