### ISSUE TITLE
What happens with status 304?

### ISSUE THREAD

**Issue by neothemachine** [github/fetch#241]
The `checkStatus` example in the READMe checks for 2xx, and this is also what [`Response.ok`](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) checks. But what about 304? jquery for example explicitly includes this status in its OK check. Why is this different for fetch? Or isn't it? It's confusing me a bit.

**Comment by dgraham** [comment]
The Fetch spec defines 304 as a [null body status](https://fetch.spec.whatwg.org/#null-body-status). It also defines the behavior for [loading responses from cache](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch).

I haven't worked with 304 Not Modified fetch responses, but I suspect it will resolve with the cached 200 response transparently. You might try it and report back on the behavior.

**Comment by neothemachine** [comment]
You are right about the behavior, both Firefox and Chrome return the cached 200, both when no actual request took place and also when a 304 came back (which I could observe with the network tab of the debug view). And this is true for both fetch and xhr. Which makes me wonder why jquery has 304 in as a check anyway. Must be to support older or broken browser implementations.
