### ISSUE TITLE
Odd line break \n in `res._bodyInit`

### ISSUE THREAD

**Issue by niftylettuce** [github/fetch#244]
The `res` object returned from `.then((res) => {` has a line break in it if a network error occurred or if there was something like a `404`.  I get a response of `Cannot POST /forgot-password\n`, and I'm not sure why it has a trailing `\n`.

**Comment by mislav** [comment]
Sorry, but:

1. Where is this odd line break? Is in the the `response.text().then((responseText) => ... )` value?
2. Why were you not expecting a line break?
3, How does this extra character break your program?
4. Are you sure the server doesn't send the line break itself?
5. Have you used a HTTP debugging proxy to verify this?
6. What are you suggesting we should fix?
7. Is this behavior with just our polyfill or does it affect Chrome and Firefox native implementations?

**Comment by niftylettuce** [comment]
@mislav ignore this - it's from a node app, per #245 i had a node process running in the background as a process that was responding :facepalm:
