### ISSUE TITLE
statusText should fallback to _bodyInit?

### ISSUE THREAD

**Issue by niftylettuce** [github/fetch#245]
If a 404 occurs and the server doesn't send a response at all (e.g. there's a network error), then `res.statusText` is blank and in order to show the actual error I can't use err.message, I want to use _bodyInit, but just monkey patching this to fallback doesn't seem right to me... here's my use case:

```js
          if (!res.ok) {

            let err = new Error(
              typeof res.statusText === 'string' ?
              res.statusText : res._bodyInit
            );

            // As inspired by Stripe
            // <https://goo.gl/QFLdGM>
            try {
              body = JSON.parse(res._bodyInit);
              if (typeof body === 'object' && typeof body.error === 'object') {
                err = new Error(body.error.message);
                if (body.error.stack)
                  err.stack = body.error.stack;
                if (body.error.code)
                  err.code = body.error.code;
                if (body.error.param)
                  err.param = body.error.param;
              }
            } catch (e) {} finally {
              throw err;
            }

          }
```

see #244 as there's an odd line break in `_bodyInit`

**Comment by mislav** [comment]
What are you saying that our library does wrong here and what do you suggest as a workaround?

I don't see how a server could respond with a 404 but not send a response at all. How is it a 404 then? Network failures will result in promise being rejected.

You shouldn't use `_bodyInit` because it's an internal property and it will probably not be available in native implementations of `fetch` in Chrome and Firefox.

**Comment by niftylettuce** [comment]
sorry @mislav I had a node process running despite shutting down terminal, ignore this issue

**Comment by dgraham** [comment]
@niftylettuce One thing to try, before opening issues here, is to confirm the behavior in Chrome and Firefox. They both provide native `fetch` implementations. This polyfill code only runs in Safari and IE.
