### ISSUE TITLE
Extracting RequestInit causes an error

### ISSUE THREAD

**Issue by tylerrash** [github/fetch#260]
This works as a expected:

    fetch('/api/foo', {
        method: 'post',
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({ name: 'foo' })
    })
        .then(res => res.json())
        .then(console.log.bind(console));

But this makes tsc unhappy:

    const url = '/api/foo';
    const body = JSON.stringify({ name: 'foo' });

    const config = {
        method: 'post',
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },
        body
    };

    fetch(url, config)
        .then(res => res.json())
        .then(console.log.bind(console));

Throwing the following error:

    error TS2345: Argument of type '{ method: string; headers: { 'Accept': string; 'Content-Type': string; }; body: string; }' is not assignable to parameter of type 'RequestInit'.
        Types of property 'headers' are incompatible.
            Type '{ 'Accept': string; 'Content-Type': string; }' is not assignable to type 'Headers | string[] | { [index: string]: string; }'.
                Type '{ 'Accept': string; 'Content-Type': string; }' is not assignable to type '{ [index: string]: string; }'.
                    Index signature is missing in type '{ 'Accept': string; 'Content-Type': string; }'.

Version info:

    $ tsc --version
    message TS6029: Version 1.7.5

**Comment by dgraham** [comment]
This is a TypeScript data type mapping error. The [HeadersInit](https://fetch.spec.whatwg.org/#headersinit) and [RequestInit](https://fetch.spec.whatwg.org/#requestinit) definitions from the specification might help to map the data types.
