### ISSUE TITLE
How to make a post request with JSON data in application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by vishalvijay** [github/fetch#263]
```
let data = {
	a: "some data",
	b: 33,
	c: [
		{
			name: "XYZ",
			other: true
		},
		{
			name: "ABC",
			other: true
		}
	]
	d: {
		something: true
	}
}
```
How to make a POST request with above JSON data, as content-type `application/x-www-form-urlencoded` using fetch api?

**Comment by mislav** [comment]
You need to serialize it yourself to a string. If you're using jQuery, then you can use `$.param(data)` to serialize it. Don't forget to specify the `Content-type` header for the request.

However, if your server accepts JSON, it would be much easier to just `JSON.stringify(data)` and post JSON instead.

Anyway, we can't help you with details about communicating with your server. The `fetch()` standard itself doesn't handle any encoding strategies. It's all left to the user.

**Comment by vishalvijay** [comment]
Thanks @mislav 

Server can't accept JSON data, that is the all problem. I'm trying to solve this with out jquery. Any suggestion?

**Comment by mislav** [comment]
I can't solve this problem for you. You could take a look at [Zepto's `$.param` implementation](https://github.com/madrobby/zepto/blob/601372ac4e3f98d502c707bf841589fbc48a3a7d/src/ajax.js#L344-L370) and try to copy it. You would have to rewrite it a little bit to not make it dependent on `$.isFunction`, `$.isArray`, `$.type` and `$.each`.

**Comment by dgraham** [comment]
You might also consider using [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects) as the post body. Server endpoints that accept application/x-www-form-urlencoded frequently accept multipart/form-data as well.

**Comment by vishalvijay** [comment]
:+1:

**Comment by yakirn** [comment]
For anyone else who might still have this problem, I've implemented mislav suggestion using lodash here:
https://gist.github.com/yakirn/831e5e7fcdfb50fc6c94

**Comment by tiemevanveen** [comment]
@dgraham using 

```
fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    body: new FormData(postData)
})
```

results in this formData why I try it...

```
------WebKitFormBoundarybJk1vnBHdSvQEKdD--
```

![image](https://cloud.githubusercontent.com/assets/1330668/14500645/2856996a-01a3-11e6-8890-b34e62740f2d.png)

**Comment by dgraham** [comment]
A `FormData` request body automatically sets the Content-Type to `multipart/form-data`. Overriding the header with a different type, like in the above example, probably won't work.

A [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) request body automatically sets the Content-Type header to `application/x-www-form-urlencoded;charset=UTF-8`.

https://fetch.spec.whatwg.org/#body-mixin

**Comment by tiemevanveen** [comment]
That makes sense.

Too bad we need yet another polyfill for that to work..

```{js}
import URLSearchParams from 'url-search-params';

const searchParams = new URLSearchParams();
for (const prop in params) {
  searchParams.set(prop, params[prop]);
}


fetch(url, {
  method: 'POST',
  body: searchParams
})

```

And that only works for flat objects..

And then again, when the data is that simple, a manual conversion isn't that hard as well. 

```{js}
const searchParams = Object.keys(params).map((key) => {
  return encodeURIComponent(key) + '=' + encodeURIComponent(params[key]);
}).join('&');

fetch(url, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
  },
  body: searchParams
})
```

Thanks for the quick reply and the insight!

**Comment by zxzl** [comment]
@tiemevanveen Thanks for simple urlencoder :)

**Comment by zhouyingkai1** [comment]
@tiemevanveen  Thanks

**Comment by nitinja** [comment]
How I solved this:

I am using "qs" package for stringifying/encoding the json

My Request code:

```
        fetch('http://localhost:8888/oauth2/token',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
          },
          body: qs.stringify({
            grant_type: 'password',
            username: 'user_name',
            password: "user_password"
          })
        })
```

this makes server call as 

![image](https://cloud.githubusercontent.com/assets/3931042/22969323/2166d898-f394-11e6-9b53-28fb461c99f3.png)

**Comment by LuisHansen** [comment]
I got this working by using JSON.stringify and the correct headers:
![image](https://cloud.githubusercontent.com/assets/7854445/24102231/ff17b5b6-0d59-11e7-95f1-0442217680b9.png)

**Comment by tarlig** [comment]
@nitinja This solved it for me! Thanks a lot

**Comment by vikas199** [comment]
enable to get data should get the data in the array of books
fetch('https://reactnd-books-api.udacity.com/search', {
    method: 'POST',
    headers: {
       'Accept': 'application/json',
      'Authorization': 'whatever-you-want',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ query, maxResults })
  }).then(res => res.json())
    .then(data => console.log(data))

**Comment by wxianfeng** [comment]
@nitinja 
can use `qs` in React ?

**Comment by hifni** [comment]
Where can I get help on `fetch`?

**Comment by SeanFloresDOMO** [comment]
> This is how I solved for that issue. It was also a problem in jsfiddles echo. I got lazy and used jQuery in the end. Hope this helps others. https://jsfiddle.net/6mnk6kkq/
```javascript
function GetSomeDeferredStuff() {
  var deferreds = [];
  for (let count = 1; count <= 10; count++) {
    var params = {
      html: '<p>Task #'+count+' complete.',
      delay: count
    }
```
> Encode the data
```javascript
   const searchParams = Object.keys(params).map((key) => {
     return encodeURIComponent(key) + '=' + encodeURIComponent(params[key]);
   }).join('&');
```
> Push fetch requests to an array
```javascript
    deferreds.push(
      fetch("/echo/html/",
      {
          method: "POST",
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
          },
          body: searchParams
      })
      .then(r => r.text())
      .then(data => log(data))
    );
  }
  return deferreds;
}
```
> Log for debugging however
```javascript
function log(html){
	console.log(html);
	$("div").append(html);
}
```
> Execute using jquery or Promise.All() if preferred
```javascript
$(function() {
    $("a").click(function() {
        var deferreds = GetSomeDeferredStuff();

        $.when.apply($, deferreds).done(function(e,i) {
            $("div").append("<p>All done!</p>");
        });
    });
});
```

**Comment by malpanianshul** [comment]
@nitinja  Thanks a lot

**Comment by tawfikbougerba** [comment]
I have problem with post request authentification while trying to run the code I get error invalide request does anyone know how I could solve this problem, I get this error { error: 'invalid_request' }








`const express = require('express');
   
const fetch = require('node-fetch');
const btoa = require('btoa');
const { catchAsync } = require('./utils');
const router = express.Router();
    
const CLIENT_ID = 'CLIENT_ID ';
const CLIENT_SECRET = 'CLIENT_SECRET';
const creds = btoa(`${CLIENT_ID}:${CLIENT_SECRET}`);
const redirect = encodeURIComponent('http://localhost:50451/callback');
    
router.get('/login', (req, res) => {
   res.redirect('https://flow.polar.com/oauth2/authorization?response_type=code&client_id=client_id');
});

router.get('/list', catchAsync(async (req, res) => {
   if (!req.query.code) throw new Error('NoCodeProvided');
      const code = req.query.code;
      const creds = btoa(`${CLIENT_ID}:${CLIENT_SECRET}`);
   
      fetch('https://polarremote.com/v2/oauth2/token', {
         method: 'POST',
         data : {
            'grant_type' : 'authorization_code',
            'redirect_uri' : redirect,
            'code' : code
         },    
         headers : {
            'Authorization':`Basic ${creds}`,
            'Content-Type':'application/x-www-form-urlencoded',
             'Accept':' application/json;charset=UTF-8'
         }
      })
      .then(function(response) {
          return response.json();
          console.log(response.json());
       }).then(function(body) {
           console.log(body); 
           res.send('POST');
       });
 })`

**Comment by tawfikbougerba** [comment]
I have problem with post request authentification while trying to run the code I get error invalide request does anyone know how I could solve this problem, I get this error { error: 'invalid_request' }



const  dat = {
              'grant_type': 'authorization_code',
              
              'code':code ,
               "redirect_uri" : redirect
               };
     
const URLSearchParams = Object.keys(dat).map((key) => {
  return encodeURIComponent(key) + '=' + encodeURIComponent(dat[key]);
}).join('&');


 fetch('https://polarremote.com/v2/oauth2/token',
 {

  method: 'POST',
  headers: {
    'Authorization':`Basic ${creds}`,
    
    'Content-Type': 'application/x-www-form-urlencoded',
     'Accept':'application/json; charset=utf-8'

  },
  data: URLSearchParams
 
}).then(function(res) {
    return res.json();
}).then(function(body) {
    console.log(body);
});

**Comment by legnaro** [comment]
Thanks a lot! Very useful this code!

**Comment by rayj10** [comment]
@nitinja I wish I had seen ur post sooner!! been fiddling around with fetch for a week now trying to firgure out if I did the body formatting wrong cos I can't get the API to recognize the body of my request and now finally it's working! YOU'RE A LIFE SAVER!
