### ISSUE TITLE
Setting specific cookies

### ISSUE THREAD

**Issue by FoxxMD** [github/fetch#266]
I'm using [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) with this [isomorphic application](https://github.com/erikras/react-redux-universal-hot-example) and part of my authentication strategy entails using [encrypted cookies](https://github.com/mozilla/node-client-sessions) to store a token on the client.

When using client-side rendering this works perfectly as I have `credentials: 'same-origin'` set in the options for `fetch` and all requests are made from the client, so the cookie gets sent.

However when I choose to render server-side I need to be able to get that encrypted cookie from the initial request (sent by the client) and then attach it to requests made by `fetch` on the server.

In the isomorphic application they use `superagent` and are able to do this like so:

```js
if (__SERVER__ && req.get('cookie')) {
  request.set('cookie', req.get('cookie'));
}
```

but I can't see a way to do the same thing with `fetch`. Is this possible?

**Comment by dgraham** [comment]
I haven't used isomorphic-fetch, but this might work:

```js
request.headers.getAll('Cookie')
```

If not, you might ask in the isomorphic-fetch repository.
