### ISSUE TITLE
How can I perform sync call?

### ISSUE THREAD

**Issue by ziziermao** [github/fetch#267]
May I ask how can we make a sync call. I was trying to do:
```
response = fetch(url, {
            credentials: 'same-origin',
            redirect: 'error',
            async: false,
        }).catch(function(e){
           // catch exception.
        });
        return response.json();
```

I am pretty sure the response return json, but looks like this is not the correct way to call it. Could anyone please suggest? I am trying to avoid callback

**Comment by dgraham** [comment]
Synchronous requests are not a feature of fetch. Responses must be handled in a Promise.
