### ISSUE TITLE
Is there some way to overwrite response headers?

### ISSUE THREAD

**Issue by SunboX** [github/fetch#273]
I've a problem. Windows 10 Mobile caches the response of GET requests. You can force Windows Mobile to not cache it, if you overwrite the response headers with `Cache-Mode: no-cache,no-store`. But I don't have any idea how to achieve this.By now I'm appending a "cachebuster" time stamp to the GET parameters. But that looks bit ugly / hacky. I can't change the header server side.

**Comment by dgraham** [comment]
Sending a query string parameter with a unique timestamp value is the traditional work around for this problem. This implementation of `fetch` uses `XMLHttpRequest`, which does not provide a method of setting response header values.
