### ISSUE TITLE
Usage with babel and ES6 

### ISSUE THREAD

**Issue by abimelex** [github/fetch#275]
I try to use the package with babel and es6
`import fetch from 'whatwg-fetch';`

Unfortunately I get the following error:

`Uncaught TypeError: (0 , _whatwgFetch2.default) is not a function`

**Comment by TrySound** [comment]
@abimelex 
Description 
> A window.fetch JavaScript polyfill.
fetch do not export modules.
You can do
```js
import 'whatwg-fetch';
// And then just use global variable.
fetch(...);
```

**Comment by abimelex** [comment]
Ah thank you, thats perfect.

**Comment by TrySound** [comment]
Don't forget to close issue if you found answers.

**Comment by webjay** [comment]
I solved it with `import 'isomorphic-fetch';` in my `jest-setup.js`.
