### ISSUE TITLE
Trouble uploading files

### ISSUE THREAD

**Issue by Pungsnigel** [github/fetch#276]
Having trouble uploading files using FormData and fetch. It might very well be my code thats broken, but I can't find whats wrong. My code:
```
export function updateProfilePicture(apiKey, userID, picture) {
  let data = new FormData();
  data.append('firmware', picture);
  return fetch(`${API_URL}/v1/${ROOT}/update_profile_picture/${userID}`,{
      headers: {'Authorization': `Token token=${apiKey}`},
      method: 'POST',
      data: data
    }
  ).then(response => response.json());
}
```

Looking at the request, it seems that no file is included.

**Comment by dgraham** [comment]
It should work as long as `picture` is a [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) from a `FileList`.

You can also create a `FormData` instance from a form element that contains an `<input type="file">`.

```js
const form = document.querySelector('.js-picture-form')
const body = new FormData(form)
```

**Comment by Pungsnigel** [comment]
Just in case someone else makes the same mistake: The error in the code above is the name of the property used to include the FormData in the request. It should of course be 'body'.
