### ISSUE TITLE
Cross Origin Request when Access-Control-Allow-Origin is set to *

### ISSUE THREAD

**Issue by tylerwgoza** [github/fetch#277]
Currently I get the following error when attempting a Cross Origin Request: 
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource ... (Reason: CORS header 'Access-Control-Allow-Origin' does not match '*').` 

I only get this error when I set then `credentials: 'include'` option without it the request works but an authentication cookie I have won't submit. 
Just wondering if there was a workaround for this or if this is just the browsers behavior when Access-Control-Allow-Origin was set to *. I've been searching for an answer and can't find one.

**Comment by dgraham** [comment]
> Important note: when responding to a credentialed request,  server must specify a domain, and cannot use wild carding.

— https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Requests_with_credentials

**Comment by tylerwgoza** [comment]
Thanks. Much appreciated!
