### ISSUE TITLE
Response object is undefined if the server returns 204 status code.

### ISSUE THREAD

**Issue by cluk3** [github/fetch#279]
don't know if this is a bug or an expected behavior, but i think it should at least return a response object with body = null.

Sample code:
```
fetch(uri, options)
  .then( (response) => {
    console.log(response) // undefined
    if(response.ok) {
     // this will never be executed
    }
 })
```

**Comment by dgraham** [comment]
Which browser are you using? Chrome and Firefox use a native fetch implementation rather than this polyfill code.

**Comment by cluk3** [comment]
i only tested it on Firefox and Chrome.

**Comment by mislav** [comment]
@cluk3 We do have [tests covering the HTTP 204 scenario](https://github.com/github/fetch/blob/a9f49ab0875e284dbd0eda9be5004949e31b4161/test/test.js#L781-L788) and they pass both on polyfill implementation and native implementations in Chrome and Firefox.
