### ISSUE TITLE
How to do a no-cors request to flickr open api?

### ISSUE THREAD

**Issue by morgs32** [github/fetch#280]
This is more of a question than an issue. A question to you but an issue to me. I'm trying to use fetch to hit the flicker open api, or to make cross origin requests in general, and can't. I've gathered that I should use `mode: 'no-cors'` but that results in an "opaque" response, which doesn't provide me the json data I need.

Even though I can see in the network tab that the JSON was sent back with the response, in fact.

Any help would be a big help!?

Here's a codepen. The request works with jquery. Not with fetch.
http://codepen.io/morgs32/pen/OMGEpm

**Comment by dgraham** [comment]
Flickr does not support CORS headers on `api.flickr.com`, so `fetch` and `XMLHttpRequest` will not work.

jQuery is sending a JSONP request and evaluating the JavaScript served in Flickr's response with an injected `<script>` element.

**Comment by vga-** [comment]
The issue claims that the fetch is unsuccessful in general. I have tried to do a simple fetch of github.com, as the example demonstrates, and I have been unsuccessful. Is there some trick not included in the example code?

**Comment by dgraham** [comment]
[Cross-origin resource sharing](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) requires the participation of the server via the `Access-Control-Allow-Origin` response header. We don't serve that header from the `github.com` domain, but we [do support CORS](https://developer.github.com/v3/#cross-origin-resource-sharing) from `api.github.com`.

Compare the results of the following requests:

```js
fetch('https://github.com')
fetch('https://api.github.com')
```

**Comment by vga-** [comment]
Thanks, I thought this might be the case, but since the example uses github.com. rather than api.giuthub.com, I thought it might be the case that it was supposed to work. I'll put in a pr to change the example.
