### ISSUE TITLE
Cross site post request not submitting authentication cookie with 'credentials' set to 'include'

### ISSUE THREAD

**Issue by shangsunset** [github/fetch#284]
Hi,

Im making a cross site post request to an express api backend. However, data passed from fetch request wont be saved in the session even though i set `credentials` to `include`, and corresponding headers in the server. i dont get any errors, its just the request is not submitting authentication cookie. I've been searching for answers, but no luck getting it work.

Thanks.

server:
```javascript

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(session({
  secret: 'ssshhhhh',
  resave: true,
  saveUninitialized: true,
  cookie: { 
    httpOnly: false
  }
}));

app.use(function(req, res, next) {
  res.set("Access-Control-Allow-Origin", "*");
  res.set('Access-Control-Allow-Credentials', true)
  res.set("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});

app.post('/api/users', function(req, res) {

    req.session.accessToken = req.body.accessToken;
  
  ...
})

app.get('/api/users/token', function(req, res) {
  console.log(req.session);
  if (req.session.accessToken) {
    return res.json({ accessToken: req.session.accessToken });
  }
  return res.json({ accessToken: null });
})
```
client:

```javascript

  fetch('http://localhost:3000/api/users', {
    credentials: 'include',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    },
    method: 'post',
    body: JSON.stringify({     
      accessToken: user.accessToken,
      name: user.name,    
    })
  })
  .then(res => res.json())
  .then(json => {
    console.log(json);
  })
  .catch(error => {
    console.log(error);
  });
```

headers in request:
```

{ host: 'localhost:3000',
  accept: '*/*',
  'if-none-match': 'W/"4d-oW2yTGBOs6aaA4LAPgNxNQ"',
  cookie: 'connect.sid=s%3AHXDL6Az0hRZeSGsJgjhw4kvVONBLz-yn.sOOAqbxaLQ6Z%2FfCdfGOmXf9XsYl3JdHvP%2FmfkUln1xA',
  'user-agent': 'cairn/1 CFNetwork/758.2.8 Darwin/15.3.0',
  'accept-language': 'en-us',
  'accept-encoding': 'gzip, deflate',
  connection: 'keep-alive' }
Session {
  cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: false } }
GET /api/users/token 304 23.780 ms - -
{ host: 'localhost:3000',
  'content-type': 'application/json',
  cookie: 'connect.sid=s%3A1jat379BSZQCKvJV1pKL4_Cub9ApMFVI.m%2BQHkIewMl9Uzjg315GTC5aD5qpWESiQVNDnXrFFSbQ',
  connection: 'keep-alive',
  'if-none-match': 'W/"270-toaMUba3dhoaPENGp5EGaA"',
  accept: 'application/json',
  'accept-language': 'en-us',
  'content-length': '484',
  'accept-encoding': 'gzip, deflate',
  'user-agent': 'cairn/1 CFNetwork/758.2.8 Darwin/15.3.0' }
POST /api/users 200 52.485 ms - 622

```

**Comment by mislav** [comment]
What is this user agent "cairn/1 CFNetwork/758.2.8 Darwin/15.3.0"? From where are you making these requests?

**Comment by shangsunset** [comment]
It's a react native app

**Comment by Download** [comment]
> res.set("Access-Control-Allow-Origin", "*");

Try replacing `*` here with the actual origin (should be set as request header `Origin`).
You cannot use the wildcard i.c.w. credentials. See e.g. [this stackoverflow answer](http://stackoverflow.com/a/19744754/286685).

**Comment by shangsunset** [comment]
Hey, by origin, do you mean the back end server domain? I tried putting
`localhost:3000` before but it didn't change anything.

**Comment by mislav** [comment]
I'm afraid we can't offer assistance here. Cookie header processing is left entirely up to the browser and trying to manipulate those headers whilst making XHR requests is forbidden. On top of that, you're making a native app, which I presume ultimately runs in some sort of Webkit webview, where certain behaviors might deviate by design from typical mobile Safari.

There's nothing we can do or fix through this polyfill, and I recommend that you search for other ways to persist session and authentication details, such as custom HTTP headers or GET/POST params.

**Comment by shangsunset** [comment]
Got it, thanks.
