### ISSUE TITLE
If-None-Match being added to request

### ISSUE THREAD

**Issue by JakeGinnivan** [github/fetch#288]
I am trying to stop fetch sending the `If-None-Match` header but can't seem to do it. The issue is that the response headers from the cache are not available if the server sends a 304. I am trying to use fetch to get all github repositories.

```
function getAllPages(githubToken, currentResults, response) {
  var next
  if (response.headers.link && (next = parseLinkHeader(response.headers.link).next)) {
    return fetch(next, {
      method: 'GET',
      cache: 'no-store',
      headers: {
        Accept: 'application/json',
        Authorization: 'token ' + githubToken
      }
    }).then((r) => {
      return getAllPages(githubToken, currentResults.concat(r.json()), r)
    })
  }

  return currentResults
}

return fetch('https://api.github.com/user/repos?affiliation=owner,collaborator,organization_member', {
    method: 'GET',
    cache: 'no-store',
    headers: {
      Accept: 'application/json',
      Authorization: 'token ' + githubToken
    }
  }).then(checkStatus).then((response) => {
    return getAllPages(githubToken, response.json(), response)
  })
```

In my request I am getting `If-None-Match:W/"...."` added to my request. How can I stop this happening? I can't see anything in the spec which explains this behaviour. What have I missed?

**Comment by dgraham** [comment]
A native `window.fetch` implementation provides [granular cache control](https://fetch.spec.whatwg.org/#concept-request-cache-mode) via the `cache` request option in your example. However, the polyfill doesn't have access to the cache with `XMLHttpRequest`, so it uses the browser's default caching behavior.

Ignoring caching headers from the GitHub API is not recommended. We serve those to prevent excessive requests for data that's already cached in the client.

**Comment by JakeGinnivan** [comment]
@dgraham can I get access to the headers of the cached requests? The response doesn't contain the link to the second page, so the cached response is of quite limited use without that.

**Comment by dgraham** [comment]
Header names are not exposed directly as properties on the `Headers` object, like in the `response.headers.link` example.

The [`Headers.get`](https://developer.mozilla.org/en-US/docs/Web/API/Headers/get) and [`Headers.getAll`](https://developer.mozilla.org/en-US/docs/Web/API/Headers/getAll) methods return the value for a name.

```js
var url = headers.get('Link')
var urls = headers.getAll('Link')
```
