### ISSUE TITLE
Getting all headers, mismatch between the specs and polyfill and implementations

### ISSUE THREAD

**Issue by lukeapage** [github/fetch#292]
So MDN says to use
```
headers.entries();
```
the fetch spec says the Headers object is iterable itself (so it should have a `Symbol.iterator` function)

and then the polyfill has `forEach`

Looking at chromes fetch we have

![image](https://cloud.githubusercontent.com/assets/309321/13664673/f62b211e-e6a8-11e5-879d-f253db804b2b.png)

and firefox has

![image](https://cloud.githubusercontent.com/assets/309321/13664784/79bec22e-e6a9-11e5-93ab-7ec54463512b.png)

so I guess to be forwards compatible I have to try to use forEach and fall-back to either an iterator on headers itself or entries..

Should an iterator be added and forEach removed so that people donm't think that forEach is guarenteed to be present when not polyfilled?

[Edited to be more correct about iterator on headers directly]

**Comment by dgraham** [comment]
Interesting, Firefox has [previously had support](https://github.com/github/fetch/issues/149) for `forEach`, but it's missing now. Headers has `forEach` in Firefox Nightly builds, so it looks like it is returning.

I don't think it's possible to polyfill an ES6 iterator, at least not without a heavy download size increase.

**Comment by lukeapage** [comment]
Its actually easy to write an iterator e.g.
1. If Symbol && Symbol.iterator
2. Have a function on headers prototype with the name Symbol.iterator, have it return an object
3. The object has only a next function on it, calling it iterates through the results returning an object with value - an array of header name, value and done a boolean for if iteration has finished

I dont think you should close this unless forEach goes back in the spec.. even if ff reintroduces, some ff dont have it and there is high chance it will be removed (or in a new browser not supported) in the future

**Comment by dkfiresky** [comment]
> Once `Headers.prototype[Symbol.iterator]` is defined this special casing will no longer be needed.

`Symbol.Iterator` is optional as default behavior described:

> If object is a Headers object, copy its header list as headerListCopy and then for each header in headerListCopy, retaining order, append header's name/header's value to headers. Rethrow any exception.

**Comment by lukeapage** [comment]
@dkfiresky that sounds like the sentence describing the Headers constructor (constructing a new Headers from a Headers instance). Not sure how it effects `Symbol.Iterator` - that needs to be defined for something to be iterable which is what the current spec says.

**Comment by dkfiresky** [comment]
@lukeapage (the Fetch spec)[https://fetch.spec.whatwg.org] says that `Headers` object can be constructed both ways: by using `Symbol.Iterator` or by simply using `forEach` to iterate over key/value pairs. So I believe that using of `Symbol.Iterator` is optional.

**Comment by lukeapage** [comment]
Yes @dkfiresky that is about constructing Headers and what can be passed to the constructor.

I am talking about consuming a Headers instance and the spec says it is iterable but no forEach method on it.

**Comment by dkfiresky** [comment]
@lukeapage ok, I agree, but this polyfill is only for Fetch spec. `Symbol.iterator` should be implemented in all supported browsers then. Otherwise as @dgraham noticed:
> I don't think it's possible to polyfill an ES6 iterator, at least not without a heavy download size increase.

**Comment by lukeapage** [comment]
Yes. I am saying you should do if Symbol && Symbol.Iterator then add one as it is low cost, not adding a heavy download size as suggested.
