### ISSUE TITLE
Neither then() nor catch() executed when request timeout in Safari

### ISSUE THREAD

**Issue by fabioberger** [github/fetch#294]
In Safari V9.0.3 (10601.4.4), neither `then()` nor `catch()` is called when a request timeout occurs. Instead, Safari prints out the following error to the console:

![screen shot 2016-03-11 at 3 43 22 pm](https://cloud.githubusercontent.com/assets/2151492/13718571/0951f338-e7a0-11e5-9ab8-4290786b2bd0.png)

In Chrome V49.0.2623.87 (64-bit), the `catch()` callback is properly executes as expected. 

Test Script Used:

```
fetch('http://10.255.255.1') // a non-routable IP address
    .then(function(response) {
        console.log("response.ok", response.ok);
    }).catch(function(error) {
        console.log('Failed: ', error)
    });
```

Without either `then()` or `catch()` being called on timeout, how are we supposed to handle this type of request failure for Safari browsers?

**Comment by mislav** [comment]
Thanks for bringing this to our attention. This seems to be a limitation of XMLHttpRequest in Safari. I'm not sure if there's something we can do about this, but on your end you can definitely install an [ad-hoc timeout like suggested here](https://github.com/github/fetch/issues/175#issuecomment-125779262). This will at least ensure that non-routable requests eventually get rejected.

**Comment by fabioberger** [comment]
Thanks for the quick response Mislav, I've gone ahead and filed a bug report for the Safari team at Apple and in the mean time will implement the timeout as you suggested.

**Comment by dgraham** [comment]
@mislav I think this is asking for:

```js
xhr.ontimeout = function() {
  reject(new Error('timeout'))
}
```

so that the promise is not trapped in the pending state.

@fabioberger What is the `error` object returned by Chrome and Firefox in your `catch` example?

**Comment by fabioberger** [comment]
@dgraham The error returned from the catch in Chrome is:
```
TypeError: Failed to fetch
    at TypeError (native)
```
Full console output:

<img width="840" alt="screen shot 2016-03-12 at 1 03 38 pm" src="https://cloud.githubusercontent.com/assets/2151492/13725318/e78ab29a-e852-11e5-8062-224ae8100a07.png">

**Comment by jaafarexcz** [comment]
> In Safari V9.0.3 (10601.4.4), neither `then()` nor `catch()` is called when a request timeout occurs. Instead, Safari prints out the following erro
r to the console:
> 
> ![screen shot 2016-03-11 at 3 43 22 pm](https://cloud.githubusercontent.com/assets/2151492/13718571/0951f338-e7a0-11e5-9ab8-4290786b2bd0.png)
> 
> In Chrome V49.0.2623.87 (64-bit), the `catch()` callback is properly executes as expected.
> 
> Test Script Used:
> 
> ```
> fetch('http://10.255.255.1') // a non-routable IP address
>     .then(function(response) {
>         console.log("response.ok", response.ok);
>     }).catch(function(error) {
>         console.log('Failed: ', error)
>     });
> ```
> Without either `then()` or `catch()` being called on timeout, how are we supposed handle this type of request failure for Safari browsers?

9

**Comment by jaafarexcz** [comment]
#294

 #294

**Comment by jaafarexcz** [comment]
#294
