### ISSUE TITLE
It will be good to add URLSearchParams support

### ISSUE THREAD

**Issue by btd** [github/fetch#296]
To make it possible to use x-www-urlencoded data.

Thanks.

**Comment by mislav** [comment]
It might be out of scope for this polyfill. How do you intend to use this?

**Comment by btd** [comment]
At [current spec](https://fetch.spec.whatwg.org/#body-mixin) Body mixin can accept URLSearchParams to set Content-Type to be **application/x-www-urlencoded**.

**Comment by mislav** [comment]
Is there already some URLSearchParams polyfill? We could suggest that people use it in combination with this polyfill. Should we also add special handling of URLSearchParams bodies?

**Comment by btd** [comment]
I found only [this one](https://github.com/WebReflection/url-search-params), looks good to me.
I do not think need anything very special. If passed URLSearchParams set Content-Type to be application/x-www-urlencoded and use .toString() to get value.
```
var p = new URLSearchParams()
p.append('a', 10)
p.append('b', 'abc')
p.toString() // "a=10&b=abc"
```

**Comment by mislav** [comment]
> If passed URLSearchParams set Content-Type to be application/x-www-urlencoded and use .toString() to get value.

Sounds good. Want to make a pull request for this?

People would need to include the URLSearchParams polyfill themselves.
