### ISSUE TITLE
Fetch polyfill not working with Safari Technology Preview

### ISSUE THREAD

**Issue by cesarandreu** [github/fetch#303]
Using [Safari Technology Preview](https://webkit.org/blog/6017/introducing-safari-technology-preview/) Version 9.1.1 (11601.6.10, 11602.1.25), when I try using fetch:

```js
fetch('/')
```

It returns a rejected promise:

```
Promise {status: "rejected", result: "Fetch is not yet implemented"}
```

**Comment by dgraham** [comment]
Thanks for the report. We're following the nightly build progress as fetch is implemented natively in Safari too.

**Comment by bvaughn** [comment]
@dgraham Not sure I understand your response. Why does STP fail with "_Fetch is not yet implemented_" then (and how is this not a bug?)

**Comment by dgraham** [comment]
The preview browser build provides a native `window.fetch` that isn't working yet. The polyfill won't override a native implementation so we see this in the console.

```
> window.fetch
< function fetch() {
    [native code]
}
> fetch('/')
< Promise {status: "rejected", result: "Fetch is not yet implemented"}
```

Presumably the stubbed native `window.fetch` function will be fully implemented before shipping in a real Safari release.

**Comment by bvaughn** [comment]
This makes the Safari Technology Preview ... _much_ less useful, at best. To have a native implementation that fails is much worse than having none at all, since it also breaks polyfills (and any apps that rely on `fetch` to function).

**Comment by bvaughn** [comment]
FYI a released WebKit Bugzilla issue seems to be https://bugs.webkit.org/show_bug.cgi?id=151937

**Comment by dgraham** [comment]
https://twitter.com/jonathandavis/status/715315412791988225

**Comment by bvaughn** [comment]
Thanks for the update @dgraham! :)

**Comment by mislav** [comment]
It was a pretty bad call on their part to provide a stubbed but useless `window.fetch` function, but let's stay hopeful for the next update. 👍

**Comment by mislav** [comment]
BTW you can force the polyfill taking place if you nulify `window.fetch` before loading the polyfill:

```html
<script>
  if (detectSafariPreview()) window.fetch = undefined
</script>
<script src="./fetch.js"></script>
```

**Comment by dgraham** [comment]
http://thread.gmane.org/gmane.os.opendarwin.webkit.devel/28072

**Comment by rastersize** [comment]
The native `fetch` API [has been disabled](https://trac.webkit.org/changeset/199081/) until it’s ready. The change is available in the newly released version 2 of STP. See the [release notes](https://webkit.org/blog/6098/release-notes-for-safari-technology-preview-release-2/)

**Comment by pedropolisenso** [comment]
Hey Guys, I have a problem with Safari version 10.0.1. I think that an is problem of compatibility. Someone had this same problem using JavaScript?

**Comment by mislav** [comment]
@pedropolisenso:

1. This thread was about Safari Technology Preview. You are using Safari stable version.
2. You haven't actually told us exactly what kind of problem you have.
3. All of our tests pass on Safari 10.0.1. If you think there is a bug, please send some failing code in a separate, or even better, a failing test. Thanks!

**Comment by pedropolisenso** [comment]
Hey @mislav 

I'm sorry. I thought that had a problem, but the problem were on PC of the client. It was a problem with certification apple. Thank you!
