### ISSUE TITLE
Polyfill doesn't load on Safari Technology Preview

### ISSUE THREAD

**Issue by rbiggs** [github/fetch#305]
Today Apple released Safari Technology Preview. This is a developer ready version of what Apple intends to ship in the next version of Safari, as opposed to Webkit nightlies. I'm noticing that the polyfill for fetch doesn't seem to load. This may be because the Technology Preview has stubs in place for fetch, etc. but has not implemented it yet. The polyfill works fine with the current releases of Safari and with the Webkit nightly.

https://developer.apple.com/safari/technology-preview/release-notes/

**Comment by dgraham** [comment]
We're tracking this over in #303.
