### ISSUE TITLE
`request.clone()` doesn't preserve the original request

### ISSUE THREAD

**Issue by wmadden** [github/fetch#308]
The purpose of the `clone()` method is to allow reuse of the (normally single-use) `Body` of the request. Unfortunately, the implementation in this polyfill doesn't allow that.

To illustrate the problem, this example code will fail:

``` js
var r1 = new Request('http://somewhere.com', { method: 'POST', body: 'test' });
var r2 = r1.clone();
r1.text(); // --> fails - but should succeed
r2.text(); // --> succeeds
```

The `clone()` method in this polyfill just [delegates to the constructor](https://github.com/github/fetch/blob/master/fetch.js#L317-L319), but the constructor is supposed to consume the stream of the original request ([which it does](https://github.com/github/fetch/blob/master/fetch.js#L297)), and the `clone()` method is supposed to leave it untouched.

**Comment by wmadden** [comment]
It should probably be doing something equivalent to what the `Response.clone()` method does: https://github.com/github/fetch/blob/master/fetch.js#L364-L371

**Comment by mislav** [comment]
Thanks for reporting! Could you look into how native implementations in Chrome and Firefox handle this, and what the whatwg spec recommends in this case, if anything?

It would be great if you opened a PR for this by adding extra tests for these `clone()` cases.

**Comment by scarlac** [comment]
I had a look. The spec wants a copy of the Request for `clone()` but without the body which will be copied separately by re-reading the original stream. Since this polyfill is not stream based, a simple re-use of the copy-constructor with a bogus body and then overriding the body produces the same effect.

An alternative would be to clone all properties excluding any body-related ones. I actually implemented that but went away from it because this is a bit cleaner.

I also added an extra test based on the code in this issue.
Let me know what you think.

// Seph

From the spec:
> To **clone** a request request, run these steps:
> 
> Let _newRequest_ be a copy of _request_, except for its body.
> 
> If _request_'s body is non-null, set _newRequest's_ body to the result of cloning request's body. Rethrow any exceptions.
> 
> Return _newRequest_.

and

> To **clone** a body body, run these steps:
> Let «_out1_, _out2_» be the result of teeing body's stream. Rethrow any exceptions.
> 
> Set body's stream to out1.
> 
> Return a body whose stream is out2 and other members are copied from body.
> 

Chrome 51 produces the following output:
> &gt; var r1 = new Request('http://somewhere.com', { method: 'POST', body: 'test' });
> <· undefined
> &gt; var r2 = r1.clone()
> <· undefined
> &gt; r1.text();
> <· Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
> &gt; r2.text()
> <· Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}

**Comment by mislav** [comment]
@scarlac Thanks for looking into. I see that you started a commit with some fixes. Care to make this into a pull request? Thanks!

**Comment by mislav** [comment]
@scarlac Ah I see that you opened a pull request already. I didn't see a cross-reference here because you referenced this issue number in PR title but not body. (Cross-references are only counted when they are in issue/PR body.)

**Comment by scarlac** [comment]
@mislav, Let me know if you need more changes to the PR for it to be acceptable. I'll be happy to refine it further.
