### ISSUE TITLE
Support referrer and cache control

### ISSUE THREAD

**Issue by montogeek** [github/fetch#309]
Hi!
Does this library support referrer and cache control?

Ref: https://hacks.mozilla.org/2016/03/referrer-and-cache-control-apis-for-fetch/

**Comment by dgraham** [comment]
The polyfill uses XMLHttpRequest, which does not provide API to change referrer or cache behavior. These features of `fetch` are only available in native browser implementations.

Related discussion in https://github.com/github/fetch/issues/288#issuecomment-195800822.
