### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource - firefox issue 

### ISSUE THREAD

**Issue by jcimoch** [github/fetch#310]
Hi, I have simple function for logout that looks like this
```js
public logoutHandler() {
    fetch('/logout', <RequestInit>{
      method: 'get',
      credentials: 'include'
    }).then((response) => {
      console.log(document.cookie);
      window.location.href = '/login';
    });
  }
```
It is workin in chrome but in firefox I get "TypeError: NetworkError when attempting to fetch resource.1 (unknown)". Client side app is on the same server as backend, I'm using https connection with self-signed cert, could it be the issue?

**Comment by dgraham** [comment]
Firefox contains a native fetch implementation and does not use this polyfill code. You can use the Network tab in Firefox's web console to debug the request and response.

**Comment by ariden83** [comment]
On chrome, I've got "TypeError: Failed to fetch"
On firefox, the same "TypeError: NetworkError when attempting to fetch resource"
..

**Comment by jstoja** [comment]
Have you check errors like CORS?

**Comment by billytianlan** [comment]
@ariden83 did you figure out what was causing the errors? I'm seeing the same issues in isolated cases

**Comment by fabdarice** [comment]
Can we reopen this ticket?
I'm seeing the same error, but only on Firefox.
Also, nothing shows up in the Network tab.

**Comment by seeba8** [comment]
I have the same problem now too, in firefox only. It does not work in the web extension for firefox, but it does work if I open the respective site and try it in the web console when I am on that site.
I have the respective site in my web extension permission array.

**Comment by ncaq** [comment]
There maybe relational link.

[Fetch api not working in firefox addon : firefox](https://www.reddit.com/r/firefox/comments/5yhwob/fetch_api_not_working_in_firefox_addon/)
[1346447 - Fetch api not working within addon](https://bugzilla.mozilla.org/show_bug.cgi?id=1346447)

**Comment by ganeshangler** [comment]
I'm seeing the same error,except chrome

**Comment by iamsoorena** [comment]
I have the same exact issue. everything is fine in chrome but firefox caches wrong fetch response. and the worst of all is that it caches this error as response of that particular endpoint of my api for a LONG time.

**Comment by jomo** [comment]
Having the same issue when I have `network.http.referer.XOriginPolicy` set to `1` ("send a referrer only when the base domains are the same"). Is that supposed to happen? I'm quite sure the base domain of `localhost` matches the base domain of itself :)

**Comment by manoharreddyporeddy** [comment]
Related issue.

I was accessing Function app, via Logic app, when I got the above error.

Following worked for me:

1. Function app > Platform features tab > API > CORS > Allowed Origins > (remove all, Save)
2. Function app > Platform features tab > API > CORS > Allowed Origins > * > Save (that is add * and save)
3. Function app > Overview tab > Restart

Hope that helps.

**Comment by aguayUmbt** [comment]
@manoharreddyporeddy  function app > platform features tab etc 
what are those?

**Comment by manoharreddyporeddy** [comment]
@aguayUmbt they are menu/sequence of operations to be done in the Azure portal

**Comment by niranjanreddy891** [comment]
I am having the same issue as @jcimoch mentioned. Can anyone tell me how to solve this

**Comment by niranjanreddy891** [comment]
@jcimoch, I am having the same issue. Please tell me how to debug it. :)

**Comment by hantatsang** [comment]
For those who are writing Firefox addon, the [solution here](https://www.reddit.com/r/firefox/comments/5yhwob/fetch_api_not_working_in_firefox_addon/) helped me, I have to add `"*://localhost/*"`
to `permissions` key in `manifest.json`:

```

  "permissions": [
    "storage",
    "*://localhost/*"
  ],
```

Chrome just works without the need to add this permission...

**Comment by Barracuda6** [comment]
If anyone comes across this, I had the same error in Firefox (but with a different application) and it turns out it was because the (self-signed) SSL certificate I was using on the server was not trusted in Firefox. I added the self-signed root CA to Firefox and all was well.

**Comment by thehme** [comment]
In our case, the solution was not using the wild card for `Access-Control-Allow-Origin`, instead our settings look like this:

```
res.setHeader('Access-Control-Allow-Origin', req.headers.origin);
res.setHeader("Access-Control-Allow-Headers", "Authorization, Cache-Control, Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers");

```

**Comment by Hervera** [comment]
Check if you are using http or https on your server. For me, the error was coming online with heroku server because they use https while in local machine I was using http and it was working. 
After choosing https for my endpoints, it worked

**Comment by x011** [comment]
I managed to solve the problem by monitoring the headers returned by github used on the demo page.
Since I'm using a python webserver, the headers look like:

```
self.send_header("Access-Control-Allow-Origin", "*")
self.send_header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
self.send_header("Access-Control-Allow-Headers", '*');
self.send_header("Status", "200 OK")
self.send_header("Vary", "Accept")
self.send_header('Content-Type', 'application/octet-stream')
```

Hope it helps.

**Comment by rohanaceres** [comment]
For me, Swagger UI for some reason crashes when I use examples that consume multilanguage resource files. So I removed the examples from Swagger config and Swager UI started working properly again - of course, without examples.

**Comment by willwillis** [comment]
Happened to me, Jupyter wouldn't behave until i renamed ./lib/twitterlib.py to something without "lib" in the file name... something to do with lib/*lib.py.. maybe ?

**Comment by sebastian-palma** [comment]
Tried in a Rails 6 only-api app with CORS enabled, using NGROK and no luck.

Tried instead

```javascript
{
  ...
  "permissions": [
    "storage",
    "<all_urls>"
  ]
}
```

and got it working.

**Comment by Leslie-Wong-H** [comment]
Same issue. But what is particular in my situation is that I need to fetch a blob url, like "blob:https://images.google.com.hk/9143673d-b976-4416-b29c-85ce48a77da6". 

However, if I declare manifest.json as 
```
{
   ...
   "permissions": [
       "blob:*",
    ]
} 
```
Firefox does not recognize it, and throws a warning message, "Reading manifest: Warning processing permissions: Error processing permissions.1: Value "blob:*" must either: must either [must either [be one of ["clipboardRead", "clipboardWrite", "geolocation", "idle", "notifications"], be one of ["bookmarks"], be one of ["find"], be one of ["history"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["topSites"], be one of ["activeTab", "tabs", "tabHide"], be one of ["browserSettings"], be one of ["cookies"], be one of ["downloads", "downloads.open"], be one of ["privacy"], be one of ["webNavigation"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["captivePortal"], be one of ["browsingData"], be one of ["devtools"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["normandyAddonStudy"], be one of ["pkcs11"], be one of ["geckoProfiler"], be one of ["sessions"], be one of ["urlbar"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["activityLog"], be one of ["management"], be one of ["networkStatus"], be one of ["proxy"], be one of ["nativeMessaging"], be one of ["telemetry"], be one of ["theme"], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]"

Maybe the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/ can provide some hints, but useless for a blob URL.  😞 

I don't need to declare any permission about blob URL at chrome. 

All right, it looks like <all_urls> is the only way.

**Comment by MihailYotov** [comment]
I had this problem and turned out that someone had put redirection (window.location = '/') not in the promise's resolve function, but immediately after the fetch call, so the application was aborting the call and redirecting to the index.
