### ISSUE TITLE
IE throws errors for 401 status codes

### ISSUE THREAD

**Issue by andykent** [github/fetch#312]
Not sure if this is fixable or expected but I couldn't find it documented anywhere. 

usecase: We are calling an API that can return 401 status codes and so need to ask you to login when this happens.

A minimal reproduction would look something like this...

```javascript
fetch(SOME_URL_THAT_RETURNS_401)
  .then(function(r) { console.log('success', r.status) })
  .catch(function(e) { console.log('error ', e) })
```

In Chrome/FF this logs `success 401` but in IE10 this logs `error TypeError: Network request failed` 

The docs state...

> The Promise returned from fetch() won't reject on HTTP error status even if the response is a HTTP 404 or 500. Instead, it will resolve normally, and it will only reject on network failure, or if anything prevented the request from completing.

So I'm guessing this is a difference of IE treating 401 as an error condition but I feel like it should be normalised in the polyfill or at least documented somewhere if it's not possible to fix.

**Comment by dgraham** [comment]
I just tested receiving a 401 response status in IE 10 and the Promise is resolved correctly.

Is the request listed in the Network tab of IE's web console? That might indicate whether the response was received at all or the connection failed.

**Comment by andykent** [comment]
Yep the response shows up in the network tab. it is a CORS request, if that would make a difference, if I return a 200 response code then the request goes through fine. 

![screen shot 2016-04-11 at 17 40 04](https://cloud.githubusercontent.com/assets/614/14434760/8081553c-000c-11e6-813f-30927d583637.png)

I will try and investigate further.

**Comment by dgraham** [comment]
The CORS tips in https://github.com/github/fetch/issues/181 might help even though they're related to Chrome. The failure might be related to the OPTIONS preflight request.

**Comment by andykent** [comment]
Thanks for the suggestions. I did also wonder if my OPTIONS requests were returning non 2xx error codes but that doesn't seem to be happening. I have researched this further and...

- I agree with your findings, IE10 behaves as expected when not making CORS requests.
- When the request is CORS and the response code is 401 IE10 seems to throw an error, from what I can tell this happens regardless of if the request has a pre-flight check or not. This results in different behaviour in IE vs all other browsers.

I therefore believe this is still a valid issue and should be re-opened.

I have created a small Sinatra based example that reproduces the issue for me... https://gist.github.com/andykent/e37a32ea4c5c9a3b4a6486c2e6d52ca2

When running this server you can hit http://localhost:4567/ and check the console. Here's the output I see...

**Chrome**
![screen shot 2016-04-12 at 10 34 48](https://cloud.githubusercontent.com/assets/614/14455983/7300e66e-009a-11e6-96d3-20e63bf6e784.png)

**IE10 (win8 / browserstack)**
![screen shot 2016-04-12 at 10 36 29](https://cloud.githubusercontent.com/assets/614/14455986/76907222-009a-11e6-96f9-e800cc4ea7b1.png)

**Chrome network requests**
![screen shot 2016-04-12 at 10 38 12](https://cloud.githubusercontent.com/assets/614/14456027/b55877e8-009a-11e6-9793-e71eb593a8b1.png)

Using the same server you can point your browser to http://test.lvh.me:4567/ (thus avoiding the CORS requests) and you will see that IE starts behaving as expected. You can also remove the `Authorization` header that I added to force `OPTIONS` requests but, like I said previously this doesn't seem to make a difference and IE still seems to throw regardless of if it makes the pre-flight request or not.

**Comment by mislav** [comment]
> I therefore believe this is still a valid issue and should be re-opened.

What do you suggest we do in the polyfill? Can we detect the rejection case in IE CORS and transform it into resolving with a 401 response?

**Comment by andykent** [comment]
Very good question! - It needs further investigation. I've not dug into the code too much but it looks like you just reject with a TypeError for all errors currently...

```
xhr.onerror = function() {
  reject(new TypeError('Network request failed'))
}
```

..this makes it pretty much impossible to do anything in end user land (which lead to me originally opening this issue) but it might be that the xhr object has some usable state attached on it. I will have a poke around now.

**Comment by andykent** [comment]
OK, so it seems to be an IE bug....

- https://connect.microsoft.com/IE/feedback/details/785990/ie-10-on-win8-does-not-assign-the-correct-status-to-xmlhttprequest-when-the-result-is-401
- http://stackoverflow.com/questions/16081267/xmlhttprequest-status-0-instead-of-401-in-ie-10

I can't see anything on the response that would allow us to differentiate between this and a 'real' network error though :(

Maybe it's worth documenting this in the readme as it's a deviation from the spec that I don't think can be worked around due to browser limitations.

**Comment by mislav** [comment]
On Tue, Apr 12, 2016 at 1:10 PM, Andy Kent <notifications@github.com> wrote:

> Maybe it's worth documenting this in the readme as it's a deviation from
> the spec that I don't think can be worked around due to browser limitations.
>
Possibly. Is it possible to detect this case from the error message,
though? Or is the error object inaccessible from the `onerror` handler?

**Comment by andykent** [comment]
That's what I was hoping but I can't find a way to access the error message that is displayed in the console...

**onerror handler gets called with a ProgressEvent which looks like this**
```
[object ProgressEvent] {
	lengthComputable : false,
	loaded : 0,
	total : 1.844674407370955e+019,
	initProgressEvent :  function initProgressEvent() {     [native code] } ,
	bubbles : false,
	cancelable : false,
	currentTarget : [object XMLHttpRequest],
	defaultPrevented : false,
	eventPhase : 2,
	isTrusted : true,
	target : [object XMLHttpRequest],
	timeStamp : 1460467894607,
	type : "error",
	cancelBubble : false,
	srcElement : null,
	initEvent :  function initEvent() {     [native code] } ,
	preventDefault :  function preventDefault() {     [native code] } ,
	stopImmediatePropagation :  function stopImmediatePropagation() {     [native code] } ,
	stopPropagation :  function stopPropagation() {     [native code] } ,
	AT_TARGET : 2,
	BUBBLING_PHASE : 3,
	CAPTURING_PHASE : 1
}
```

**by this point the XHR object looks like this**
```
[object XMLHttpRequest] {
	onabort : null,
	onerror : function(e,x) {         console.dir(e)         console.dir(xhr)         console.log(x)         // reject(new TypeError('Network request failed'))       },
	onloadend : null,
	onloadstart : null,
	onprogress : null,
	ontimeout : function() {         reject(new TypeError('Network request failed'))       },
	response : undefined,
	responseBody : null,
	responseType : "blob",
	timeout : 0,
	upload : [object XMLHttpRequestEventTarget],
	onload : function() {         var options = {           status: xhr.status,           statusText: xhr.statusText,           headers: headers(xhr),           url: responseURL()         }         var body = 'response' in xhr ? xhr.response : xhr.responseText       ,
	onreadystatechange : null,
	readyState : 4,
	responseText : ,
	responseXML : ,
	status : 0,
	statusText : "",
	withCredentials : false,
	addEventListener :  function addEventListener() {     [native code] } ,
	dispatchEvent :  function dispatchEvent() {     [native code] } ,
	removeEventListener :  function removeEventListener() {     [native code] } ,
	abort :  function abort() {     [native code] } ,
	getAllResponseHeaders :  function getAllResponseHeaders() {     [native code] } ,
	getResponseHeader :  function getResponseHeader() {     [native code] } ,
	open :  function open() {     [native code] } ,
	send :  function send() {     [native code] } ,
	setRequestHeader :  function setRequestHeader() {     [native code] } ,
	DONE : 4,
	HEADERS_RECEIVED : 2,
	LOADING : 3,
	OPENED : 1,
	UNSENT : 0
}```

So can't see a way to get access to the actual root error. `status == 0` but this also holds true for other network errors so it's not possible to differentiate I don't think.

**Comment by mislav** [comment]
Shame. I guess that if we're going to advise anything, is to point out that you shouldn't use 401 statuses with CORS if you need to support IE10+.

**Comment by andykent** [comment]
Yep, for sure, that's the conclusion I am coming to as well.

I think this bit of the readme is somewhat misleading given the IE situation...

> The Promise returned from fetch() won't reject on HTTP error status even if the response is a HTTP 404 or 500. Instead, it will resolve normally, and it will only reject on network failure, or if anything prevented the request from completing.

maybe that wording should be adjusted? it's sort of a Caveat to the Caveat :)

Anyway, I'm off to cry into my keyboard and I start returning 200 responses with an unauthorised JSON payload. :( 

Thanks a bunch for hearing me out anyway.

**Comment by alshain** [comment]
The same behavior seems to apply for 404 with a no-cors request.
