### ISSUE TITLE
Resolve XHR in onloadend event listener?

### ISSUE THREAD

**Issue by thgaskell** [github/fetch#313]
I have been running into an issue with my tests that are using phantomjs.
The main reason is that phantomjs does not always seem to trigger the `xhr.onload`(e.g. return a 401 status code) but that's a completely separate issue in itself.

However, `xhr.onloadend` listener _does_ trigger. After looking at the source, it doesn't look like this listener is being used. Would there be any implications resolving the promise in the `xhr.onloadend` listener instead of the `xhr.onload` listener?

**Comment by mislav** [comment]
Our CI test suite runs on PhantomJS and passes. If it didn't support the `onload` callback, we would be in big trouble. Do you have any more info to back the claim that PhantomJS XHR implementation is broken? Perhaps you could add a failing test?

**Comment by thgaskell** [comment]
> Do you have any more info to back the claim that PhantomJS XHR implementation is broken? 

I'm using `phantomjs-prebuilt` which is PhatomJS 2.0 (newer version than the one used on this project).
I had to dig into the fetch code and override the event listeners to see what was happening.

The`onload` callback _does_ trigger, but only when statuses are `>= 200` and `< 300`. I'm not sure if that has to do with [the `ok` property on the `Response` object](https://github.com/github/fetch/blob/989a1e8132e9adb4c4e973875ad043ff7219fc5a/fetch.js#L289)?

Gist: https://gist.github.com/thgaskell/f001054ad785f8dea245c0955a3ebf1f

Fetch works perfectly in the browser, I was just curious if there were any implications of resolving/rejecting the promise in the `loadend` since that is _always_ fired after the any of `abort`, `error`, and  `load` events trigger?

**Comment by dgraham** [comment]
I tried to update the dependencies to PhantomJS 2.1.1, to test the 401 response behavior, but got stuck on our web worker Mocha tests failing. So it will take more time to debug those test failures to update. Pull requests that move us to the latest PhantomJS would be welcome!

The `onload` handler has proven reliable in production for a couple years, so we wouldn't switch to `onloadend` just to fix a PhantomJS failure. It's kind of the nature of using PhantomJS: once you manage to get it working, it's difficult to upgrade.

**Comment by mislav** [comment]
> but got stuck on our web worker Mocha tests failing.

Haha I tried too and got stuck on the same thing! 😉 

At least the non-webworker suite passes and that proves that onload is in PhantomJS 2.1. However, not sure if we have any 401 tests.
