### ISSUE TITLE
Simple text file pull not working

### ISSUE THREAD

**Issue by MarkusPint** [github/fetch#315]
```
    return fetch('https://gist.githubusercontent.com/MarkusPint/6a0f2b01ae74b79a379f21117a618909/raw/75ea7fd20a6b65f1b504030eeb1b4e56245cc20c/test.js', {
      mode: 'no-cors'
    }).then(function (res) {
      return res.text();
    }).then((text) => {
      console.log(text.length); // 0
    });
```

**Comment by mislav** [comment]
In order to fetch content from other domains, that domain has to explicitly allow it by setting CORS headers. The `gist.githubusercontent.com` doesn't, as evident if you `curl -i <URL>` it. So, there's no way you can load content from it from your site that I can see.
