### ISSUE TITLE
Global settings

### ISSUE THREAD

**Issue by luckydrq** [github/fetch#319]
In my project i use `cookie` to store session information which means cookies are required to send in each request. But i don't want to add `{credentials: 'same-origin'}` option every time i wrote a fetch api. Is there a way to set up global settings?

**Comment by dgraham** [comment]
There are no global settings. We use a few [wrapper functions](https://gist.github.com/dgraham/92e4c45da3707a3fe789) around the standard fetch API to configure common settings.

**Comment by luckydrq** [comment]
cool, i'd use it, thanks!
