### ISSUE TITLE
JSON parsing fails when strings contain some UTF8 characters

### ISSUE THREAD

**Issue by r88r** [github/fetch#321]
the usual suspects of smart quotes and a few other fancy punctuation marks causes the JSON parse to fail after returning a URL.

Is there a fix or recommended way to pre-process?

**Comment by dgraham** [comment]
Parsing invalid JSON data isn't something we can help with. The fetch polyfill sends the response body through the standard [`JSON.parse`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) function, which throws a `SyntaxError` when given an invalid document.

**Comment by r88r** [comment]
are UTF8 characters invalid JSON then?
I've pushed JSON through validators that comes back as 100% fine, that fetch/response.json() couldn't handle.
