### ISSUE TITLE
Content-type question

### ISSUE THREAD

**Issue by bergr01** [github/fetch#322]
Hi

I need to send a request without specifying a content-type header value (I'm trying to upload a document to Amazon S3 and haven't specified a value for content-type when previously requesting S3 token). However current fetch implementation seems to insist on setting that header - is there some reason for that? Can someone point me at a location in https://fetch.spec.whatwg.org/ or elsewhere that states that Content-Type header is mandatory?

thanks in advance,
Greg

**Comment by dkfiresky** [comment]
@bergr01 

I think it's because of the [following](https://fetch.spec.whatwg.org/#basic-fetch):

> ## 5.2 Basic fetch
> To perform a basic fetch using request, switch on request's current url's scheme, and run the associated steps:
>
> "blob"
> ...
> 5. Append `Content-Type`/blob's type attribute value to response's header list.
> ...

**Comment by bergr01** [comment]
Hi dkfiresky
Thanks for your suggestion - however, what you posted seems to talk about a set of steps in a response to GET request... in my case I'm making a PUT request myself.

**Comment by dgraham** [comment]
You might try setting Content-Type to `null` or the empty string.

```js
fetch('/url', {
  headers: {'Content-Type': null}
})

// or

fetch('/url', {
  headers: {'Content-Type': ''}
})
```

**Comment by bergr01** [comment]
Looks like this issue is partially back for me - as even with type-less blob creation, when I upload a document using webkit/Safari, for some reason empty Content-Type header value gets sent along... this doesn't seem to happen for me in any other browser (e.g. Chrome, IE 11, Firefox)
