### ISSUE TITLE
Empty POST body

### ISSUE THREAD

**Issue by AmenRa666** [github/fetch#323]
Hello i'm using Fetch on Node with React and Browserify, i trigger this code from a form submit:
```
event.preventDefault();

var form = new FormData();
form.append('a', 1);

fetch('http://localhost:8080/login', {
      method: 'POST',
      body: form
})
```
Can't figure out why the request sent to the server has empty body, no matter what i put in (i also tried strings as body).

Any ideas?

**Comment by mislav** [comment]
Where is this code executing? On the server (with node.js) or in a browser? If in a browser, which one? Is the HTTP request to another host name or port number? If so, it's subject to CORS policies.

**Comment by AmenRa666** [comment]
Hi, the code is executing in the browser (Chrome). The  request is sent to the server that host the app, same host name, same port number.

**Comment by mislav** [comment]
Your usage of fetch looks alright. How are you verifying that the HTTP request doesn't have a POST body? Did you try right-clicking in Developer console and choose “Log XMLHttpRequest”?

**Comment by dgraham** [comment]
Closing since this is related to Chrome, which does not use this polyfill, but feel free to continue discussing the issue.

**Comment by samcorcos** [comment]
Huh, I'm having the same issue. The request appears to be successful, but the body is empty.

I am using Chrome and my request looks like this:

```js
    const data = {
      email: "sam@corcos.io"
    }

    fetch('http://localhost:3030/api/purchase', {
      method: "POST",
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    }).then((res) => {
      console.log("this is res", res)
    }).catch((err) => {
      console.log(err)
    })
```

The XMLHttpRequest appears to have been successful:

```
index.js:63 Fetch complete: POST "http://localhost:3030/api/purchase".
```

I have a simple logger that logs the request and `response.body`:

```
{}
POST to /api/purchase
took 1 ms
```

I've tried it with `import 'whatwg-fetch'` and without.

**Comment by madsilver** [comment]
I had the same problem. I solved using:
```
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
```

**Comment by m-adil** [comment]
every body is suggesting the same solution as of @madsilver but unfortunately this isn't working at my end. 
Any success by using `fetch`?

**Comment by tanmqn** [comment]
@m-adil You might forgot to add contenttype in the request

**Comment by dineshswamy** [comment]
has anyone had success resolving this issue  ?

**Comment by Piepongwong** [comment]
I had the same issue and I solved it. **First** you have to fix the cross browser issue by doing something like this on your api server (I'm using node with Express): ```
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});
```
**Second**, you have to make sure you are able to parse json by doing something like this on your api server:
`app.use(require("body-parser").json());
`
Note that you rarely send x-www-form-urlencoded data with react, because the recommended way of posting form data it is not by using the form directly, but by setting up a form handler. That is why it doesn't work with via react, but it does work with Postman, Curl or some other test-tool.

**Comment by superpuper** [comment]
Thanks guys, saved me a day. Essentially, what did work out for me:
**Client:**
`fetch(...
  headers: { "Content-Type": "application/json" }`
**Server:**
`app.use(require("body-parser").json())`

**Comment by milewski** [comment]
it might be not that obvious but make sure you are doing `app.use(bodyParser.json());` before registering your routes!

**Comment by jiminshi** [comment]
Adding header with content-type key solved it! Thanks!

**Comment by jitendras007** [comment]
Hi,

I am facing the same issue since a week. I have tried lots of things to resolve it :(
Since its as it is, Can anyone help me out for the issue why I am not able to call my API with fetch but able to call it using postman?

Thanks

**Comment by thesilentpsycho** [comment]
Thanks Guys. I had the same problem.  The solution from @Piepongwong solved my problem.
I had the same problem where the response.body was an empty object.
The console showed the following error on posting something from React to my express server:
![image](https://user-images.githubusercontent.com/13063226/44621847-3244d780-a8cb-11e8-863c-a9f070a6d743.png)

I have the following on my server.js file:
`app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
  });
var bodyParser = require('body-parser')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))`

Client side looks like below:
`var resp = await fetch('http://localhost:5000/order', {
                          method: "POST",
                          // mode: "no-cors",
                          headers: {
                            'Accept': 'application/json',
                            'Content-Type': 'application/json'
                          },
                          body: JSON.stringify(order)
                        })
                        .then(function(response) {
                          return response.json();
                        });`

**Comment by MtzwOsk** [comment]
'Content-Type': 'application/x-www-form-urlencoded',
