### ISSUE TITLE
Can we have a new release?

### ISSUE THREAD

**Issue by danez** [github/fetch#324]
I was just using `Headers.entries()` in my code and had to find out the latest release of this polyfill does not support it. But it is already in master.

Last release was also in January and I would really love to see a new release.

Or is there anything blocking?

**Comment by dgraham** [comment]
Version 1.0.0 is now available.

https://github.com/github/fetch/releases/tag/v1.0.0
https://www.npmjs.com/package/whatwg-fetch

**Comment by jonathanong** [comment]
is there a changelog of breaking changes somewhere?

**Comment by dgraham** [comment]
The only new requirement in this version is IE 10 and higher. IE 9 is supported by the previous 0.11 version.
