### ISSUE TITLE
get请求参数

### ISSUE THREAD

**Issue by Yhaojing** [github/fetch#325]
get请求参数不拼接在URL中要怎么做，有类似与post请求放在body中的嘛

**Comment by mislav** [comment]
Sorry! We don't speak Chinese. We can't help you.

**Comment by Yhaojing** [comment]
Sorry ,how to do when get request parameters do not stitching in the URL

**Comment by mislav** [comment]
I still don't understand the question, sorry. It sounds like you might be trying to append GET request parameters onto a URL? You can do that like so:

```js
fetch('http://example.com/foo?name=' + encodeURIComponent(name))

// or, with jQuery:
var getParams = { "name": name }
fetch('http://example.com/foo?' + $.param(getParams)
```

**Comment by Yhaojing** [comment]
thank you

**Comment by Yhaojing** [comment]
I set defaultFileList like that           ```
<FormItem
                    label="App Banner 图片"
                    labelCol={{ span: 6 }}
                    wrapperCol={{ span: 16 }}
                    help="App Banner 图片600*600">
                    <Upload {...UPLOAD_CONFIG} listType="picture"
                        {...appBannerImgProps} defaultFileList={[{
            uid: -1,
            name: project.appBannerImg,
            status: 'done',
            url: project.appBannerImg
        }]}> 
```
but when i submit appBannerImg is undefined why????

**Comment by yoyo837** [comment]
@Yhaojing 你压根不应该往get请求的body上放数据去钻牛角尖，理解http就清楚了，你的疑问与本库无关。
