### ISSUE TITLE
Add reference to Fetch API wrapper

### ISSUE THREAD

**Issue by niftylettuce** [github/fetch#330]
I'm not sure if you would be willing to - but I wrote a really clean API wrapper (still needs some work and features), but if you're interested in adding it as a reference in the Readme here - I think that would help a lot of people with common problems!  Using `fetch()` by itself can be annoying!

<https://github.com/glazedio/frisbee>

**Comment by mislav** [comment]
Looks nice, but this belongs to userland, and I'm sure people will discover it if they search for it. We can't really link to all fetch-related projects from our simple polyfill. I hope you understand!
