### ISSUE TITLE
Error: Promise undefined ? 

### ISSUE THREAD

**Issue by elinadenfina** [github/fetch#334]
I get a "'Promise' is undefined"-error on Internet Explorer 11. I imported whatwg-fetch but it seems like the polyfill wont be found. Or is there something I'm missing? 

```import 'whatwg-fetch'; ```

```
return fetch(url)
    .then(function (response) {
      return response.json();
    }).then(function (json) {
      return json;
    }).catch(function (ex) {
      console.log('failed:' + ex);
    }); 
```

**Comment by LPGhatguy** [comment]
Make sure you have a `Promise` polyfill, as IE 11 [doesn't support Promises out of the box](http://caniuse.com/#feat=promises). I'd recommend `es6-promise`.

**Comment by ajfarkas** [comment]
This seems like a good thing to include in documentation.

This library is fantastic, but I long for better documentation.

**Comment by LPGhatguy** [comment]
The library states:

```
You'll also need a Promise polyfill for older browsers.

$ bower install es6-promise
```

Additionally, this is a current web standard. Documentation is available in other places too; this is just a polyfill.
