### ISSUE TITLE
Disable Sauce labs in CI

### ISSUE THREAD

**Issue by mislav** [github/fetch#336]
Running our test suite with Sauce labs in CI seems to fail almost more often than not for reasons that we are not responsible for. Take [this run, for example](https://travis-ci.org/github/fetch/builds/133434104), which took more than 2 hours before it timed out.

It's still very important to have real browser tests other than PhantomJS, but with Sauce labs being as unreliable as it is, I think it's hurting us with intermittent failures on people's PRs and our master branch.

Alternatively, we can try looking into our Sauce labs integration (which is [pretty ad-hoc](https://github.com/github/fetch/pull/220)) and figure out if we're doing anything wrong and could be improve parts of it with strict timeout settings and reconnect attempts.

/cc @dgraham

**Comment by dgraham** [comment]
We can disable them if they aren't useful. I rely on `make test` to validate changes.

**Comment by mislav** [comment]
Done in 133f690710b04f6b899357aa6767a94a1afac3a7.
