### ISSUE TITLE
fetch is taking extra long time on waiting(TTFB) in Chrome

### ISSUE THREAD

**Issue by ripitrust** [github/fetch#338]
Simple GET request 
 ` fetch('/test').then(res => {console.log(res.text)}); `

takes very long on waiting(TTFB) in the first connection,  but will return normal in the next.
![screen shot 2016-06-01 at 11 11 02 am](https://cloud.githubusercontent.com/assets/3109078/15697442/c6024082-27ec-11e6-87c6-0a33cee2a38a.png)

![screen shot 2016-06-01 at 11 10 40 am](https://cloud.githubusercontent.com/assets/3109078/15697452/dcb69f94-27ec-11e6-86b6-fe51133a9161.png)

This only happens in Chrome, not in Safari or other HTTP client.  If I use jQuery ajax, this problem also will not appear.

Any potential problems related to this?

**Comment by dgraham** [comment]
This isn't something we can help with because Chrome uses its native `fetch` implementation rather than this polyfill code. The polyfill is active in Safari and uses `XMLHttpRequest` like jQuery's `$.ajax` does.

**Comment by ripitrust** [comment]
@dgraham  Thanks for your reply

I am using Python Flask as the backend
I have found out a possible reason [http://stackoverflow.com/questions/23639355/extremely-long-wait-time-when-loading-rest-resource-from-angularjs](here), so I might just put it here in case anyone else encountered this issue.
