### ISSUE TITLE
Chrome status codes (help request)

### ISSUE THREAD

**Issue by dendril** [github/fetch#339]
Hey everyone! I've been dealing with the following problem, and any help is welcome! 

I have a service which uses ETag to prevent the download of the same content multiple times. First time you hit the service, you get a 200 code, next calls answer 304.

Using the following snippet:
```js
fetch('/my-service').then(resp => console.log(resp.status));
```

I always get a 200 code instead of been able to read the 304 to make a decision.

Recommendations? Suggestions? I read the documentation but could not find anything useful 😢 

Thanks in advance!

**Comment by dgraham** [comment]
See https://github.com/github/fetch/issues/241.
