### ISSUE TITLE
PUT and PATCH requests fail in Microsoft Edge (with native Fetch support)

### ISSUE THREAD

**Issue by javan** [github/fetch#340]
This isn't an issue with your polyfill per se so feel free to close it any time. We recently noticed a number of exceptions in our app stemming from Fetch-intiated `PUT` requests in MS Edge that lacked a request body.

I did some digging and found that Edge's `PUT` requests had `Content-Length: 0` so the `JSON.stringify`'d data we send as the body wasn't making it to the server. I also found that `PATCH` requests fail entirely and are never transmitted.

These requests succeed in every browser I could find that has native Fetch support. They also succeed in browsers that don't when using this polyfill.

I put together small demo Rack app here: https://github.com/javan/fetch-put-patch-demo

I'm curious if you think MS Edge is doing it right and most closely following the spec. And if not, should this polyfill step in and smooth over the inconsistency?

Thanks for your time! ❤️

**Comment by dgraham** [comment]
I think this is probably a bug in the beta build of Edge. I [reported this](https://twitter.com/davidgraham/status/738473923386302464) via Twitter based on [this suggestion](https://twitter.com/gregwhitworth/status/738212018113515520) from Microsoft.

@javan This might be the best bug report I've ever received. Thank you so much for taking the time to create a test repository demonstrating the problem. ❤️

**Comment by javan** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7773267/ 🎉

**Comment by dgraham** [comment]
Nice, I'll close this out in favor of that Edge tracking bug.
