### ISSUE TITLE
ArrayBuffer as body must not be passed directly to XHR

### ISSUE THREAD

**Issue by datenreisender** [github/fetch#343]
When `fetch` is invoked with an `ArrayBuffer` as body, that `ArrayBuffer` is passed directly to the `XMLHttpRequest`, but invoking xhr with an `ArrayBuffer` is deprecated. Thus this causes a warning in some browsers, e.g. Safari. It should be wrapped in an `ArrayBufferView`: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send

When executing this fiddle with Safari, the warning is shown in the console: 
https://jsfiddle.net/gkp1swke/4/

**Comment by datenreisender** [comment]
I tried passing an `ArrayBufferView` directly as a body to `fetch`, but this also yields an error, as explained in #344.

**Comment by inithink** [comment]
+1
