### ISSUE TITLE
Any BufferSource should be accepted as an body for a POST

### ISSUE THREAD

**Issue by datenreisender** [github/fetch#344]
According to the spec any BufferSource should be accepted as body for a POST, but this polyfill only allows `ArrayBuffer` not an `ArrayBufferView`. 

Running https://jsfiddle.net/fn2j46tu/1/ on Safari shows in the console, that either using a `DataView` or an `TypedArray` yields a `unsupported BodyInit type` error.

**Comment by mislav** [comment]
Thanks for catching this and providing detail! It seems that there are 2 separate but related problems that you've correctly opened 2 issues for. Let's see if we can tackle them. Would you be willing to submit patches that first address this problem, and then the one described in the other issue?

**Comment by datenreisender** [comment]
I‘m currently not able to submit a tested PR, but my shot would be to utilise [`ArrayBuffer.isView()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/isView) by changing https://github.com/github/fetch/blob/65b611e/fetch.js#L180 to something like 

```js 
  } else if (support.arrayBuffer && (ArrayBuffer.prototype.isPrototypeOf(body) || ArrayBuffer.isView(body))) {
```
