### ISSUE TITLE
404 when trying to replicate jQuery ajax POST request

### ISSUE THREAD

**Issue by superfunkminister** [github/fetch#345]
Hello! I'm trying to send some basic form data via a POST request.

The following works for me using jQuery's AJAX:
```` js
$.ajax({
    type: 'POST',
    url: 'api/form',
    data: data,
    dataType: 'json'
});
````
However the following does not work for me using fetch:
```` js
fetch('api/form', {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    },
    body: data
});
````

I have tried sending it both as JSON and as a serialized string, i.e. `name=Brian&email=brian%40butterfield.com&message=Test+message`, both give me the message `contactForm.js:83 POST http://localhost:3000/api/form 404 (Not Found)`.

Any idea why this wouldn't be working?

I've attached screenshots of my network panel for both below:

![network-stuff](https://cloud.githubusercontent.com/assets/1285419/15915998/18a36aba-2de6-11e6-817b-649240a09896.png)

**Comment by superfunkminister** [comment]
Looks like I specifically needed the header `'X-Requested-With': 'XMLHttpRequest'`, seems to be working now!

**Comment by yuanhepeng** [comment]
查看下url
