### ISSUE TITLE
how to get the message from server

### ISSUE THREAD

**Issue by brealisty** [github/fetch#347]
as we know， if we use ajax, we can get the message from server via the jqXHR.responseText. when we use fetch how do we do? for example:
server:
`return res.status(500).send('Error occurred:database has existed.');`
ajax:
`error: function (jqXHR) {
                        $container.html(jqXHR.responseText);`

**Comment by mislav** [comment]
Please refer to [Usage examples in the README](https://github.com/github/fetch#usage) to see how to extract text from a response.
