### ISSUE TITLE
how to fetch with cookie in server side?

### ISSUE THREAD

**Issue by L-x-C** [github/fetch#348]
Isomorphic react
I need to fetch data in server side before render, and the request needs contain login information within cookie.
On client side, i add `credentials: 'include'` it's not a problem, but in server side, the request cannot contains cookie?
How to solve that?

**Comment by mislav** [comment]
This library doesn't support being executed on the server. You will have to use another approach to make server-side requests. Sending a cookie from server-side requests is as easy as setting any custom HTTP header, and you shouldn't have a problem figuring it out.
