### ISSUE TITLE
Cookie not set in Request Headers, even with 'same-origin' credentials.

### ISSUE THREAD

**Issue by chalisegrogan** [github/fetch#349]
Making requests to a Django API requires setting a `csrftoken` cookie. I am having trouble setting this and sending the `Cookie` header in a `fetch` request. I have looked at: 
* https://github.com/github/fetch/issues/163#issuecomment-112180606
* https://github.com/github/fetch/issues/142
* https://github.com/github/fetch/pull/56#issuecomment-69113848
* http://stackoverflow.com/a/29664267/651952

I've made sure that I'm setting the `credentials` to `'same-origin'`, as noted many times in the above resources. However, the `Cookie` header is still missing from the request. Headers seem to be properly changed for every other attribute but `Cookie`. I feel like I'm missing something obvious, but cannot figure out what it is. Below is the example js I'm using.
```js
fetch('/api/v2/user/me', {
  method: "GET",
  headers: {
    'Accept': 'application/json', // This is set on request
    'Content-Type': 'application/json', // This is set on request
    'X-CSRF-Token': 'abcdefghijklmnop', // This is set on request
    'Cache': 'no-cache', // This is set on request
    credentials: 'same-origin', // This is set on request
    'Cookie': 'csrftoken=abcdefghijklmnop' // This is missing from request
  }
})
.then(response => {
  if (response.status >= 200 && response.status < 300) {
    return response.json();
  } else {
    throw error;
  }
})
.catch(error => { console.log('request failed', error); });
```
You will note the header missing from the request:
![screen shot 2016-06-13 at 11 49 31 am](https://cloud.githubusercontent.com/assets/1843056/16019376/7cb08bbc-315d-11e6-865e-06de4f6389fc.png)
I tried changing the cookie key to something other than `csrftoken`; that did not work either. Thoughts on this?

**Comment by mislav** [comment]
You [can't manipulate cookies manually](https://github.com/github/fetch/issues/163#issuecomment-112178247) in either XMLHttpRequest nor `fetch()`. The browser handles cookies automatically. If you want a cookie to be sent, you have to first set it by writing to `document.cookie` prior to making a requests.

Can't the backend read the CSRF token from the `x-csrf-token` header, though?

**Comment by chalisegrogan** [comment]
@mislav Even with `document.cookie` set prior, the cookies are missing from the request. I assumed (incorrectly) that because they weren't being passed along, I maybe needed to add the cookie manually. So, for example:
```js
document.cookie = 'test=abcd';
fetch('/api/v2/user/me', {
  method: "GET",
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Cache': 'no-cache',
    credentials: 'same-origin'
  }
})
```
Still results in:
![screen shot 2016-06-13 at 12 15 54 pm](https://cloud.githubusercontent.com/assets/1843056/16020065/1be8f16c-3161-11e6-85fe-2a0dac708653.png)

Note that any other requests on the page _do_ pass along cookies:
![screen shot 2016-06-13 at 12 20 02 pm](https://cloud.githubusercontent.com/assets/1843056/16020159/72ec4400-3161-11e6-90ab-18ce215e8435.png)
---

> Can't the backend read the CSRF token from the x-csrf-token header, though?

I could do this, but there's still a reasonable question as to why the cookies are missing, I think. Why don't _any_ of the cookies on `document.cookie` get sent along with the request whilst using `fetch`? Is there a config value I'm supposed to be setting, and not?

**Comment by chalisegrogan** [comment]
@mislav I've figured it out. The `credentials` property is not supposed to be defined in the `headers` object. This works:

```js
fetch('/api/v2/user/me', {
  method: "GET",
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Cache': 'no-cache'
  },
  credentials: 'include'
})
```

...duh. For others.

**Comment by mislav** [comment]
Yikes. Sorry I didn't spot that. Thanks for the update

**Comment by tamitutor** [comment]
FWIW: 

If you set `credentials: 'same-origin'` it will only send the cookies from the same domain--which is handy if 3rd party client-side libraries are adding lots of cookies and you don't want to muddle up your server-side request with lots of useless cookie junk.

Example call:

```javascript
fetch('/api/v2/user/me', {
    method: "GET",
    headers: {
        'Accept':  'application/json',
       'Content-Type': 'application/json',
       'Cache': 'no-cache'
    },
    credentials: 'same-origin'
})
```

**Comment by constantinosergiou** [comment]
hello @chalisegrogan ,
i did the same as you did here is my code
``` const base = (method, url, data = {}) => {
    return fetch(`${jwtConfig.fetchUrl}${url}`, {
      method,
      headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Cache': 'no-cache',
     Authorization: localStorage.getItem("id_token") || undefined,
  },
  credentials: 'include',
      body: JSON.stringify(data),

    })
    .then(response => response.json())
    .then(res => res)
    .catch(error => ({ error: "Server Error" }));
};
```
but i dont get any cookies
here is my screenshot
![2018-07-07](https://user-images.githubusercontent.com/23071921/42411604-78490eb2-8207-11e8-8f24-7aa2887443ae.png)

i use react for front and laravel for backend

**Comment by nick-baliesnyi** [comment]
@constantinosergiou ++ having the same problem, also using React. Help, anyone? :)

**Comment by nick-baliesnyi** [comment]
fetch became too much of a pain for me, so I went for axios library.. after I read this article.

https://medium.com/@shahata/why-i-wont-be-using-fetch-api-in-my-apps-6900e6c6fe78?source=linkShare-a084d3e16929-1531565170
