### ISSUE TITLE
Nexus 7 Dolphin 11 "Object #<Response> has no method 'blob'"

### ISSUE THREAD

**Issue by tobireif** [github/fetch#355]
On Nexus 7 in Dolphin 11 I'm getting "Object #<Response> has no method 'blob'".

**Comment by tobireif** [comment]
Also in Android Browser 4.1.

**Comment by dgraham** [comment]
The [Response.blob](https://github.com/github/fetch/blob/4bde61788365cfd3d6155eee8aed3c7673d299d5/fetch.js#L199) function is available only when [Blob is supported](https://github.com/github/fetch/blob/4bde61788365cfd3d6155eee8aed3c7673d299d5/fetch.js#L11) by the browser. The Blob constructor was first [available on Android](http://caniuse.com/#feat=blobbuilder) with Chrome 50.

**Comment by tobireif** [comment]
Thanks!

For future visitors, here's the feature-detection code you linked:
```
'FileReader' in self && 'Blob' in self && (function() {
  try {
    new Blob()
    return true
  } catch(e) {
    return false
  }
})()
```

**Comment by jimmywarting** [comment]
I think it's insufficient to only include the blob method when it's possible to use it. Leaving the user with question to why it doesn't exist.

`res.blob()` returns a promise and I think we could use it and reject if it fails to construct a blob. With a message like 

```javascript
reject(new Error("Failed to construct a blob, Include blob a polyfill, https://github.com/eligrey/Blob.js"))
```

Leaving us with fewer browser specific hacks

**Comment by mislav** [comment]
@jimmywarting That's an excellent idea. We'd love a PR that does that.
