### ISSUE TITLE
PATCH URL parameter not working?

### ISSUE THREAD

**Issue by lukasoppermann** [github/fetch#359]
Hey, when I run the following:

```javascript
fetch('http://test.de/pages/12345', {
    method: "PATCH",
    body: {
        position: draggedItem.position
    }
}).then(function(response) {
    return response.blob();
});
```

The PATCH request, that is triggered is to `http://test.de`. However, if I change the method to `PUT`, it sends it to `http://test.de/pages/12345`.

I hope this is not intended behaviour. However, it seems patch-requests are impossible? Or am I missing something here?

**Comment by silvenon** [comment]
@lukasoppermann have you found the solution for your problem?

**Comment by lukasoppermann** [comment]
To be honest I don't remember. I probably did something wrong and it worked afterwards.
