### ISSUE TITLE
Losing headers in AOSP

### ISSUE THREAD

**Issue by fedgrant** [github/fetch#360]
Losing access to some of the header tags on the AOSP browser. 

In chrome and FF i am getting
```
"access-token":["xxx"],
"client":["xxx"],
"expiry":[xxx"],
"uid":["xaz@xaz.com"],
"token-type":["Bearer"],
"content-type":["application/json; charset=utf-8"],
"cache-control":["max-age=0, private, must-revalidate"]
```
 but in AOSP I am getting
```
"content-type":["application/json; charset=utf-8"],
"cache-control":["max-age=0, private, must-revalidate"]
```
My hunch is that it might be based on how the browser processes custom header tags or that the request is not fully completed when the xhr.onload fires. Any advice in debugging the script would be appreciated. Thanks.

**Comment by mislav** [comment]
Thanks for letting us know. It doesn't look like we can do anything about this issue. We piggyback off XMLHttpRequest, so we are at the mercy of its own HTTP header processing. We can't make headers stripped by the browser re-appear.

If you can investigate this XMLHttpRequest issue by searching the web and find some easy workarounds that we could employ from the usage side of XHR, then please update here. Otherwise, we should close this as #wontfix. Thanks!

**Comment by dgraham** [comment]
One way to debug is to use `XMLHttpRequest` directly and investigate the response headers. It's likely that the headers are missing there as well, and it would isolate the problem to either this [parsing code](https://github.com/github/fetch/blob/4bde61788365cfd3d6155eee8aed3c7673d299d5/fetch.js#L313-L323) or the browser itself.

**Comment by egadstar** [comment]
I've been seeing this inside of electron; looking at the the console, I see all the headers being returned from the API call; however, the response object in the promise only contains the 'content-type' and 'cache-control' headers.

here's the headers returned from the response in the Network tab

<img width="366" alt="screen shot 2016-07-18 at 6 22 30 pm" src="https://cloud.githubusercontent.com/assets/1434274/16932534/db7e0fa2-4d14-11e6-8246-ed59f4d4148a.png">

here's the output from the promise

<img width="725" alt="screen shot 2016-07-18 at 6 34 35 pm" src="https://cloud.githubusercontent.com/assets/1434274/16932715/2e1cfbd2-4d16-11e6-97b4-fbdcb4d166ec.png">

**Comment by hchood** [comment]
I'm seeing the same in Chrome:

![screen shot 2017-02-03 at 8 20 16 am](https://cloud.githubusercontent.com/assets/4464987/22592856/ae075a7a-e9e9-11e6-877d-e5ea5a27c086.png)

**Comment by iiwo** [comment]
I think you have to have [Access-Control-Expose-Headers](https://fetch.spec.whatwg.org/#http-access-control-expose-headers) response header set to access those header values
