### ISSUE TITLE
XML ?

### ISSUE THREAD

**Issue by okbel** [github/fetch#361]
I don't know if I should put this here or in StackOverflow. But, since fetch is the new XMLHttpRequest.

 Does anyone know if I could retrive an XML? If so, how can I achieve this?

Thank you!

**Comment by hollowdoor** [comment]
Looking around I don't see any methods to get XML. In this library, or the standards spec. I wonder if an XML resolver will be added to the spec. In the mean time there is DOMParser.

**Comment by mislav** [comment]
Yes, XML is not specified by the fetch spec, meaning that you simply need to use methods to get response string and parse that yourself.
