### ISSUE TITLE
HTTP Headers are converted to low case

### ISSUE THREAD

**Issue by MarcoScabbiolo** [github/fetch#362]
I'm setting the Autorization header with the first letter set to 'A'

`headers: {
	Authorization: authHTTPHeader(username, password)
}`

But when the request flies, the first letter of the key is not 'A' but 'a', this made my server unable to find the header. The workaround was easy for me, but it would be nice to send the headers as they were declared if it's possible.

**Comment by steezeburger** [comment]
Experiencing the same issue.

**Comment by dgraham** [comment]
See #249.
