### ISSUE TITLE
data parse problem on 'xx.json()'

### ISSUE THREAD

**Issue by iniestano8** [github/fetch#368]
i fetch some data(json) from my api, and it costs about 1.5 seconds on the step xx.json(), i found that the responseType of xhr( = New XMLHttpRequest()) exists and values a empty string, so it returns me a blob responseType, then i call xx.json(), it does take too long ...
![image](https://cloud.githubusercontent.com/assets/5787530/16985586/0ba804b2-4eb4-11e6-9c8c-26f310398677.png)
maybe the method below works well..sorry for bad english
`if ('responseType' in xhr && xhr.responseType && support.blob) {
    xhr.responseType = 'blob'
  }`

**Comment by mislav** [comment]
Sorry; I don't understand how does your proposed fix (checking `xhr.responseType`) help making `json()` function faster? How large is the JSON payload that you're parsing and that takes 1.5 seconds?
