### ISSUE TITLE
Could the catch function pass a response object instead of just an error?

### ISSUE THREAD

**Issue by JosephShering** [github/fetch#372]
It would help handling non 200 status codes.

**Comment by mislav** [comment]
A `fetch()` promise is not rejected on non-200 responses. Instead, it resolves normally, and [you're responsible for detecting "successful" HTTP response](https://github.com/github/fetch#handling-http-error-statuses). The `catch()` callback will only be called for rejected Promise, which will happen in the event of network or similar error that made making the request impossible.
