### ISSUE TITLE
response.json generates a SyntaxError

### ISSUE THREAD

**Issue by davidtzoor** [github/fetch#373]
When handling errors with the following code:
```javascript
return fetch(route, generateFetchOptions(method, body))
    .then(response =>  {
        if (!response.ok) {
            return Promise.reject(response.json());
        }
        return response.json();
    });
```
I get a `SyntaxError`:
```Uncaught (in promise) SyntaxError: Unexpected token U in JSON at position 0```

This is what the Response object looks like:
![image](https://cloud.githubusercontent.com/assets/8441214/17544573/d4ff07d4-5ee0-11e6-9388-d872f359cae4.png)

Am I doing something wrong?

Another issue with error handling, is that they are always printed to the console, even though I have a function to handle it.

**Comment by mislav** [comment]
This looks like a JSON parsing error. Did the server return valid JSON as the response body for the HTTP 401?

**Comment by dgraham** [comment]
It's possible, but unlikely, that the server is going to return a `Content-Type: application/json` response body with all error statuses (404, 401, 406, 500, etc).

If your server does send JSON with a particular error code, a better way to handle it in the client is with an explicit status test.

```js
if (response.ok) {
  // A 200-299 response status
} else if (response.status === 401) {
  response.json().then(…)
} else {
  // No JSON expected or available for these error codes.
}
```

**Comment by davidtzoor** [comment]
Thank you @dgraham! Can you please refer to the other matter, where error responses always show in the console?

**Comment by dgraham** [comment]
I think that's your browser making sure you don't miss any errors in the Promise handling chain during development.

Errors that are not handled by a `catch` method are definitely going to appear in the console. I'm not sure what the behavior is for errors already handled during a `catch`.
