### ISSUE TITLE
Implement default values and validation for status codes

### ISSUE THREAD

**Issue by wheresrhys** [github/fetch#376]
To comply with https://fetch.spec.whatwg.org/#dom-response, and equivalent to these 2 PRs on node-fetch 
https://github.com/bitinn/node-fetch/pull/135
https://github.com/bitinn/node-fetch/pull/132

I'm happy to submit a PR if it's approved in principle

**Comment by mislav** [comment]
I'm fine of setting default HTTP status to 200 and text to "OK". This will be easy to implement. However, I don't think it's worth our time to implement the validation that the status code must be between 200–599. Our library should stay simple and doesn't need to conform to 100% of the spec— we aim to implement just the parts that will actually be useful to people in development.
