### ISSUE TITLE
Vulnerability in shell-quote 1.4.3 of github/fetch

### ISSUE THREAD

**Issue by briandoll** [github/fetch#377]
The **shell-quote 1.4.3** library, a transitive dependency in the **github/fetch** repository, is subject to vulnerability [SID-2503: Command Injection through Improperly Escaped Shell Characters](https://srcclr.com/registry/vulnerabilities/2503).

A transitive dependency is a library that is included in your project indirectly through another dependency. A vulnerability in a transitive dependency can be fixed by adding a new direct dependency of the library in your project.

This issue was fixed in version 1.6.1. That version is currently considered safe, so we suggest that you add version 1.6.1.

Applying the fix may break your project, so we recommend that you always build and test your project to verify that the fix has been successful.

##### package.json
```js
"dependencies": {
  ...,
  "shell-quote": "1.6.1",
  ...,
}
```

For more information on this vulnerability, please visit the [SourceClear Registry](https://srcclr.com/registry/vulnerabilities/2503).

**Comment by mislav** [comment]
Thanks @briandoll, but I'm going to close this out as safe, since `fetch` doesn't have any runtime dependencies, and the vulnerability that you're talking about must be coming from `devDependencies`, which are only used in local testing and in CI.

Thanks for letting us know!

**Comment by briandoll** [comment]
Ah, I see that now. 👍
