### ISSUE TITLE
response.json()

### ISSUE THREAD

**Issue by augustnmonteiro** [github/fetch#378]
I think that response.json() should works with a empty string returning a null

**Comment by mislav** [comment]
No, sorry! Blank response is not valid JSON. This is how native implementation in Chrome also handles it: by raising a SyntaxError. And the spec says:

> JSON
> Return the result of invoking the initial value of the `parse` property of the JSON object with the result of running utf-8 decode on bytes as argument. Rethrow any exceptions.

Basically, it says that the implementation should invoke `JSON.parse(response_body)` and re-raise any exceptions. That's what we do right now.
