### ISSUE TITLE
Please use window instead of this

### ISSUE THREAD

**Issue by dignifiedquire** [github/fetch#382]
Currently the `function` wrapper checks for `self` and `this` to get the global namespace. When this module is bundled though and is executed inside a strict mode function both `self` and `this` evaluate to `undefined`.

Please consider switching to check for `window` instead.

**Comment by dgraham** [comment]
History related to `window`, `self`, and `this` can be found with [this search](https://github.com/github/fetch/pulls?utf8=✓&q=is%3Apr%20self).
