### ISSUE TITLE
JSON parsing blocks the eventloop

### ISSUE THREAD

**Issue by Smert** [github/fetch#387]
response.json() must be async but **fetch.js** contains
```javascript
    this.json = function() {
      return this.text().then(JSON.parse)
    }
```

**JSON.parse** blocks the eventloop

https://developer.mozilla.org/en-US/docs/Web/API/Body/json

**Comment by dgraham** [comment]
The parse function is called asynchronously when the response body text promise is resolved.

**Comment by Smert** [comment]
But parsing of a large JSON blocking eventloop if used **JSON.parse**.
**Body.json()** should not block
