### ISSUE TITLE
Fetch self signed certificate

### ISSUE THREAD

**Issue by Jacky-cheng** [github/fetch#389]
How to Ignore invalid SSL Certificate(self signed certificate)?Can someone answer,tanks!

**Comment by dgraham** [comment]
This will depend on your browser configuration settings. There isn't a way to control encryption from the Fetch API.

**Comment by Jacky-cheng** [comment]
I am use it in react native for android app.So,How to config browser?thanks

**Comment by wraix** [comment]
+1
