### ISSUE TITLE
Empty GET response.text()

### ISSUE THREAD

**Issue by adamyonk** [github/fetch#392]
<img width="1680" alt="screen shot 2016-09-10 at 22 22 16" src="https://cloud.githubusercontent.com/assets/33258/18414968/814b5bc8-77a5-11e6-9bca-22aa6ec97609.png">
<img width="1680" alt="screen shot 2016-09-10 at 22 22 37" src="https://cloud.githubusercontent.com/assets/33258/18414967/8149fc10-77a5-11e6-8a13-d0f54d3a8945.png">

I'm really confused by what's happening here. Chrome net inspector shows a body coming back, but `text()` returns nothing?

**Comment by adamyonk** [comment]
I don't know what was going on with Chrome there, but I tried the same thing in Safari and it works. :shrug:

**Comment by hikigaya58** [comment]
i hope it's not too late, this question annoy me  whole today, and i find answer here:https://stackoverflow.com/questions/36840396/fetch-gives-an-empty-response-body.
