### ISSUE TITLE
Unable to save cookies in browser

### ISSUE THREAD

**Issue by wlingke** [github/fetch#394]
In both Chrome 52 & Firefox 43, I've been unable to set a cookie from my server by using `fetch` to send a `get` request to a specific API. The Set-Cookie response header in developer tools shows: `Set-Cookie: "TESTCOOKIE=setcookie; path=/"`, but `document.cookie` is blank.

However, when I use standard XMLHttpRequest and when I just navigate to the API in the browser URL, the cookie does get set. I have no idea why this is happening.

**Comment by dgraham** [comment]
See #393.

**Comment by wlingke** [comment]
excellent thanks
