### ISSUE TITLE
upload progress return response.json()?

### ISSUE THREAD

**Issue by bORm** [github/fetch#395]
Hi, i have readed 
https://github.com/whatwg/fetch/issues/21
https://github.com/github/fetch/issues/202
https://github.com/github/fetch/pull/290
https://github.com/github/fetch/issues/379

And this issue copy https://github.com/whatwg/fetch/issues/389

How get response json from server after progress upload

```
function consume(response, total=0) {
  var reader = response.body.getReader()
  return pump()
  function pump() {
    return reader.read().then(({done, value}) => {
      if (done) {
        return response
      }
      total += value.byteLength
      log(`received ${value.byteLength} bytes (${total} bytes in total)`)
      return pump()
    })
  }
}

fetch("/music/pk/altes-kamuffel.flac", {method: 'POST', body: MYFormData})
  .then(response => consume(response))
  .then(response => return response.json() // "return Already read" )
  .then((resultFromServer) => log(resultFromServer.file)) 
  .catch(e => log("something went wrong: " + e))
```

**Comment by dgraham** [comment]
In this example, you're uploading a form to an audio URL, then reading a streaming response body from the server, then consuming the response again as a JSON document. An HTTP response body may only be consumed a single time.

This fetch polyfill does not implement response body streaming, so you'll want to use Chrome for testing that.

**Comment by bORm** [comment]
Shit you fetch, I can write similar module based on xmlhttprequest on promise with progress and normal response
