### ISSUE TITLE
Encoding issue for Array responses in Firefox 18

### ISSUE THREAD

**Issue by dylanpyle** [github/fetch#396]
We're running into an issue in old versions of firefox (specifically FF18, but likely others) where the response encoding seems to be somehow very, very wrong when trying to parse Arrays as JSON.

Here's a reduced test case:

https://jsfiddle.net/w7s0o2ow/2/

— simple stuff; we fetch a JSON array, then try parsing it as JSON.

## Expected result
This works in every other modern browser we've tried, e.g in Chrome:
![](https://cloudup.com/clr6C6Q_E_R+)

## Actual result (firefox 18, windows 7)
![](https://cloudup.com/cu8KY-3aBhr+)

**Comment by dylanpyle** [comment]
Some other "broken browser" datapoints, if anyone's interested in testing: FF15-19 seems to be affected, FF12 and FF20 are not

**Comment by dgraham** [comment]
I downloaded Firefox 18 and it wouldn’t load the jsfiddle page successfully. I’m impressed you got that far!

A couple ideas for debugging:

- The behavior may be affected by Content-Type or other response headers. Does it parse JSON responses from other URLs, like `https://api.github.com`?

- You might add a `debugger` breakpoint when fetch [starts the `XMLHttpRequest`](https://github.com/github/fetch/blob/a82b0a9b84f2490112a9d29299f359a57ac2b00a/fetch.js#L381) process and step through the code to inspect the headers and response body.

We don’t support browsers this old, so I’ll close this issue. But feel free to add comments if you find the source of the problem. It could help others in the future.

**Comment by dylanpyle** [comment]
@dgraham Yeah, this doesn't seem to be specific to our API. Here's a version hitting the Github API, with the same issue: https://jsfiddle.net/w7s0o2ow/6/

For some reason I had thought during testing that only `Array` responses were affected, but it looks like `Object`s are broken too.

Just curious - do you have a defined list of supported browsers? The README just says "Firefox". We're leaning on this polyfill pretty heavily (thanks for all your work on this!), so whatever's officially supported here will inform our own support matrix.

**Comment by dgraham** [comment]
Firefox 33 was current when the fetch polyfill was first written, and Firefox 39 introduced a native fetch implementation. We don't maintain a list of specific browser versions, but based on your testing here, versions 20–38 work well.
