### ISSUE TITLE
response headers incomplete in the CORS request.

### ISSUE THREAD

**Issue by Abel94** [github/fetch#399]
hi, example:

```
fetch('https://registry.npm.taobao.org')
    .then((response) => {
        response.headers.forEach((val, key) => {
            console.log(key, val)
    })
})
```

output: 

```
content-type application/json; charset=utf-8
```

but see the response information:

```
Access-Control-Allow-Origin:http://localhost:8080

Connection:keep-alive

Content-Length:776

Content-Type:application/json; charset=utf-8

Date:Fri, 23 Sep 2016 14:57:34 GMT

ETag:"308-KTjgFOxcNZRPaaFF01sFMw"

X-Current-Requests:1

X-ReadTime:1456
```

Why can't obtain other header information?

**Comment by mislav** [comment]
I'm guessing that the `registry.npm.taobao.org` response must explicitly allow the requester to read the headers via some CORS settings. When I manually hit `registry.npm.taobao.org`, I don't see any CORS headers being set.

**Comment by Abel94** [comment]
Thanks! I find this is just one example of the URL, I tested locally, the server completes the CORS agreement and can normally obtain data.

When implementing jwt trying to get Authorization, but the findings are not obtained.

**Comment by Abel94** [comment]
I did a full example:

```
fetch('https://api-demo.websanova.com/')
  .then((response) => { 
    response.json().then((json) => {
      console.log(json)
    })

    response.headers.forEach((val, key) => {
      console.log(key, val)
    })
  })
```

Data can be acquired, but the header is not acquired.

**Comment by dgraham** [comment]
See the `Access-Control-Expose-Headers` description in this [CORS tutorial](http://www.html5rocks.com/en/tutorials/cors/).
