### ISSUE TITLE
Fetch native not supported on iOS 10

### ISSUE THREAD

**Issue by germanorizzo** [github/fetch#401]
Hi,
    thanks for this work. One very minor thing: contrary to what is stated on the readme, iOS 10 seems not to support native fetch functionalities. Maybe you could edit the Readme, for clarity.

Thanks again!

      G.

**Comment by mislav** [comment]
It states in the README that Safari on macOS supports native `fetch`, but that statement is also untrue, since it didn't seem to have shipped with native support after all. I'll amend the text. Thanks for the heads-up! /cc @dgraham

**Comment by jhabdas** [comment]
@germanorizzo For `fetch` support on Mobile Safari you need to be using Safari 10.1.  To test your version of Mobile Safari click the link titled `javascript:alert(navigator.userAgent)` from [Analyzing User Agent Strings](https://habd.as/analyzing-user-agent-strings/) (about half-way down the page) and look for `Version/10.1` in your user agent string.

**Note:** If you `window.alert(window.fetch)` on Safari Mobile you will see `fetch` is implemented. But I just tested it and it doesn't work.

**Comment by jhabdas** [comment]
Here's the official scoop on when we can expect `fetch` support in Safari, quoted directly from Jon Davis of Apple:

> The status reported is correct. Fetch is still technically "in development” in WebKit, meaning changes can still happen up until the wide release to customers in Safari. Ostensibly that release will be in the forms of Safari 10.1 on macOS and Safari for iOS 10.3, both of which are currently in beta and do include support for Fetch. That means when those beta version ship to customers, Fetch will be available. Once the new products are released, the status of Fetch on the WebKit Feature Status page will change to “Done”.

> Both Can I use…  and MDN are reporting correctly: Fetch will become available in Safari in the Safari 10.1 release that ships with macOS Sierra 10.12.4 and Safari on iOS 10.3. I hope that is helpful.
