### ISSUE TITLE
TypeError: HEAD or GET Request cannot have a body.

### ISSUE THREAD

**Issue by huanghaiyang** [github/fetch#402]
should HEAD or GET can not add a body ?

**Comment by jeffhuys** [comment]
HEAD or GET requests should never have a body. Be sure you give `body: undefined`. `null` is not the same as "nothing".

**Comment by radiosilence** [comment]
@jeffhuys Surely there should be an override for this? We don't always control the APIs we talk to, especially if they are written by another company. It seems extremely patronising to actively prevent people doing this.

**Comment by nshgraph** [comment]
Stating that a GET request **should never** have a body is not in the HTTP spec. https://tools.ietf.org/html/rfc7231#section-4.3.1

Elasticache is the primary example of an api that uses bodies in GET requests.
