### ISSUE TITLE
Native fetch missing methods on Headers in MS Edge

### ISSUE THREAD

**Issue by nhardy** [github/fetch#407]
Not sure if this is entirely within the scope of this polyfill, but [Microsoft's Edge's implementation](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/apireference/interfaces/headers/) of the fetch API and its corresponding `Headers` type are missing methods. It would be ideal if this project was able to polyfill these methods if they are not present:

`Headers.entries()`
`Headers.getAll()`
`Headers.keys()`
`Headers.values()`

**Comment by mislav** [comment]
Thanks for letting us know! Agreed that we should try to polyfill the missing methods.

**Comment by jimmywarting** [comment]
I did work a bit with node-fetch and thought it would be a good idea to abstract out the Headers to a separate module so it could be included anywhere...
How about just including https://www.npmjs.com/package/fetch-headers? It has support for entries, getAll, keys, & values

**Comment by mislav** [comment]
@jimmywarting That's not a far-fetched idea, but for now we like the convenience of having everything in a single file with no dependencies that people can easily load into their projects.

**Comment by STRML** [comment]
@jimmywarting You can get this via [fetch-ponyfill's](https://github.com/qubyte/fetch-ponyfill) exports.

**Comment by dgraham** [comment]
The easiest fix would be to expand [this check](https://github.com/github/fetch/blob/90cf4501c7e91271970c7e2423019813d38fd53e/fetch.js#L4-L6) to test for `entries`.

```js
if (self.fetch && self.Headers.prototype.entries) {
```

The missing methods are part of the `Iterable` interface and will likely be implemented together when Edge makes `Headers` conform to that interface. Firefox had a similar partial `Headers` implementation in the past too.

We polyfilled these methods in #295.

**Comment by dgraham** [comment]
I didn't find a report for this in the [Edge issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/), so I [reported it](https://twitter.com/davidgraham/status/787335657291026432) via Twitter.

**Comment by molant** [comment]
Bug opened [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9370062/)

**Comment by mislav** [comment]
Just a heads-up that I'm currently in the process of selectively polyfilling these methods for Edge but am running into some hurdles. Namely, Edge also doesn't support `getAll`, which technically isn't part of the iterable interface, but is trivial to polyfill. However, while running tests, I've noticed how some existing tests for other Headers methods fail in Edge due to it implementing the spec *more* precisely than us or Chrome. Therefore, we will need to adjust our test suite. I'm trying to read carefully through the spec and confirm that each of our tests is adjusted according to the spec.

**Comment by mislav** [comment]
@dgraham and I decided that we are not going to polyfill these methods on Edge, because it opens a whole can of worms regarding cross-browser support due to the fact that Chrome, Firefox, and Edge implement Headers methods such as `get`, `getAll`, `forEach`, and iterable methods inconsistently. We decided we were not normalizing the native implemenation of Headers in any browsers. This polyfill is simply providing `window.fetch` to browsers that don't have it.

**Comment by nolanlawson** [comment]
I agree it sounds like a better bet to just wait for Edge to fix these issues. Sorry for the trouble; is it possible to feature-detect and load the polyfill?

**Comment by mislav** [comment]
@nolanlawson Yes:

```html
<script>
  if (/* your feature detection here */) {
    window.fetch = undefined // have the polyfill override the native implementation
  }
</script>
<script src="./fetch.js"></script>
```

**Comment by nolanlawson** [comment]
Yes I mean is it possible to feature detect Edge's implementation vs a full fetch() implementation. I guess by inspecting the Headers prototype?

**Comment by STRML** [comment]
Sure, that's possible that way, but you won't get https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9383422/ and the like

**Comment by nolanlawson** [comment]
Fair enough, just trying to understand the impact. :) And yeah I just tested; `'entries' in Headers.prototype` will suss out that issue, but obviously not the DELETE issue.

**Comment by nolanlawson** [comment]
@mislav 

> some existing tests for other Headers methods fail in Edge due to it implementing the spec more precisely than us or Chrome

Could you provide some more details on this? If Chrome (and maybe Firefox/Safari?) are deviating from the spec, then it would be helpful for us to know. Also did you file a bug on Chrome? /cc @aliams

**Comment by nolanlawson** [comment]
OK, did a bit of research and found that [the Headers spec](https://fetch.spec.whatwg.org/#headersinit) doesn't define those methods, but it is an [Iterable, which does](https://heycam.github.io/webidl/#idl-iterable). However Iterable defines `entries()`, `keys()`, `values()`, and `forEach()`, but not `getAll()`, which both Firefox and Chrome implement, so I'm not sure where `getAll()` comes from.

**Comment by STRML** [comment]
That is indeed odd. It appears `getAll()` has been removed from the living spec. The [MDN Link](https://fetch.spec.whatwg.org/#dom-headers-getall) doesn't resolve.
