### ISSUE TITLE
inconsistent behavior when constructing a new Request

### ISSUE THREAD

**Issue by jimmywarting** [github/fetch#411]
This fails with polyfill - works ok in browser

``` javascript
x = new Request('x')
y = new Request(x)
console.assert(x.bodyUsed === false) // expected bodyUsed to be false
```

**Comment by mislav** [comment]
At the time of implementing this in 3bc7b45a, I thought I was doing this per-spec. Can you check with the spec to verify? The native implementation in your browser might not be correct.

**Comment by jimmywarting** [comment]
Didn't find anything about setting it to true. but i found this:

![skarmavbild 2016-10-17 kl 23 14 53](https://cloud.githubusercontent.com/assets/1148376/19456044/f8c943b8-94bf-11e6-9f59-131c7ceaf9e2.png)

**Comment by jimmywarting** [comment]
Ah, I know if body is null then don't run this step

if you where to do this:
```javascript
x = new Request('x', {method: 'post', body: 'x'})
y = new Request(x)
console.assert(x.bodyUsed === true) // then you expect it to be true
```
