### ISSUE TITLE
Can't post data

### ISSUE THREAD

**Issue by kopax** [github/fetch#412]
I have the following code:

    const options = {
      method: "POST",
      header: {
        "Accept": "application/json",
        "Content-Type": "application/x-www-form-urlencoded"
      },
      data: JSON.stringify({ username, password })
    };
    console.log(JSON.stringify(options));
    // "{"method":"POST","header":{"Accept":"application/json","Content-Type":"application/x-www-form-urlencoded"},"data":"{\"username\":\"joe\",\"password\":\"$2a$10$ZGthAAAAAAAAAAAAAAAAA.KoRc0Kh2hRVNtEP4PVJgtUc1geJw.nW\"}"}"
    let dataOrErr = fetch("http://localhost:8080/login", options)
        .then(checkStatus)
        .then(parseJSON)
        .then((data) => ({ data }))
        .catch((err) => ({ err }));
    console.log(dataOrErr);
    // Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}

The options object is fully filled, the xhr request send is a POST, however, __I can't see any data submited with this form.__

**Comment by mislav** [comment]
You are sending JSON data using `application/x-www-form-urlencoded` Content-type.

**Comment by kopax** [comment]
Well, this is just a tried.

I have tried before with         // "Content-Type": "application/x-www-form-urlencoded"  and it didn't work either.

**Comment by mislav** [comment]
It always helps to post JSON data using the JSON content-type.

```js
const options = {
  method: "POST",
  header: {
    "Accept": "application/json",
    "Content-Type": "application/json"
  },
  data: JSON.stringify({ username, password })
}
```

**Comment by kopax** [comment]
@mislav, this is the first configuration I have tried, but it didn't helped.

      // Post a real request
      const options = {
        method: "POST",
        header: {
          "Accept": "application/json",
          "Content-Type": "application/json"
        },
        data: JSON.stringify({ username, password })
      };
      console.log(JSON.stringify(options));
      // "{"method":"POST","header":{"Accept":"application/json","Content-Type":"application/json"},"data":"{\"username\":\"joe\",\"password\":\"$2a$10$ZGthAAAAAAAAAAAAAAAAA.KoRc0Kh2hRVNtEP4PVJgtUc1geJw.nW\"}"}"
      let dataOrErr = fetch("http://localhost:8080/login", options)
          .then(checkStatus)
          .then(parseJSON)
          .then((data) => ({ data }))
          .catch((err) => ({ err }));
      console.log(dataOrErr);
      // Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}

![image](https://cloud.githubusercontent.com/assets/1866564/19493243/107dbd1a-95a4-11e6-9077-3099a5b7cbc7.png)

**Comment by mislav** [comment]
> this is the first configuration I have tried, but it didn't helped.

I didn't know. You should have told us that.

Thanks for sharing more info about your request, but looking at it I can't immediately tell what's wrong with your request. I see, however, that you're making a CORS request. Even though your server at `localhost:8080` seems to allow requests from `localhost:3001` where you're making them from, there are specific restrictions on POST bodies for CORS requests that you might not be yet aware of. The responsibility is on you to familiarize yourself with preflight requests. We can't help you here, unless you're reporting an actual bug with our polyfill, which you are not since you're using Chrome which implements its own native `window.fetch`, and thus this polyfill code is never used. If there is a bug (which is unlikely), it is with Chrome.

**Comment by kopax** [comment]
@mislav, I have tested the cors request before running this test, so It cannot be CORS.

The only difference here is that I am sending string has parameters, not in the body.

here is a vanilla js client running on port 8000 request to the __same__ server. 

![image](https://cloud.githubusercontent.com/assets/1866564/19505886/c1af2bcc-95f0-11e6-88ed-600cb4cac1d9.png)

You can see the status code for each request:

![image](https://cloud.githubusercontent.com/assets/1866564/19505898/dd6f3e60-95f0-11e6-934c-aa0caaf87841.png)


I am using instance of XMLHttpRequest for each request.

**Comment by kopax** [comment]
I think this should be reopened as it is certainly not related to CORS.
I have replaced the fetch code with an oldschool XMLHttpRequest, and it went well.

**Comment by mislav** [comment]
> We can't help you here, unless you're reporting an actual bug with our polyfill, which you are not since you're using Chrome which implements its own native `window.fetch`, and thus this polyfill code is never used. If there is a bug (which is unlikely), it is with Chrome.

Did you read my comment? ^

**Comment by kopax** [comment]
I did, I am not using the window.fetch from chrome but the one from my node_modules folder. 

From my package.json : 

    "whatwg-fetch": "1.0.0"

NPM: https://www.npmjs.com/package/whatwg-fetch
GitHub: https://github.com/github/fetch/tree/v1.0.0

**Comment by mislav** [comment]
If you type `window.fetch` in the web inspector, does it say `[native code]` or not?
