### ISSUE TITLE
For those who want to use bluebird with fetch in browser and node

### ISSUE THREAD

**Issue by FTAndy** [github/fetch#417]
if you want to use bluebird in browser, use this, and
```javascript
window.fetch = null

window.Promise = bluebird

require('whatwg-fetch')
```
the latest version browser may have fetch API already, this repo will return false if there is fetch API.

if you want to use bluebird in node, use [node-fetch](https://github.com/bitinn/node-fetch), and
```javascript
let fetch = require('node-fetch');

fetch.Promise = bluebird
```

**Comment by mislav** [comment]
Thanks for the tips! We won't recommend that people use Bluebird in the browser, though, since it's 55 kB. Node is fine, but our fetch polyfill is not meant for node.
