### ISSUE TITLE
Documentation for Typescript users.

### ISSUE THREAD

**Issue by kritollm** [github/fetch#418]
Solution: `npm install @types/whatwg-fetch --save-dev`

I searched for a solution to add typings for this library, but didn't find any solution.

Then in desperation I just tried` npm install @types/whatwg-fetch --save-dev` and it worked.

Since all the old TypeScript issues is closed without solution, I thought to mention it in case others are struggling with the same thing.

**Comment by mislav** [comment]
What is the `@types` scope?

**Comment by kritollm** [comment]
[The repository for high quality TypeScript type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped). You can read more about it [here](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/).

**Comment by mislav** [comment]
Ah I see: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/whatwg-fetch/whatwg-fetch.d.ts

And how does `@types/whatwg-fetch` get discovered within your `node_modules/` directory? Does TypeScript do that discovery by default?

I guess what I'm asking is whether your experience is reproducible for other people having different projects and different build chains.

**Comment by kritollm** [comment]
It works for TypeScript > 2.0,  older versions can use`typings install dt~whatwg-fetch --global --save`

**Comment by mislav** [comment]
Thanks for the info.

@dgraham do you think we could add a note about TypeScript definitions to the Readme?

**Comment by dgraham** [comment]
The TypeScript community has [documented this command](https://github.com/DefinitelyTyped/DefinitelyTyped#npm). I don't think each upstream library needs to document it too, considering the workflow could change over time.

**Comment by kritollm** [comment]
I agree, I was confused by the closed issues without solutions. When Typescript 2 becomes standard it will no longer be a issue anyway.
