### ISSUE TITLE
PUT becomes OPTIONS

### ISSUE THREAD

**Issue by TyraelYoung** [github/fetch#423]
js code :       

```js
fetch(URL_SET_DEFAULT , {
            method: 'PUT',
            credentials: 'same-origin',
            body: formData,
        }).then((response) => {
            if (response.ok) {
                return response.json();
            }
        }).then((json) => {
            alert(JSON.stringify(json.msg));
        }).catch((error) => {
            console.error(error);
        });
```

chrome devtools show the general info
Request URL:http://api.ssb2.test.csmall.com/member/bank/default
Request Method:OPTIONS
Status Code:405 
Remote Address:120.24.251.82:80

so the problem is  the client "PUT" becomes "OPTIONS" in the server side.

**Comment by mislav** [comment]
It sounds like you're making a request to another domain. Please [familiarize yourself with CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests) and all the limitations it has.
