### ISSUE TITLE
Detect 503 status code if rejected by CORS

### ISSUE THREAD

**Issue by NeXTs** [github/fetch#426]
Is it possible to detect response status code if request was rejected by CORS?

Let's say for testing purposes my server side which is located on different domain is hardcoded to return 503 status code. Because of that - all requests rejects and catched by `.catch(error => {})` but `error` argument is just rejecting message (_TypeError: Failed to fetch_), it does not contain status code and I can not find a way to detect it.

Is it possible at all?

**Comment by dgraham** [comment]
I don't think this is possible because a 503 error will be sent in response to the `OPTIONS` pre-flight request, which is considered part of the connection setup and unavailable to `fetch` or `XMLHttpRequest`.
