### ISSUE TITLE
Error in Android 4.0.3, UC browser 11.2.0.880, Lenovo Phone caused by blob。

### ISSUE THREAD

**Issue by ilife5** [github/fetch#433]
I have caught an error in Android 4.0.3, UC browser 11.2.0.880, Lenovo Phone 。

The xhr object in console:

![image](https://cloud.githubusercontent.com/assets/785102/20305402/67215618-ab70-11e6-85bd-f04ad30fcd6d.png)

This error has been caught in the xhr.onError function.

**Comment by mislav** [comment]
1. Can you share the `fetch` invocation that caused this bug?
2. Is it reproducible every time?
3. Is the request CORS, i.e. to another domain?
4. Which version of fetch polyfill are you using?

I've just tried to run our test suite on Android 4.0, but it largely passes (it only has failures around ArrayBuffer/DataView body handling). So I'm not sure where the error comes from.

**Comment by ilife5** [comment]
Could not reproduce now.

1. 

```
fetch(requestPath, headerOptions).then(response => response.json().then(json => ({
        json,
        response,
      }))).then(({
        json,
        response,
      }) => {
        if (response.status === 200) {
          return resolve(json);
        }
        return reject(json);
      });
```

2. No
3. yes, the request is CORS.
4. 2.0.0

**Comment by mislav** [comment]
If the error is not reproducible, do you mind if we close this? It might have been related with how the browser handles CORS and not something we can fix from the polyfill. Also, Android 4.0 is a platform we're not regularly testing on, but as I said, I've ran the test suite on it and it largely passes.

**Comment by ilife5** [comment]
@mislav 

I'll close it。Thanks all the same。
