### ISSUE TITLE
 Response.redirect 如何阻止其自动跳转

### ISSUE THREAD

**Issue by Yhaojing** [github/fetch#436]
返回302 fetch 会自动跳转到location，怎么阻止其自动跳转

**Comment by dgraham** [comment]
> Return 302 fetch will automatically jump to location, how to prevent its automatic jump

I don't think this is possible in native browser fetch implementations based on the [atomic redirect handling](https://fetch.spec.whatwg.org/#atomic-http-redirect-handling) description in the specification. It's not possible with this polyfill because redirects are not exposed to XMLHttpRequest.
