### ISSUE TITLE
Android 4.x, TypeError: Object #<Response> has no method 'blob' when use systemjs

### ISSUE THREAD

**Issue by JiaLiPassion** [github/fetch#437]
fetch version 2.0.0
The detailed error log is here 
https://travis-ci.org/angular/zone.js/builds/176598482

It seems in Android4.x, support.arrayBuffer is true, but blob is false.

If I modify the package.json, with "whatwg-fetch": "https://github.com/jimmywarting/fetch.git" , 
the error is gone.

**Comment by mislav** [comment]
I see; thanks for reporting.

I think what we did before is not define the `response.arrayBuffer()` method at all if Blob wasn't supported. Do you think it would be useful to bring back that behavior? Then you can check the existence of the `arrayBuffer()` function before calling it to avoid exceptions on old browsers.

**Comment by JiaLiPassion** [comment]
Thank you for your reply, 

> I think what we did before is not define the response.arrayBuffer() method at all if Blob wasn't supported

Yes, I think whether go back to old behavior that if no arrayBuffer then no blob, or add another check even arrayBuffer exists still check old browser support blob or not?

**Comment by mislav** [comment]
Hah I just spotted this in your test suite: https://github.com/angular/zone.js/blob/c69df259a6bc0caa49acd914b66b83b35fbbc784/test/common/Promise.spec.ts#L439

**Comment by JiaLiPassion** [comment]
thank you for finding the case, I will study into it.

**Comment by mislav** [comment]
Fixed in 3d3bb0ca72172b224e8101c0a5264adc41f53929; new releases are under way
