### ISSUE TITLE
About `cache` option

### ISSUE THREAD

**Issue by poppinlp** [github/fetch#438]
Seems `cache` option not work in this polyfill.
It's hard to do polyfill for some cache mode such as `force-cache`. But we could support behavior similar to `no-store` by query string at least.
So do you think it is necessary to do this?
I think it will be convenient if this option is available, although I could assemble the URL outside.

**Comment by mislav** [comment]
There are some things we are not able to polyfill due to limitations with XMLHttpRequest. This is one of them. Sure, we could maybe support `no-store` by appending a cache-busting parameter to the URL, but I'd rather not tamper with URLs. Also, it doesn't make sense to implement just one of the possible `cache` options while not supporting the others.

**Comment by poppinlp** [comment]
OK got it. THX

**Comment by serbanghita** [comment]
@mislav this is really an issue on IE11, would you be interested in review-ing a PR for this?

**Comment by jslegers** [comment]
> There are some things we are not able to polyfill due to limitations with XMLHttpRequest. This is one of them.

I understand that you may not be able to polyfill all behavior of IE, but I would expect that IE11's caching behavior is the same as that of other browsers when no cache settings are provided.

IMO, default behavior should be the same in polyfilled and non-polyfilled browsers.

> Also, it doesn't make sense to implement just one of the possible cache options while not supporting the others.

It makes even less sense to have different default behavior in a polyfilled browser than in the other browsers. This kind of defeats the purpose of using a polyfill.

Consider my use case :

Up until yesterday, the sample code of [LuciadRIA](https://www.youtube.com/watch?v=I9wG5uTQhbY) still made use of [`dojo/request`](https://dojotoolkit.org/reference-guide/1.10/dojo/request.html) for XHR requests. When replacing `dojo/request` with a `fetch` based implementation, I've looked into this polyfill for dealing with IE11.

Whenever I send a PUT request to my rest store, the server correctly updates the data in all browsers. But when I refresh my browser, all browsers show the updated data... except IE11. IE11 still shows the original data loaded, unless I first cleared my cache. It took me many hours of frustrated head scratching to figure out why IE11 didn't behave the same as other browsers and realize that there was a caching issue.

Cache busting does solve this problem, but it feels like a hack... and I feel like it kind of defeats the purpose of using a polyfill when I have to use hacks like this to make every browser behave the same. This, especially considering I did not need to use this sort of black magic when using `dojo/request`.
