### ISSUE TITLE
Is IE9 Support possible ?

### ISSUE THREAD

**Issue by onigoetz** [github/fetch#439]
Hello,

I work in a company where we still have to support IE9 users, it's not ideal but we have to deal with it.

We would love to use fetch in our projects but are limited by it's current IE10+ support.

If we make a Pull Request to add IE9 support, would you be interested ?

**Comment by mislav** [comment]
We're not interested in maintaining IE 9 support. We consciously dropped it in fetch 1.0 release.

As a solution for you I propose: are you able to use fetch 0.11 instead? That still includes IE 9 support.

**Comment by onigoetz** [comment]
This might do the trick in the meantime :D 

Thank you for your quick answer.
