### ISSUE TITLE
Response.url support for older MS Edge Build

### ISSUE THREAD

**Issue by yiransheng** [github/fetch#443]
I have located the implementation for `response.url` polyfill:

https://github.com/github/fetch/blob/master/fetch.js#L427

```
options.url = 'responseURL' in xhr ? xhr.responseURL : options.headers.get('X-Request-URL')
```

However, there's a bug in older build of Edge, where `xhr.responseURL` is an empty string. The only reference to this bug I can find is this [stackover flow question](http://stackoverflow.com/questions/38319150/xmlhttprequest-in-edge-responseurl-property)

> Basically I use the responseURL variable that XMLHttpRequest's give back. The problem is for some reason my code wasn't working on Microsoft Edge, but it was on Chrome/Firefox. You will also notice that the responseURL property isn't in the Edge docs, https://msdn.microsoft.com/enus/library/ms535874(v=vs.85).aspx

I have observed this buggy behavior a old version of Edge, and the following code failed to work:

```
fetch(url)
  .then(response => {
    if (isValidAPI(response.url)) {
      // do stuff
    }
  ))
```

Because `fetch` polyfill's `response.url` evaluates to an empty string. 

This could be fixed by something like:

```
options.url = 'responseURL' in xhr ? (xhr.responseURL || request.url) : options.headers.get('X-Request-URL')
```

EDIT: a bit more thoughts, just use `request.url` is not enough in case of 30x redirects, a compromise could be special check for Edge and fallback to `request.url` only if `xhr.responseURL` is empty, and browser is Edge.

**Comment by mislav** [comment]
Thanks for letting us know. How about this?

```js
xhr.responseURL || options.headers.get('X-Request-URL') || request.url
```

**Comment by yiransheng** [comment]
Thanks for the fast response, looks like a good solution!

**Comment by barbarosalp** [comment]
Hi @yiransheng,

How can i get "responseURL" for the request below for Edge browser:

 ```
      var request = new Request(url, {
            method: 'HEAD',
            mode: 'cors',
            redirect: 'follow'            
        });

        var b = fetch(request)
        .then(function (response) {
            var a = "";
        }).catch(function (ex) {
            var b = "";
        });
```

**Comment by idavollen** [comment]
@mislav what if the fetch(url, {redirect: 'follow'}) call got redirected to a new url ? How to retrieve the redirected url in IE 11? and fetch Response.redirected has wrong value _false_ even though the ajax call was redirected in IE 11 and it works well with Chrome, Firefox.

So can you shed the light on how to detected if fetch was redirected or not? if redirected, how to retrieve the redirected url in IE 11? Thanks in advance!

**Comment by idavollen** [comment]
@mislav thanks for your prompt reply. How about the field _**redirected**_ in fetch Response when redirect occurs, https://developer.mozilla.org/en-US/docs/Web/API/Response/redirected?

**Comment by mislav** [comment]
@idavollen We don't seem to implement this property in the polyfilled Response object. Browsers don't usually give us any insight into whether the XHR response was obtained after following a redirect or not.

**Comment by mislav** [comment]
This was a while ago, and since the fix was supposed to target an older version of Edge, I'm going to assume that such an ancient version of Edge isn't in circulation anymore. Thanks for all your thoughts!
