### ISSUE TITLE
No respect for "cache" option

### ISSUE THREAD

**Issue by DimitryDushkin** [github/fetch#446]
There is no any code that handles "cache" option https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

On IE11 this causes similar request always fetching from cache.

**Comment by mislav** [comment]
You're right. It's due technical limitations. See explanation here https://github.com/github/fetch/issues/438#issuecomment-261272466

**Comment by pawelrychlik** [comment]
This should be written in bold in README/Caveats section imho.

**Comment by mislav** [comment]
It's listed in [Caveats of the web site](https://github.github.io/fetch/#caveats).

**Comment by MihaMarkic** [comment]
It should be listed on top of page with big red font and blinking :)
