### ISSUE TITLE
Question about Safari 5.x Support

### ISSUE THREAD

**Issue by alphanull** [github/fetch#451]
Hello, just a simple question:

Safari 6.1+ is the earliest supported Safari version according to the docs.

Now, I need Safari 5.x support as well. I just tried the fetch polyfill with Safari 5.1 on OS X 10.6.8 and on a first glance, it seems to work just OK. Was Safari 5.x just not tested or is there a specific issue that prevents (full) support? If yes, what exactly does not work?

**Comment by mislav** [comment]
I'm not sure why we drew the line at Safari 6.1 specifically. It's possible that the polyfill works well on Safari 5. However, us stating that we “support Safari 6.1+” means that we don't aim to fix bugs that might affect Safari 5 or Safari 6.0 users.

So, of course you can use this polyfill on older browsers, but you discover issues specific to those (unsupported browsers), you will need to fork this polyfill in your own project and make fixes there.

I hope everything works out for you!

**Comment by alphanull** [comment]
FYI: seems to work fine so far even with Safari 5.1 (on OS X 10.6.8)

**Comment by mislav** [comment]
Thanks for reporting!
