### ISSUE TITLE
How to use fetch post json and Sending cookies ?

### ISSUE THREAD

**Issue by kizzyang** [github/fetch#452]
How are you.
I have a question: How to use fetch post json and Sending cookies ?
My code:
`return fetch('/category/save.json' , {
            credentials: 'include',
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }).then(function(response){
            if (response.status >= 200 && response.status < 300) {
                return response
            } else {
                var error = new Error(response.statusText);
                error.response = response;
                throw error
            }
        }).then(function(response) {
            return response.json();
        }).then(function(json) {
            console.log('parsed json', json)
        }).catch(function(ex) {            
            console.log('parsing failed', ex)
        });`

Why cookie not send?
                                                                                         Thank you.

**Comment by mislav** [comment]
https://github.com/github/fetch#sending-cookies

**Comment by kizzyang** [comment]
I only use parameter `credentials: 'include' ` ,   The cookie Can send.
But I use parameter `credentials: 'include' ` and  `headers: {
    'Content-Type': 'application/json'
  }` to post json data,  Why cookie not send?

**Comment by kizzyang** [comment]
I only use parameter credentials: 'include' , The cookie Can send.
But I use parameter credentials: 'include' and headers: { 'Content-Type': 'application/json' } to post json data, Why cookie not send?

**Comment by mislav** [comment]
Are you sending a request to another domain? See this note about CORS https://github.com/github/fetch#read-this-first

**Comment by xgqfrms** [comment]
# `credentials: "include"`

https://developers.google.com/web/updates/2015/03/introduction-to-fetch

![image](https://user-images.githubusercontent.com/7291672/41389183-e6bb2de2-6fc1-11e8-9145-c7eaf6e91da9.png)

**Comment by xgqfrms-GitHub** [comment]
# why & solution

> cookie & Fetch & credentials

https://github.com/github/fetch#sending-cookies
https://github.com/github/fetch#receiving-cookies

![image](https://user-images.githubusercontent.com/18028768/41389732-05d27958-6fc5-11e8-928a-097e7a0fdb56.png)

**Comment by seajean** [comment]
why people answering question without watching closely to the question.

**Comment by seajean** [comment]
@kizzyang I find out what the problem is, change your params form 

` {
            credentials: 'include',
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }
`

to 

` {
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            credentials: 'include',
            method: 'POST',
            body: JSON.stringify(data)
        }
`

**Comment by seajean** [comment]
@mislav this is a bug,  you should fix it

**Comment by keithamus** [comment]
@seajean if there is a bug, would you kindly please file a new issue that details the bug - including a code reproduction? That way we can address it much more quickly

**Comment by seajean** [comment]
@keithamus Sorry~  I finally found out it was Chrome’s problem,in some cases Chrome debugger do not show the cookie,but  Charles do.  The cookie has been sent.
