### ISSUE TITLE
headers.getAll() support

### ISSUE THREAD

**Issue by 1999** [github/fetch#456]
Currently headers.getAll is undefined

**Comment by mislav** [comment]
`getAll` was removed from the spec: 02b1dcb5424484b326b75313c2b9cab8758b479c

**Comment by 1999** [comment]
Hm... Thank you, didn't know about that.
MDN page seems to outdated then? https://developer.mozilla.org/en-US/docs/Web/API/Headers/getAll

**Comment by mislav** [comment]
Yes probably. Also implementation in Firefox and Chrome is outdated, i.e. not according to spec anymore. I'm sure that you could contribute a fix to MDN's documentation because I believe it's wiki style.
