### ISSUE TITLE
Make module available without polyfill

### ISSUE THREAD

**Issue by qubyte** [github/fetch#46]
It would be nice to be able to require `fetch` without it being appended to `window` in a similar way to the `es6-promise` polyfill. If `fetch` can be assigned to a variable, then this means that when a broken or otherwise incompatible version of the fetch API become available in a browser, code that uses `fetch` won't break.

In other words:

```javascript
// This fetch can be used as is.
var fetch = require('fetch');

// Do this only if you want to polyfill fetch on the window object.
fetch.polyfill();
```

I realise however that this breaks the existing API.

**Comment by josh** [comment]
https://github.com/github/fetch/issues/9#issuecomment-69297320
