### ISSUE TITLE
Parsing formData failed with 'could not read FormData body as text'

### ISSUE THREAD

**Issue by idiotWu** [github/fetch#460]
Example code:

```js
const request = new Request('whatever', {
    method: 'POST',
    body: new FormData(),
});

request.formData(); // failed
```

I think this problem is caused by `this.text()` statement in [fetch.js#L283](https://github.com/github/fetch/blob/master/fetch.js#L283).

**Comment by mislav** [comment]
Thanks for reporting. What did you expect to get back from `formData()`; the identical object `new FormData()` that you passed as body?

Our support for `formData()` is really limited. Basically, it only handles parsing out text data encoded as `application/x-www-form-urlencoded`. It doesn't even handle `multipart/form-data` as it should per spec.

We also don't know how to improve this support, or even if we should at all. Chrome's `fetch` implementation doesn't seem to include `formData()` method at all. Even though both Chrome and this polyfill support passing FormData instances as Request body, _reading_ `formData()` from either Request or Response is little useful because FormData by design doesn't support any methods for introspection.

**Comment by idiotWu** [comment]
Actually I'm currently working on a network interceptor in browsers, I got this issue while testing. Although chrome doesn't support `.formData()` method, it can parse the formData body as text or blob.

I'm wondering if we can iterate through the formData body then create a copy of it like:

```js
this.formData = function() {
  if (this._bodyFormData) {
    var newFormData = new FormData();

    this._bodyFormData.forEach(function(val, key) {
        newFormData.append(key, val);
    });

    return newFormData;
  } else {
    return this.text().then(decode);
  }
}
```

**Comment by mislav** [comment]
> I'm wondering if we can iterate through the formData body then create a copy

Hm, I thought that it was not possible to read data stored within FormData, but it looks like it's possible using iterators in Chrome 50+ and Firefox 44+. You probably still can't do it with Safari and IE, though.

Do you have any concrete suggestions of what we could fix within the polyfill to make your work with FormData easier, while still conforming to the spec? We need to define an actionable goal as a result of this conversation.

**Comment by idiotWu** [comment]
Ah, hadn't noticed the compatibility...

It seems to be impossible to access FormData value in most browsers 😢. And unlike the `body.blob()` method, return `this._bodyFormData` directly maybe somehow dangerous as the FormData object is mutable.

This issue can be closed now, though I still think it's a little wired to throw a `could not read FormData body as text` error when using `body.formData()` method.

**Comment by mislav** [comment]
Yes I agree it's a little weird. When browser implementations of both `fetch` and FormData improve and it becomes a little clearer how this all should behave, we can improve the polyfill. But right now it's unclear to me what we should do, and while Chrome (the most popular browser) doesn't even implement the method and people are fine with it, I don't think it's time yet to obsess over it in the polyfill.

**Comment by caub** [comment]
Is https://github.com/github/fetch/blob/master/fetch.js#L343-L353 really serious?

I tried it, with some FormData sent from Node with form-data module
```
app.get('/optimize', (req, res)=>{
	var fd = new FormData();
	fd.append('test', ....); 
	res.header(fd.getHeaders());
	fd.pipe(res);
})
// and in browser:
fetch('http://localhost:3000/').then(r => r.formData()).then(fd=>{  console.log([...fd])})
```
but it doesn't parse things well

Any idea how to make something more solid? or when browsers will start implementing? `Response.prototype.formData` https://fetch.spec.whatwg.org/#body-mixin 

For now I use base64 in response, but too bad FormData isn't working well in the other direction server -> client

ex mltipart body:
```
----------------------------430383449649779322794935
Content-Disposition: form-data; name="test"; filename="worker1.js"
Content-Type: application/javascript

stuff
----------------------------430383449649779322794935--
```
the output of fetch is
```
["----------------------------374369449710540793030469
↵Content-Disposition: form-data; name",

""test"; filename="worker1.js"
↵Content-Type: application/javascript
↵
↵stuff
↵----------------------------374369449710540793030469--"]
```

**Comment by mislav** [comment]
@caub: As I've said above:

> Our support for `formData()` is really limited. Basically, it only handles parsing out text data encoded as `application/x-www-form-urlencoded`. It doesn't even handle `multipart/form-data` as it should per spec.

You are testing it with multipart encoding, which this polyfill doesn't support.

**Comment by cameron-martin** [comment]
It seems that FormData does now support introspection of the contained values: https://xhr.spec.whatwg.org/#formdata
