### ISSUE TITLE
URL vs URL string

### ISSUE THREAD

**Issue by joeshub** [github/fetch#462]
I could be wrong, but it appears the Fetch specification and most native implementations accept a _URL object_ as the first parameter to fetch() while it appears most of the examples here require a _URL string_, and passing a URL object breaks non-native implementations, for example Safari.

Is this polyfill built to support an URL object or URL string?

Thank you

**Comment by mislav** [comment]
Per spec, the `fetch()` method accepts a "RequestInfo" as 1st argument.

RequestInfo is [a Request or string URL](https://fetch.spec.whatwg.org/#requestinfo).

The `new Request()` constructor accepts an "input" as 1st argument.

"Input" is a string URL or Request.

Therefore, in both cases, the spec says that URLs should be passed as strings, not URL instances.

**Comment by dgraham** [comment]
> "Input" is a string URL or Request.

This is how I understand the specification as well. It's interesting, though, that Chrome, Edge, Firefox, and Safari Technology Preview all accept a URL object as the input parameter.

Intuitively, we expect passing a URL object to work, so maybe we're misreading the spec?

**Comment by mislav** [comment]
I don't think we're misreading the space. In [case of `new Request(input)`](https://fetch.spec.whatwg.org/#dom-request):

> 5\. **If input is a string**, then run these substeps: …
> 6\. **Otherwise (input is a Request object**), run these substeps: …

**Comment by joeshub** [comment]
Thanks for clarifying. FWIW I think what is confusing is the spec actually shows a [URL being used in an example](https://fetch.spec.whatwg.org/#fetch-api) not to mention as @dgraham  mentioned, most browsers supporting it now too.

```javascript
var url = new URL("https://geo.example.org/api"),
    params = {lat:35.696233, long:139.570431}
Object.keys(params).forEach(key => url.searchParams.append(key, params[key]))
fetch(url).then(/* … */)
```

**Comment by mislav** [comment]
@joeshub Ah, nice find. I agree that it would be intuitive to support URLs. If you have the time, you could try adding the tests that verify that we accept URL objects properly. Meanwhile, I'm going to open an issue in the spec repo asking for details.

**Comment by mislav** [comment]
Here's the official reply:

>  the binding layer (the bit IDL defines) will first check if the passed argument is a Request object and otherwise invoke `ToString()` on it

This is interesting and probably not what we do in the polyfill. We will have to change our behavior for spec compliance.

**Comment by Mouvedia** [comment]
The `toString` invocation needs to be documented prominently.
