### ISSUE TITLE
Better error when trying to `.json` a `Resource` that's not JSON.

### ISSUE THREAD

**Issue by matthew-andrews** [github/fetch#47]
It would be nice if there were a better error when trying to `.json` a `Resource` that's not JSON.

Currently in two implementations ([this polyfill](https://github.com/github/fetch) and Chrome Service Workers) trying to `fetch` and `.json()` a non JSON resource throws a not particularly helpful error:-

```js
fetch("//some.thing/not-a-json-resource")
  .then(function(res) {
    return res.json();
  })
  .catch(function(err) {
    console.log(err); // => Unexpected token c
  });
```

![screen shot 2014-12-24 at 12 36 59](https://cloud.githubusercontent.com/assets/825088/5548458/961311ce-8b69-11e4-8824-4ebb8bf7423f.png)

It would make for more less unpleasant debugging / error aggregation if it threw an error along the lines of “Failed to parse {{url}} as JSON”… or something like that…

[I know errors aren't spec'd](https://github.com/github/fetch/pull/44#issuecomment-67579609) as such so it's not something that should/could be fixed in the spec — but I will raise as an issue in Chrome as well so that GitHub & Chrome's fetches can stay aligned but I think it's something that should be improved and I'm sure you have an idea of what it might look like…

**Comment by josh** [comment]
Have any specific ideas for how we could improve this? Or should we just wait it out until Chrome makes the first move?

**Comment by dgraham** [comment]
I think this error is pretty good. "SyntaxError" and "unexpected token" are good clues that's it's invalid JSON. Then you can inspect the response and see it's HTML or other non-JSON data.

**Comment by matthew-andrews** [comment]
for what it's worth i'm playing with ideas here:-
https://github.com/matthew-andrews/fetchres#usage-node
