### ISSUE TITLE
cookie can't be set in chrome  

### ISSUE THREAD

**Issue by yepbug** [github/fetch#470]
```
fetch('http://mytest.com/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          credentials: 'include',
        },
        body: JSON.stringify({
          username: 'username',
          password: 'password',
        }),
      })
```

`chrome/55.0.2883.95` implements `fetch`. Perhaps, it didn't implement the specification as shown here -- [Fetch Standard](https://fetch.spec.whatwg.org/#example-cors-with-credentials). `Set-Cookie` response headers are always ignored, no matter whether `credentials` option is set or not.

However, `safari 10.0.2` has not implement `fetch`, so `ajax` makes `Set-Cookie`  functional.

So, for compatibility, is it possible to do something before [return](https://github.com/github/fetch/blob/master/fetch.js#L5)?

**Comment by mislav** [comment]
If you want to override Chrome's implementation with our polyfill—NOT RECOMMENDED—then you can do:

```html
<script>window.fetch = undefined</script>
<script src="./fetch.js"></script>
```

However, if you have problems when using native `fetch` in the browser, but using XMLHttpRequest (like this polyfill uses) works just fine with CORS and cookies, then perhaps you should use XMLHttpRequest directly in your app and not `fetch`.

**Comment by yepbug** [comment]
Thank you for your fast response, this maybe an option.
