### ISSUE TITLE
Content Type & multipart boundary ignored when using Request object

### ISSUE THREAD

**Issue by colepatrickturner** [github/fetch#473]
Hello!

I ran into this issue today where I was attempting to upload a file using `isomorphic-fetch`, which appears to use `github/fetch` polyfill. 

Uploading with the following signature will result in a content type header with multipart boundary:
```js
const headers = new Headers({ 'Accept': 'application/json' });
const body = new FormData();
body.append('myImageFile', file);
const options = { body, headers };
fetch(url, options);
// content-type:multipart/form-data; boundary=----WebKitFormBoundary5FPg0s6HB9BmL6m3
```

However, the following signature does create a `Content-Type` header at all:
```js
const headers = new Headers({ 'Accept': 'application/json' });
const body = new FormData();
body.append('myImageFile', file);
const options = { body, headers };
const request = new Request(url, options);
fetch(request);
```

I'm not familiar with the `fetch` whatwg spec, but rather just presenting an observation I've seen when comparing to the fetch implementation in Chrome 56 where one can do `fetch(request)` and the content type header will be automatically set.

Edit: Using Version 1.0.0

**Comment by mislav** [comment]
We can't provide support for `isomorphic-fetch`, since that's a different project. Are you saying that this issue comes exclusively from our code? Are you able to replicate it if you load our own `fetch.js` on the page and not the `isomorphic-fetch` project? Which browser version are you able to replicate this on?

**Comment by colepatrickturner** [comment]
Apologies, I followed the trail here but was not able to reproduce using `fetch.js` from this repo as of today. Thank you for your time.
