### ISSUE TITLE
FileError in Samsung Internet Browser

### ISSUE THREAD

**Issue by marcoow** [github/fetch#475]
**Unfortunately this is a pretty vague bug report but at this point I don't really know how to debug it better** 😞

We have an SPA that uses `fetch` (through https://github.com/stefanpenner/ember-fetch) and we're seeing a lot of `FileError`s in production, all coming from Samsung Galaxies (6 and 7). The specific error is

```
The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.
```

which seems to be related to Chrome's `FileReader` implementation (see [here](https://github.com/android/platform_external_webkit/blob/master/Source/WebCore/dom/ExceptionCode.cpp#L201) and e.g. [here](https://github.com/android/platform_external_webkit/blob/b5f8fbb89c3d48053d7e38282fd6f6aac3fdd0e6/Source/WebCore/fileapi/FileReaderLoader.cpp#L139)). This is also the only indication I have for this being related to fetch at all since the only usage of the `FileReader` API in our app bundle is within this library. Unfortunately we're not seeing any stack traces for this error in Sentry and I currently don't have an actual device to test this on.

More specifically, all of these errors (we have about 13000 events for 3000 users) are on Android 6 with Samsung Browser5.0/Chrome 51.

**Comment by mislav** [comment]
Ouch; thanks for letting us know.

Unfortunately, it's not possible to avoid using FileReader within our polyfill right now. It's automatically used whenever you call the `response.text()` method. I'm guessing that is how you're using the polyfill?

The only workaround right now that I can suggest is to trick the broken browsers into thinking that they don't have support for FileReader while the polyfill is loading:

```html
<script>
if (samsungGalax) {
  BrokenFileReader = FileReader
  window.FileReader = undefined
}
</script>
<script src="./fetch.js"></script>
<script>
if (samsungGalax) {
  window.FileReader = BrokenFileReader
  delete window.BrokenFileReader
}
</script>
```

**Comment by marcoow** [comment]
> Unfortunately, it's not possible to avoid using FileReader within our polyfill right now. It's automatically used whenever you call the response.text() method. I'm guessing that is how you're using the polyfill?

Yes, we do use `response.text()`.

> The only workaround right now that I can suggest is to trick the broken browsers into thinking that they don't have support for FileReader while the polyfill is loading:

Hadn't even though of just forcing fetch to use the Polyfill… That should fix it of course - thanks for the hint!

BTW: your code is missing semicolons :trollface:

**Comment by wichert** [comment]
@mislav I am hitting this as well. We happen to use `response.json()`, but I suspect that follows a very similar code path internally.

**Comment by nikcorg** [comment]
@wichert yep. `.json()` [invokes `.text()`](https://github.com/github/fetch/blob/048626722124b45ed7bc58ec841822610f08798b/fetch.js#L294-L296) internally.

I'm also seeing this bug manifesting itself on Chrome Mobile 38.0.1025 on Android 4.2 devices.
