### ISSUE TITLE
IE 11 SCRIPT1010: Expected identifier

### ISSUE THREAD

**Issue by btakita** [github/fetch#477]
I'm getting the error on browserstack IE 11:

SCRIPT1010: Expected identifier
fetch.min.js (1,5126)

![fetch-ie11](https://cloud.githubusercontent.com/assets/3664/23005124/8622646c-f3c8-11e6-80ae-e491222655da.png)

**Comment by btakita** [comment]
This is coming from https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.2/fetch.min.js

I'll file a ticket with them.

**Comment by Roopashree27** [comment]
I am having same issue with IE11, is any found solution for this???????????????????????????

Thanks,
In advance
