### ISSUE TITLE
`normalizeName` lowercasing case-sensitive header keys

### ISSUE THREAD

**Issue by rossettistone** [github/fetch#478]
Working on a Rails app where I'm using the following `fetch` call:

```js
fetch('/decline_modal', {
  method: 'POST',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'X-CSRF-Token': document.getElementsByName('csrf-token')[0].content,
  },
  body: JSON.stringify({
    decline_modal: 'true',
  })
})
```

When I check the Network tab in the Inspector, I see that the request headers include `x-csrf-token` (lowercase), and Rails is failing to verify the CSRF token. Making this same call with `$.ajax`, that header is in the same case as I wrote it, and Rails is successfully verifying the CSRF token. As best as I can tell, Rails is case-sensitive on that key.

Looking through `fetch.js`, it seems that the offending function is `normalizeName`, which includes `toLowerCase` in the last line. Is this necessary, or can we add a test for case-sensitivity and remove that method call?

Thanks!

**Comment by dgraham** [comment]
See #249.
