### ISSUE TITLE
Doesn't work in IE

### ISSUE THREAD

**Issue by jescalan** [github/fetch#480]
It says in the browser support section of the readme that this works in IE10+, however this is not the case. No version of IE supports native promises, and there is no substitute or polyfill for `Promise`, nor is it mentioned in any caveat that this needs to be polyfilled in order to work in IE.

So the question is -- am I missing something? Want me to PR in a readme caveat that `Promise` needs to be polyfilled in order for it to work in browsers that don't support it?

**Comment by MHanslo** [comment]
If you look at the installation section, it's explicitly mentioned you'll need to implement a promises polyfill for browsers that don't support it:

> You will also need a Promise polyfill for older browsers.

**Comment by jescalan** [comment]
Maybe it would make sense to add a note about this to the browser support section as well?
