### ISSUE TITLE
Using isomorphic-fetch in Edge

### ISSUE THREAD

**Issue by Zephir77167** [github/fetch#488]
Hi,

So this is more of a question: I have some issues using this polyfill on Edge. Reading the docs, I thought I understood it replaced the native fetch, even if it were already implemented in the browser.

So, as the fetch in Edge 14 is a bit broken, I use:
`import 'isomorphic-fetch';`
at the root of my project. But I still get the TypeMismatchError when I try to execute even the simplest fetch() under Edge... Works like a charm under Chrome & Mozilla though.

Any insights?

Thanks in advance.

**Comment by dgraham** [comment]
> I understood it replaced the native fetch, even if it were already implemented in the browser.

The polyfill code is [active](https://github.com/github/fetch/blob/eebaa2a1bc21eeba98ee00c9f94a0a4c2007cff1/fetch.js#L4-L6) only in browsers that do not provide a native implementation.

> So, as the fetch in Edge 14 is a bit broken

If the thing that is broken hasn't already been [reported](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?page=1&q=fetch), you might open an issue with the Edge team.

>  I use: import 'isomorphic-fetch';

This question is best asked in the [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) repository.

**Comment by kairi1227** [comment]
see: https://github.com/matthew-andrews/isomorphic-fetch/issues/123
