### ISSUE TITLE
Make use of responseType=blob conditional

### ISSUE THREAD

**Issue by vdonich** [github/fetch#490]
At the moment, the polyfill sets `responseType='blob'` unconditionally.
However, for the purpose of using `<link rel="preload"` for non-blob responses, the above responseType shouldn't be set in some cases.

I'm not sure which way is the best, maybe adding a responseType to supports object and then exposing it for modification on fetch similarly to `polyfill = true` would make sense?

**Comment by dgraham** [comment]
Related to, and possible duplicate of, #481.

**Comment by boubechtoula** [comment]
t

**Comment by JakeChampion** [comment]
Since https://github.com/github/fetch/pull/752 was merged, we no longer unconditionally set the responseType to blob.

I'll close this issue as I believe it is now resolved. If it is still an issue please comment and I will reopen and investigate :-)
