### ISSUE TITLE
how to use websocket with fetch?

### ISSUE THREAD

**Issue by Yankj** [github/fetch#499]
do you have a API for using websocket with fetch?

**Comment by dgraham** [comment]
You'll need to use the [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) API rather than `window.fetch`. Fetch is a request/response protocol like XMLHttpRequest.

**Comment by queequac** [comment]
Nevertheless a valid question. I asked myself also: For what reason does fetch specify a [websocket protocol](https://fetch.spec.whatwg.org/#websocket-protocol) if you cannot use the fetch API on top?

**Comment by dgraham** [comment]
Looks like https://github.com/whatwg/fetch/issues/235 is the entry point to the WebSocket discussion.
