### ISSUE TITLE
`catch` does not contain response object or response status `TypeError: Failed to fetch`

### ISSUE THREAD

**Issue by sndsgn** [github/fetch#501]
A get request response with a 401 response status seems to only allow you to `catch` the error  and the information provided is the following. `TypeError: Failed to fetch`.
In `catch` one does not appear to have access to the response object or status.

**Comment by matt-mcdaniel** [comment]
I have the same issue @sndsgn, did you resolve this?

**Comment by sndsgn** [comment]
I can't tell if this was done intentionally for security purposes to not expose the reasoning or response. However, I still believe the response status code should be provided in the catch. I will reopen as it's also an issue for you.

**Comment by dgraham** [comment]
See #201 for past discussion.
