### ISSUE TITLE
	TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by RameshTanugula** [github/fetch#508]
Am getting the 	TypeError: NetworkError when attempting to fetch resource.  error after passing  the api ,

anyone  can please solve my problem...

**Comment by dgraham** [comment]
There isn't enough detail provided in this issue for us to help. [StackOverflow](https://stackoverflow.com/) is a better forum for usage questions. This issue tracker is used for reporting bugs in this implementation of fetch.
