### ISSUE TITLE
Missing import statement

### ISSUE THREAD

**Issue by darakt** [github/fetch#509]
Hi,
I'm doing a react project, and I wanted to use fetch for my API calls.
But I'm getting a missing import statement...
Here a snippet:

```js
import 'whatwg-fetch';

export default () => {
    if ( $('#form1').parsley().isValid()) {
        fetch('https://smt/api/auth/login/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
            },
            body: JSON.stringify({
                "username": "x",
                "password": "y",
            })
        }).then((response) => {
                console.log(response.json());
        })
    }
    $('#form1').parsley();
    console.log('end login');
}
```

I installed fetch through "npm install whatwg-fetch --save" and if I tried ctrl + click on the import I'm getting a file fetch.js.

**Comment by dgraham** [comment]
The `window.fetch` function is a global provided by the browser so there isn't anything to import. If you're using fetch in a Node.js server, you can use [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch).
