### ISSUE TITLE
Run test suite under Worker contexts

### ISSUE THREAD

**Issue by josh** [github/fetch#51]
It'd be great to run all the same document tests under a worker context as well.

QUnit is a bit of a let down for making this happen. I'd be open to other test runners assuming its simpler overall.

Testing Service Worker context may be interesting too. I'm not sure how many differences there would be from a generic web worker context. `fetch` is at least enabled by default for SW when it might not be for a regular worker.

/cc @dgraham @matthew-andrews @domenic @knowledgecode

**Comment by matthew-andrews** [comment]
Shouldn't `fetch` already be defined in the Service Worker context?  (or would this be a test to check that the polyfill doesn't enable itself in SW?  If it's to run this test suite in SW then I think that's a useful thing to have but probably out of scope of this library?)

A little Googling suggests that phantom js supports web workers though: https://github.com/ariya/phantomjs/issues/10257

At FT we use Mocha, Karma & Chai and they're a massive improvement from [buster](http://docs.busterjs.org/en/latest/) but not used qunit so not sure how it compares.

**Comment by josh** [comment]
> Shouldn't fetch already be defined in the Service Worker context?

Yeah, that validates that are test suite actually matches the real implementation.
