### ISSUE TITLE
Browser support documentation does not detail mobile browser support

### ISSUE THREAD

**Issue by svodnik** [github/fetch#510]
Looking at the caniuse stats for Fetch (http://caniuse.com/#search=fetch), mobile browsers are the big sticking point right now. However, your documentation seems to provide details only for desktop browser support. It would be helpful if you could add support information for iOS Safari, Android Browser, UC, and Opera Mini to provide a complete picture of the browser support landscape when using this polyfill.

**Comment by dgraham** [comment]
We'll need your help building this list because we don't use fetch on mobile. There is more discussion in https://github.com/github/fetch/issues/183.

It should work fine on mobile with a Promise polyfill, but we don't have data from our own experience to know for sure.
