### ISSUE TITLE
Miss space between content-type and boundary  on iOS 10.3.1

### ISSUE THREAD

**Issue by zhaoyihong** [github/fetch#511]

**Comment by zhaoyihong** [comment]
When I post formdata ,I found that  there is no space before boundary.
For example : content-type multiparty/form-data;boundary=-----Webkit.....

**Comment by dgraham** [comment]
We use XMLHttpRequest to perform the request, so you might try using that directly to see if it fixes the problem. We don't set multipart content types in this library, relying on XMLHttpRequest to handle that header value.
