### ISSUE TITLE
ReactJs - Whatwg fetch error on IE

### ISSUE THREAD

**Issue by vuinguyen911** [github/fetch#512]
![whatwg_fetch_error_ie_11 0 9600 17031](https://cloud.githubusercontent.com/assets/4546929/25738002/ed133cea-31a4-11e7-9243-695a753dc77b.png)
<img width="761" alt="solution_fixbug_on_ie" src="https://cloud.githubusercontent.com/assets/4546929/25738058/39a7c47c-31a5-11e7-8655-3f06ba1f06f1.png">

Dear,
I found this error IE version 11.0.9600.17031, I suggest solution as image.
Add this code:   var Promise = require('es6-promise').Promise; at line 7 of file.

**Comment by dgraham** [comment]
Loading a Promise polyfill is outside the scope of this project. Fetch requires Promise to be available in the browser either natively or from one of several polyfills. We leave it up to you to [load a Promise library](https://github.com/github/fetch/#installation) for fetch to use.

**Comment by vuinguyen911** [comment]
Ok tks so much.
