### ISSUE TITLE
Promise is being rejected on a 403 response

### ISSUE THREAD

**Issue by cadejscroggins** [github/fetch#513]
Is there any reason why this would be happening? I can't get to the JSON in the response because fetch isn't resolving. Looking at the request I am clearly getting a 403 with a JSON response.

**Comment by dgraham** [comment]
There isn't enough detail in this issue for us to be able to help. If this is a cross-origin request, the preflight request might be rejected with the forbidden response. You might read through [past CORS issues](https://github.com/github/fetch/issues?utf8=✓&q=is%3Aissue%20cors) to see if any match the behavior you're seeing.
