### ISSUE TITLE
no response data available when add headers

### ISSUE THREAD

**Issue by FTAndy** [github/fetch#514]
In Chrome latest version 58.0.3029.96, I set fetch headers like this:

```javascript
    headers: {
      'token': token,
      'Content-Type': 'application/json'
    }
```
even if
```javascript
    headers: {
      'asd': 'asd',
    }
```

Then in Chrome dev tool Network panel, the request will not show any response data, and say 'This request has no response data available'.

But in Safari, response data shows up. Is this a fetch problem or Chrome problem?

**Comment by dgraham** [comment]
Sending custom headers on a cross-origin request requires an OPTIONS preflight request that allows those headers from the server. You might check past [CORS questions](https://github.com/github/fetch/issues?utf8=✓&q=is%3Aissue%20cors%20) for more information.
