### ISSUE TITLE
how to test json response laravel

### ISSUE THREAD

**Issue by developerMerna** [github/fetch#515]
I have function return JSON
 
```php
return response()->json([
            'status' => 'OK',
            'data' => [
                'id' => $routeForecast->id,
            ],
        ])
```

how can I make test for this .. my laravel version is 5.1 and i used assertJson([ ]) it give me this error
***** PHPUnit_Framework_Exception: Argument #1 (No Value) of PHPUnit_Framework_Assert::assertJson() must be a string
and try seeJson it give me this error 
***** Invalid JSON was returned from the route. Perhaps an exception was thrown?
HOW CAN I SOLVE IT ??

**Comment by dgraham** [comment]
This looks like a PHP issue rather than related to `window.fetch` JavaScript. You might ask this question, with more details included, on [StackOverflow](http://stackoverflow.com).

**Comment by mayrop** [comment]
For version 5.1 you should use `seeJson` and not `assertJson`. See: https://laravel.com/docs/5.1/testing
