### ISSUE TITLE
fetch doesn't work in ios9 safari

### ISSUE THREAD

**Issue by ilijian** [github/fetch#524]
I fired a POST fetch in my code, and it works well in Mac chrome and firefox and safari, but it failed to get me any response in ios9 safari. Debug shows that no fetches were fired at all. Can anybody help me? Below is how my codes look like

```js
fetch('//some/url', {
  method: 'POST'
})
.then(function(res) {
  return res.json();
})
.then(function(response){
  console.log(response);
  that.rapMsg = response.msg;
})
.catch(function(error) {
  console.log(error);
  alert('Something goes wrong!');
});
```

**Comment by dgraham** [comment]
I don't know how to help with this specific error, but you can try debugging in the Xcode iOS Simulator and Safari.

1. Start the simulator and open the page in iOS Safari
2. Select Develop > Simulator in macOS Safari
3. A macOS Safari development tools window appears containing any error messages in the console

#### macOS Safari menu

![screen shot 2017-05-26 at 11 50 38](https://cloud.githubusercontent.com/assets/122102/26506462/fa14418a-4209-11e7-8ec6-ce0083edf0d3.png)

#### Web inspector connected to the iOS Safari simulator

![screen shot 2017-05-26 at 11 51 54](https://cloud.githubusercontent.com/assets/122102/26506463/fa2a7a5e-4209-11e7-81df-55d228450781.png)

**Comment by Wonderfour** [comment]
How to solve?
