### ISSUE TITLE
polyfill FormData

### ISSUE THREAD

**Issue by Nemo64** [github/fetch#525]
There is already a polyfill for headers which works similarly.
There should also be a polyfill for the `FormData` object.
Sending files wouldn't work easily but other than that it should be possible to build the post body manually.

~I just noticed that the official browser support is IE10+, this would be a fix for IE9. Other than this problem it seemed to work fine in IE9.

**Comment by dgraham** [comment]
A FormData implementation, like Promise and URLSearchParams, is outside the scope of this project. The Headers class is implemented as part of the Fetch specification.

**Comment by jimmywarting** [comment]
I have built a [FormData polyfill](https://github.com/jimmywarting/FormData) That you could use
