### ISSUE TITLE
don't support chrome devtool network preview

### ISSUE THREAD

**Issue by cjd6568358** [github/fetch#529]
chrome 58

![image](https://cloud.githubusercontent.com/assets/3970494/26712676/a5cad56c-479a-11e7-9430-c2553da872ab.png)
![image](https://cloud.githubusercontent.com/assets/3970494/26712698/cb612646-479a-11e7-90fa-28b59d8355a1.png)
![image](https://cloud.githubusercontent.com/assets/3970494/26712707/dd13bf2a-479a-11e7-8552-c3c2c8270e6d.png)
when i use ajax it works

**Comment by dgraham** [comment]
The fetch JavaScript code from this repository isn't active in Chrome because the browser has a native implementation. So this is a question for the Chrome team.

**Comment by cjd6568358** [comment]
@dgraham no. i  disabled native fetch object for window.fetch = null,so it is nothing  with them.
![image](https://cloud.githubusercontent.com/assets/3970494/26753158/c44e0308-4892-11e7-9794-e71cb4bc4517.png)
this is test url: https://m.haomaiche.com/sh

**Comment by cjd6568358** [comment]
@dgraham You will only close issue or the description is not clear ?  here is test url: https://m.haomaiche.com/sh ,and i can't preview response body with your fetch ployfill
