### ISSUE TITLE
don't support chrome devtool network preview

### ISSUE THREAD

**Issue by cjd6568358** [github/fetch#530]
@dgraham no. i disabled native fetch object for window.fetch = null,so there is really a bug.
image
![c44e0308-4892-11e7-9794-e71cb4bc4517](https://user-images.githubusercontent.com/3970494/26909508-dcf189b2-4c33-11e7-89d4-0a914bd67478.png)

this is test url: https://m.haomaiche.com/sh

**Comment by dgraham** [comment]
There just isn't enough information here or in #529 for us to help with browser development tools.
