### ISSUE TITLE
Timeline for next release?

### ISSUE THREAD

**Issue by ericvicenti** [github/fetch#531]
Hi, when can we expect the next release?

At Facebook we're blocked because React Native has had/will have the ability to switch the default of `XMLHttpRequest.sendRequest({withCredentials`, and the current release of fetch assumes that withCredentials defaults to false.

This was fixed in https://github.com/github/fetch/commit/9a0c992f4c79f2050b928ed9ad62689db525c200

**Comment by mislav** [comment]
I can cut a new release easily, but if this is needed for React Native compatibility, then maybe you can help me clear one more thing out that is supposed to help with React Native: https://github.com/github/fetch/pull/521#issuecomment-307805318

Doesn't React Native support `fetch` natively? How come the polyfill is needed?

**Comment by ericvicenti** [comment]
React Native's approach is to implement APIs that are available on web browsers, such as XMLHttpRequest. The fetch API is provided with this polyfill, but not 'natively'.

I agree that things may be more simple if RN had a direct fetch implementation. I assume this decision was made for compatibility with browser libraries that expect XMLHttpRequest to exist.

**Comment by supermoshen** [comment]
看不懂

**Comment by shofian05121992** [comment]
api help me

**Comment by shofian05121992** [comment]
328140484

**Comment by dgraham** [comment]
https://github.com/github/fetch/releases/tag/v2.0.4
