### ISSUE TITLE
browser-support for IE has some error data!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [github/fetch#532]
# browser-support  for IE has some error data!

> please update it!

https://github.com/github/fetch#browser-support

## caniuse

https://caniuse.com/#search=fetch
![ie-fetch-error](https://user-images.githubusercontent.com/18028768/27010308-d9483822-4ed3-11e7-8df8-367a0062d027.png)

##  IE 11 tested

![fetch-ie11-error](https://user-images.githubusercontent.com/18028768/27010290-8374a7be-4ed3-11e7-844f-a719ef686747.png)

**Comment by dgraham** [comment]
IE 11 does not have a native implementation of `window.fetch`, which is what caniuse.com is reporting. This repository provides a JavaScript implementation of `fetch`, allowing you to use it in IE 11.

**Comment by xgqfrms-GitHub** [comment]
SO, how can i use fetch in IE11 ?

Using some polyfill libs ?

Could you show me a demo ?

I'm looking forward your early reply, and thanks in advance!

**Comment by mislav** [comment]
This project **is** a polyfill for `window.fetch`. The way to use it is to [obtain the `fetch.js` file](https://github.com/github/fetch#installation) from this project and load it together with your site's JavaScript. Then you can use `fetch()` function even in browsers that don't yet support it natively.

**Comment by xgqfrms-GitHub** [comment]
Thanks for your time!
