### ISSUE TITLE
how do i send raw request body content with fetch

### ISSUE THREAD

**Issue by biks152207** [github/fetch#535]
I have a api in asp.net and it expects raw body content like [1:1:1]. I need to send it to server. The content-type is application/json.Guys how can i send raw body content with fetch.

**Comment by mislav** [comment]
First, I want to point out that `[1:1:1]` is not valid JSON.

However, you can send any kind of body content with fetch. Just do this:

```js
fetch(url, {
  method: 'POST',
  body: myBodyContent,
  headers: { "Content-type": myContentType }
}
```

Just change the values of `myBodyContent` and `myContentType` to anything that you want.

**Comment by chovy** [comment]
what header do i need?
