### ISSUE TITLE
Empty response is not able parse

### ISSUE THREAD

**Issue by zhaoruda** [github/fetch#537]
when _bodyText is '' (empty string),  it will be error in this code:
    this.json = function() {
      return this.text().then(JSON.parse)
    }

As JSON.parse('') is not valid.

Now, I do like this in my code base:
   const parseJSON = response => response.text().then(
        text => (text ? Promise.resolve(JSON.parse(text)) : Promise.resolve())
);

**Comment by dgraham** [comment]
See #378.
