### ISSUE TITLE
Explorer issue

### ISSUE THREAD

**Issue by BnayaZil** [github/fetch#541]
In the browser compatibility table, you claim to support Explorer 10+ but Explorer is not supporting promises((see table)[http://caniuse.com/#feat=promises]) and fetch did use promises.

Did I miss something?
I would like to contribute fix if you want.

**Comment by dgraham** [comment]
https://github.com/github/fetch#installation

**Comment by BnayaZil** [comment]
@dgraham I think it's not right to presenting like the library supporting some browser versions and then in the installation instructions to instruct to use polyfills, using polyfills are not part of the library support and it's funny because with polyfills I can use ES2016 features in Internet Explorer 8 which obviously not really supported in Internet Explorer 8.
So as I see it, If the library aims to support Internet Explorer 10+  with promises we should include promises polyfill in the library If you guys think it's more important to keep the library small and not to include the unrelated code of promises polyfill you should change the compatibility table.
