### ISSUE TITLE
Force polyfill

### ISSUE THREAD

**Issue by qraynaud** [github/fetch#544]
I would like to be able to force the polyfill to replace the native implementation for the time being. Would it be possible to do that?

My reason is that I found Fx & Chrome disagreeing on part of my implementation and would like to get everything straight and hope the polyfill will do just that (though I'm not sure it will).

I know this is not the place to discuss specific browser bugs on their particular implementation of the spec. I'm only asking for a way to get it to replace the native implementation of Firefox. A way would be to expose a function that applies the polyfill. It would be autoinvoked when window.fetch is undefined but could be invoked manually if deemed useful.

As an aside note, to clarify my problem, I do a fetch, get the result accordingly, then look in my debug tools with Fx, see that the server returned a `Content-Range` header as part of its response to my request with a value of `objects 0-9/45` but when I do a `result.headers.get('Content-Range')` the function call returns me `objects 0-9/66` (same use case gets me `objects 0-9/45` as required on Chrome). This is a pain since this totally breaks my pagination that is relying on this header!

**Comment by qraynaud** [comment]
I just tried to manually comment this block from `fetch.js`:

```js
if (self.fetch) {
  return
}
```

and it resolved my issue on Firefox as I thought it might.

**Comment by mislav** [comment]
You can force the polyfill like so: https://github.com/github/fetch/issues/180#issuecomment-122972351
