### ISSUE TITLE
upload file name contain chinese ,  server side  revice garbled

### ISSUE THREAD

**Issue by lisuiheng** [github/fetch#552]
here is my code,upload file with FormData and fetch
```
 const files = document.getElementById('upload-file').files;
 let data = new FormData();
  data.append('file', files[0]);
  const options = {
    method: 'POST',
    body: data,
  };
 call(request, requestURL, options);
```
the upload request pay load:
------WebKitFormBoundarywbyScAgYBxVrXMQN
Content-Disposition: form-data; name="file"; filename="李.txt"
Content-Type: text/plain
------WebKitFormBoundarywbyScAgYBxVrXMQN--

but in the server side, I get the file name is '?.txt'

If I use XMLHttpRequest with this line, the server side get ok.
`xhr.overrideMimeType("text/plain; charset=utf-8");`

I doubt the 'Content-Type: text/plain' is the reason, but how can I change it

**Comment by mislav** [comment]
Thanks for reporting.

This might either be a bug with the brower's `fetch` implementation (note that most browsers implement a native `fetch` these days!) or a case of some missing encoding declaration somewhere when constructing the request. Either way, **this doesn't look like it's a bug with our polyfill**, but please feel free to add additional info and reopen this issue if you're convinced that this is a bug in this project's code.

If the manual approach with XMLHttpRequest works for you, then I suggest that you stick with an approach that works.
