### ISSUE TITLE
#blob and #arrayBuffer methods don't work on Android 4.2.2 Samsung Galaxy S2 built-in browser

### ISSUE THREAD

**Issue by NeverwinterMoon** [github/fetch#555]
So, I have something like this:

```
fetch(myRequest)
.then(function(response) {
  return response.blob();
})
```

The browser in questions (Samsung Galaxy S2 with Android 4.2.2 built-in browser) fails on `response.blob()` part. I've tried with `response.text()` and `response.json()` and this worked fine. But I do need a blob. I haven't investigated any further, so I can't provide any more details, but if needed, I can try to do that.

Oh, and I saw the browser support list. This browser is clearly not listed, but still...

**Comment by mislav** [comment]
> The browser in questions (Samsung Galaxy S2 with Android 4.2.2 built-in browser) fails on `response.blob()` part.

In browsers that don't support Blobs, `response.blob()` will be unavailable. This is by design and can't be worked around, since the browser doesn't support Blob.

https://github.com/github/fetch/blob/9a0c992f4c79f2050b928ed9ad62689db525c200/fetch.js#L240-L241
