### ISSUE TITLE
Use in node - documentation

### ISSUE THREAD

**Issue by mitra42** [github/fetch#561]
Using this in node was really counterintuitive, especially if you want to make code that is compatible between browsers and node. 

Note that fetch requires xmlhttprequest, but doesn't have the dependency in the code. 

By trial and error - the best I got was 
```
$ npm install whatwg-fetch --save
$ npm install xmlhttprequest --save
$ node
> const fetch = require('whatwg-fetch').fetch;
> const XMLHttpRequest = require('xmlhttprequest');
> fetch('https://github.com').then((req) => console.log(request.status))
should result in Promise { <pending> } and then 200
```
If part of the intent is to support use in environments like node it might be good to document, as there is an undocumented dependency, and the requires have to be done in two different ways to make this work.

**Comment by dgraham** [comment]
You might try [matthew-andrews/isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch).

**Comment by mitra42** [comment]
Thanks, I found https://github.com/npm/node-fetch-npm which also has a more complete implementation of fetch (e.g. support blob()). 

I think it is worth pointing people in the ReadMe - as I wasted a bunch of time thinking this was the canonical solution to the lack of fetch in node,

**Comment by mislav** [comment]
Our [Readme already points out](https://github.com/github/fetch#read-this-first) that this library is meant to be used in browsers, not under Node.js. We avoided officially recommending any 3rd-party project that provides `fetch` under Node because we have no experience with any of those projects, therefore we can't vouch for them.

**Comment by mitra42** [comment]
Understood - thanks
