### ISSUE TITLE
Request Header Cookie is incorrect

### ISSUE THREAD

**Issue by avivash** [github/fetch#563]
I'm wondering if anyone has come across this before...

I'm running a small React app within a `java`/`jsp` project. I'm using `fetch` to handle all the requests I'm making to the backend, but it's not working as expected. 

When I make a `GET` request, everything works fine, but, when I make a `PUT`/`POST` request using the `credentials: include` property, the wrong `Cookie` is included in my Request Header...

This is the `Cookie` being included in the Request Header:
![image](https://user-images.githubusercontent.com/1179291/30464654-a9d68c52-9987-11e7-85c9-1e68bda91ba0.png)

and this is the cookie value I see if I `console.log` `document.cookie`: 
`JSESSIONID=node01a1mh3bo89u80h9095lq4zwcu0.node0; gateaugage=5dcc5483-c5ec-4356-b3af-303e9eda105d`

The cookie I need to include in my request is the `gateaugage` one, but for some reason it's not being added.

Is there any way to manually specify the cookie I want to add or does anyone know of another way around this issue?

Thanks in advance

**Comment by mislav** [comment]
@avivash Neither our polyfill nor the native `fetch` API has any facilities for dealing with individual cookies. Instead, all cookie handling is left to the browser's internal implementation. Cookie handling depends on the hostname and path with which the initial `Set-Cookie` was configured, and by CORS headers (if you're making a request to another domain/port number).

So, if you're noticing a missing cookie, your task is to check all these configuration aspects, and there's not anything we can do from this polyfill to "fix" this behavior.
