### ISSUE TITLE
can't parse json when fetch a cros request!

### ISSUE THREAD

**Issue by aqnaruto** [github/fetch#566]
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data.

**Comment by aqnaruto** [comment]
test

**Comment by aqnaruto** [comment]
test

**Comment by aqnaruto** [comment]
test

**Comment by aqnaruto** [comment]
above , i post the 【test】
by using code
`fetch('https://github.com/github/fetch/issue_comments',{
        method: 'post',
        mode: "no-cors",
        credentials:'include',
        headers: {
            "Content-type": "application/x-www-form-urlencoded; charset=UTF-8",
        },
        body:"utf8=%E2%9C%93&authenticity_token=7SZ%2BP7E2MrlLu6dx%2FG6X39f2Mv3apvtCtzEYKsIJdSRYGi1%2FB4bD5OTJ8%2B01B8RuNCLL0EIrMt0rQtpfOvgyWA%3D%3D&issue=566&saved_reply_id=&comment%5Bbody%5D=test"
    }).then(function (response) {
        console.log(response);
        response.json().then(function(json){console.log(json)})
    });`

but,can't parse json
![default](https://user-images.githubusercontent.com/9067159/31224296-e98b882e-a9ff-11e7-8da8-af40919f388a.png)

**Comment by dgraham** [comment]
The URL you've posted to returns an HTML response rather than JSON. The response body is viewable in the browser's Network developer tools. You can also see it with:

```js
fetch(…).then(response => response.text()).then(text => console.log(text))
```

Please don't use the `/issue_comments` URL for testing. It sends an email to everyone subscribed to this repository.

**Comment by aqnaruto** [comment]
test
