### ISSUE TITLE
Fetch sometimes catch a JSON parse error, sometimes it's not

### ISSUE THREAD

**Issue by justinushermawan** [github/fetch#573]
I'm working on a React Native application, which fetches an API response from a server. Sometimes, it returns success, but sometimes it catches an error.

The following code is my fetch function:

```js
export default async (url, body = null, method = 'GET') => {
    let config = {
        method,
    };
    return await fetch(url, config).then((response) => {
        if (!response.ok) {
            throw Error(response.statusText);
        }
        return response.json();
    }).catch(error => {
        console.warn(error); // sometimes it was catched in here
    });
};
```

It was returning various error messages, e.g:

> [SyntaxError: JSON Parse error: "\u302\" is not a valid unicode escape]
> [SyntaxError: JSON Parse error: Invalid escape character 
> [SyntaxError: JSON Parse error: "\u740\" is not a valid unicode escape]
> Unexpected end of json input
> [SyntaxError: JSON Parse error: Unexpected character '}']
> etc.

Here's a sample of JSON output: https://pastebin.com/vduDQJ8g

I'm already checked my API response through the browser and it didn't find anything wrong with the response. Is there any bug on `fetch` function so the fetched response is not complete?

**Comment by dgraham** [comment]
Unicode escape sequences in [JSON](http://json.org) are defined as `\u` with four hexadecimal digits following.

One way to debug this is to print the value of `response.text()` rather than passing it through the JSON parser.

The mix of `then` and `async/await` can be simplified to this:

```js
export default async (url, body = null, method = 'GET') => {
  let config = {
    method,
  };
  try {
    const response = await fetch(url, config);
    if (!response.ok) {
      throw new Error(response.statusText);
    }
    return await response.json();
  } catch (error)
    console.warn(error);
    throw error;
  }
};
```

**Comment by justinushermawan** [comment]
@dgraham I've already debugged and it seems returning an incomplete JSON like this: https://pastebin.com/tE4iYfbc, so the JSON parse was error. Is it a problem on mixing of async/await & fetch?

**Comment by mislav** [comment]
> Is it a problem on mixing of async/await & fetch?

The result of `fetch`, like any `then`-able result, is compatible with `async/await`. The reason @dgraham suggested a slightly different approach was to eliminate the `await..then` construct that you had in your example, which made your code difficult to read.
