### ISSUE TITLE
Response contructor is incompatible with other browser implementations

### ISSUE THREAD

**Issue by spearmootz** [github/fetch#576]
if you use new Response directly and use 204 responses you get the following issue.

`new Response('', Init)`
fails on chrome because it expects no body. you can do

`new Response(null, init)`
fails on Firefox because body cannot be null

but you can do in both firefox, chrome, Edge, safari
`new Response(init);`

but that fails when using this polyfill.

**Comment by spearmootz** [comment]
i get around it with the following code.

```const polyfilled = fetch.toString().includes('XMLHttpRequest');
if (polyfilled) {
  const getClassOf = Function.prototype.call.bind(Object.prototype.toString);
  const isClassOf = (instance, className) => getClassOf(instance).split(' ')[1].includes(className);
  const PolyfilledResponse = window.Response;
  window.Response = (first, second) => {
    if (isClassOf(first, 'Object')) {
      return new PolyfilledResponse(null, first);
    }

    return new PolyfilledResponse(first, second);
  }
}```

**Comment by mislav** [comment]
Thanks for reporting! In the meantime, I think you can use `new Response(undefined, {status: 204})` as a workaround in your app. It's a shame null doesn't work in Firefox; is this known to Mozilla?

**Comment by spearmootz** [comment]
so my original assumption that doing new Response(options) works on other browsers. it actually returns a response that is a 200, no matter if you did 204 or 400. so it will always be resp.ok

**Comment by dgraham** [comment]
Reopening to track updating our `Response` constructor to match the [specification changes](https://fetch.spec.whatwg.org/#response-class).

We need to handle the optional first `BodyInit` argument here.

https://github.com/github/fetch/blob/7a692dc519a3a110526a26c7e252f99991510c2a/fetch.js#L377-L380
