### ISSUE TITLE
bower install failing

### ISSUE THREAD

**Issue by c256985** [github/fetch#578]
When I try a bower install of fetch, I get the following error message:

```
 Request to https://registry.bower.io/packages/fetch failed with ECONNRESET, retrying in 1.9s
```
I can install other packages without any problems.

**Comment by mislav** [comment]
We're not sure why is that, but this doesn't sound like something that we can solve, and is instead a problem with Bower itself. We recommend using npm to download `whatwg-fetch` over other package managers.
