### ISSUE TITLE
can't write cookie in Internet Explorer 11

### ISSUE THREAD

**Issue by drinkingcode** [github/fetch#579]
in response header from server, we can see as following:

 Set-Cookie: connect.sid=s%3A1phQheuQw8BsEtl-TTNUta6JtbZhFOxs.YYbD3kdg%2B3%2FIOS9HjjGZhoNtJagNT%2B9a4x9nHaq6WYY; Domain=localhost; Path=/; Expires=Thu, 26 Oct 2017 09:09:29 GMT; HttpOnly

But we can't see anything  in cookie list of Internet Explorer 11 . 
At the same time, other browsers（chrome and fireifox）work fine with cookie,  so what it happened ,
Anyone else meet the same problem ?

**Comment by mikkelwf** [comment]
I'm having trouble with IE11, but only in my dev-env (running IE11 on Win7 through Parallels).. 
Our staging/production works fine..

**Comment by mikkelwf** [comment]
@drinkingcode ^^

**Comment by drinkingcode** [comment]
@mikkelwf  credentials: 'same-origin'
