### ISSUE TITLE
fetch response in IE 11 does not contain right info

### ISSUE THREAD

**Issue by idavollen** [github/fetch#581]
It seems that window.fetch polyfill in IE 11 doesn't return the same info (https://developer.mozilla.org/en-US/docs/Web/API/Response)  as other browsers, i.e. Chrome when there happens a redirect in ajax call.

In the same scenario, 
```
Chrome and Firefox returns such Response js object info:
Response {type: "basic", url: "http://localhost:8080/authfailed", redirected: true, status: 200, ok: true, …}

But IE 11 returns totally different Response js object:

[object Object]{_bodyBlob: Blob {...}, _bodyInit: Blob {...}, bodyUsed: false, headers: Object {...}, ok: true, status: 200, statusText: "OK", type: "default", url: ""}

```
Can someone shed the light on how to force IE 11 to return the same fetch Response as other browsers?

Thanks in advance!

**Comment by dgraham** [comment]
https://github.com/github/fetch#obtaining-the-response-url

**Comment by greggilbert** [comment]
@dgraham: sorry to ping on this old issue, but I'm seeing the same as @idavollen when the response is a 302 redirect. Returning a 200 populates `response.url` properly, however.

**Comment by jacklee814** [comment]
@dgraham Can i get redirected status in Response?
