### ISSUE TITLE
Q: How can I make a HTTPS to the backend with a self-signed certificate?

### ISSUE THREAD

**Issue by uynap** [github/fetch#585]
I use the HTTPS backend with a self-signed certificate. I need to tell the HTTP client(fetch) to skip checking the insecure certificate. Otherwise I'm getting "x509: certificate signed by unknown authority" error.
As I didn't find any related topics in the documentation. I was wondering what would be your solution or workaround for my situation?

**Comment by dgraham** [comment]
TLS certificates are handled by the browser without exposing them to `XMLHttpRequest` or `fetch`. So you'll need to customize your browser settings to change TLS negotiation behavior.
