### ISSUE TITLE
Testing fails with chai v4.x

### ISSUE THREAD

**Issue by ghisvail** [github/fetch#594]
See [Debian-Bug#884154](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884154)

**Comment by chrismusselman** [comment]
i think the  comments are key to success

**Comment by ghisvail** [comment]
> i think the comments are key to success

What do you mean?

**Comment by arunasank** [comment]
I don't see any tests failing, when I upgrade chai to 4.1.2 on https://github.com/github/fetch/pull/597. What tests are failing?

**Comment by ghisvail** [comment]
@arunasank Please read the link to the Debian bug report. The complete log is provided.

**Comment by arunasank** [comment]
```
arunasank:fetch aruna$ npm test

> whatwg-fetch@2.0.3 test /Users/aruna/git/fetch
> make

./node_modules/.bin/jshint *.js test/*.js
./script/test


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․ArrayBuffer is deprecated in XMLHttpRequest.send(). Use ArrayBufferView instead.
․․․․․․․․․․․․․․․․․․․․․․․․․

  118 passing (1s)
  9 pending

ArrayBuffer is deprecated in XMLHttpRequest.send(). Use ArrayBufferView instead.


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  112 passing (21ms)
  15 pending
```

@ghisvail ok, thank you for that. The above is the output when I run the tests on my mac. Why are some tests still in `pending` state? How can I run these?

**Comment by mislav** [comment]
In #626 we've upgraded Mocha and Chai and all tests pass in all supported browsers.

Please provide more info if something fails. Note that the testing setup has been reconfigured from the ground up. See https://github.com/github/fetch/blob/master/CONTRIBUTING.md
