### ISSUE TITLE
how to set the timeout of each request?

### ISSUE THREAD

**Issue by withinoneyear** [github/fetch#596]
since xhr is not exposed

**Comment by dgraham** [comment]
It's not currently possible but will be with `AbortController`.

- https://github.com/github/fetch/search?q=timeout&type=Issues&utf8=✓
- https://github.com/whatwg/fetch/issues/20#issuecomment-323740783

**Comment by ianstormtaylor** [comment]
FWIW, I've opened an issue https://github.com/whatwg/fetch/issues/951 with a proposal for a `timeout` option that solves 90% of use cases, in case anyone's interested. I think it's super important to add to make sure calls to `fetch` (or `res.json()`) don't hang indefinitely.
