### ISSUE TITLE
Access to a API rest with https autosigned certificated

### ISSUE THREAD

**Issue by diegoceldranmorell** [github/fetch#598]
Hi, i have a problem, i need to make fetch request to an api rest located in a server with a invalid https certificate, we use https, but with a autosigned certificate, when i try to make the request i have a TypeError: Network request failed, i can make it via curl from my pc, but i CAN'T make anything with fetch in Android, i've not tested it in iOS, but i need it works in both platforms, please, it's really important, i CAN'T change the ssl server certificate, i only can modify mi mobile app made in react-native. Please, help me, i can't find any valid solution...
![image](https://user-images.githubusercontent.com/11218421/35388873-d90353be-01d5-11e8-831a-dc173c8e3328.png)

**Comment by dgraham** [comment]
The Fetch and XMLHttpRequest APIs don't have control over the TLS phase of the network connection, so there is no way to alter certificate handling. Establishing an encrypted connection is handled by the browser.
