### ISSUE TITLE
IE11: not posting FormData correctly if request has 'Content-Type' set

### ISSUE THREAD

**Issue by RefX32** [github/fetch#599]
This works in IE11:

```
var request = { 
  method: 'POST', 
  body: new FormData(document.getElementById('ContactUsForm')),
  credentials: 'same-origin',
  mode: 'no-cors',
  cache: 'default' 
};
fetch('/Company/SubmitContactUs',  request);
```
However, when I add 'Content-Type', like below:
`if (options.isJson) { request.headers = { 'Content-Type': 'application/json' }; }`

It does not get picked up correctly by my back end application (ASP MVC Core). Basically, nothing binds correctly. 

This works in all other browsers, including Edge. The only browser with the problem is IE11 (and probably below).

Doing `request.headers = { 'Content-Type': null };` also causes it to not work. However, without any content type, it works well. 

POST result:
Without setting "Content-Type" 
`Content-Type: multipart/form-data; boundary=---------------------------7e23621391bde`

After setting "Content-Type" to json (Not working)
`content-type: application/json, multipart/form-data; boundary=---------------------------7e22c935391bde`

"Content-Type" in Chrome, even after setting json (works). 
`Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryrvtIIT7v5nQSWYLl`

Any idea? Are content-type not supposed to add "application/json"?  or if it's FormData, am I never supposed to mess with "content-type"?

**Comment by RefX32** [comment]
I fixed my problem. I just stopped setting Content-Type and left it alone. There was no actual need for me to set it anyway. When I'm posting, I'm converting all data into FormData before sending. If you feel this may be a bug, feel free to look into it, if not, feel free to close it.

**Comment by stephanfriedrich** [comment]
I had a similar problem within another project. but want to share these article which explains this issue and how to fix them.

article summary:
> the issue only happens when the last form element is a checkable input and is not checked, adding another hidden input that has arbitrary name is a workaround:

https://blog.yorkxin.org/2014/02/06/ajax-with-formdata-is-broken-on-ie10-ie11.html
