### ISSUE TITLE
Fetch() POST unsupported_grant_type

### ISSUE THREAD

**Issue by rhyshi** [github/fetch#600]
Hi guys,

Hopefully I am doing something really daft but:

I have an API which I want to fire a POST at to retrive the token. Following the fetch() structure/spec (https://github.com/github/fetch#post-json) I am using this:

```js
fetch('http://xxxx/Token', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json; charset=utf-8'
  },
  body: JSON.stringify({
    grant_type: 'password',
    username: 'USR',
    password: 'PASS'
  })
})
  .then(response => response.json())
  .then(responseJson => {
    const returnObj = responseJson;
    console.log(returnObj);
  });
```

However this returns a 400 bad request, with error "unsupported_grant_type".
At the same time I try it this way and it will work fine:

```js
fetch('http://xxx/Token', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json; charset=utf-8'
  },
  body: 'grant_type=password&username=USR&password=PASS'
})
  .then(response => response.json())
  .then(responseJson => {
    const returnObj = responseJson;
    console.log(returnObj);
  });
```

Any ideas??? 

Thanks

**Comment by dgraham** [comment]
The correct Content-Type value for the request body in the second example is `application/x-www-form-urlencoded`. So I suspect the server is ignoring the content type and treating all requests as form encoded. It might not accept JSON request bodies at all.

You can try doing response body content negotiation with the server by sending an `Accept: application/json` header.
