### ISSUE TITLE
How to send Json object to server

### ISSUE THREAD

**Issue by ngohungphuc** [github/fetch#605]
When I send the data to server all data is null even though I try to console.log data is there
 ```js
fetch("http://localhost:5000/Account/Test", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        Username: this.state.username,
        Password: this.state.password,
        RememberMe: this.state.rememberMe
      })
    });
```

![devenv_2018-02-23_21-38-07](https://user-images.githubusercontent.com/13591213/36599407-d9304fea-18e1-11e8-9935-3df7dbbbb4e4.png)

If i change body to following I will see the data 
```js
body: new URLSearchParams(
        `Username=${this.state.username}&Password=${
          this.state.password
        }&RememberMe=${this.state.rememberMe}`
      )
```
![devenv_2018-02-23_21-41-31](https://user-images.githubusercontent.com/13591213/36599561-53fb8064-18e2-11e8-97c3-1a296647914c.png)

The point is I dont want to use UrlSearchParams and I want to post json object to server . Any ideas ?

**Comment by mislav** [comment]
Your initial method of sending JSON to the server is correct. However, if the `localhost:5000` domain is different than the one that you're initiating the fetch request from, then you'll also have to be aware of CORS. See https://github.com/github/fetch#read-this-first for more information about the research you need to do to make this happen. Unfortunately, we can provide support for it here.
