### ISSUE TITLE
Have a way to send custom header without forcing lowercase

### ISSUE THREAD

**Issue by phandinhloc** [github/fetch#610]
I know it was reported and closed in https://github.com/github/fetch/issues/249 . However, this way makes me impossible to call public API of third party servers that require uppercase header names (and we can't control those servers). If according to the spec the header should be case-insensitive I don't see why forcing the headers to be lower case matters then, we should be generally allowed to send headers in any case form.

**Comment by mislav** [comment]
> If according to the spec the header should be case-insensitive

Your 3rd-party servers are the ones that are misbehaving then, not this library. Please contact _them_ about fixing their implementation.
