### ISSUE TITLE
 require('whatwg-fetch') bug

### ISSUE THREAD

**Issue by xgqfrms-gildata** [github/fetch#612]
# bug

> common.js

```js

// import 'whatwg-fetch';
var fetch= require('whatwg-fetch');

```

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/37512164-47dd20d4-293c-11e8-8e16-08f5fd576f29.png)

![image](https://user-images.githubusercontent.com/29531779/37512178-53a8f6ea-293c-11e8-8291-4b8a1eb37c0b.png)

**Comment by wmertens** [comment]
the polyfill does not return `fetch`… you have to import it and then call the global `fetch`.

**Comment by xgqfrms-gildata** [comment]
I like `ES6`, too!

**Comment by wmertens** [comment]
In my app I made it lazy-loading by having the browser entry code do this:

```js
...
async initBrowser() {
  if (!global.fetch) await import('whatwg-fetch')
  // ...rest of init, like React initial render etc
}
```
