### ISSUE TITLE
user-agent is still the default after I set it in the header

### ISSUE THREAD

**Issue by ethanyuwang** [github/fetch#614]
I'm using fetch on React Native both Android and iOS. I set the `User-Agent` to the name of the platform so I can distinguish between Android and iOS from the backend:

```
const URLENCODED_HEADER = {
  'Accept': 'application/json',
  'Content-Type': 'application/json',
  'User-Agent': Platform.OS + "/" + DeviceInfo.getUniqueID().toString()
}

export async function doRegister(secureInfo) {
  formBody = encodeParameters(secureInfo)
  try {
    let response = await fetch(SERVER_URL+'/user/register', {
      method: "POST",
      headers: URLENCODED_HEADER,
      body: formBody,
      credentials: 'include'
    });
    let responseJson = await response.json();
    return responseJson;
  } catch(error) {
    console.error(error);
    throw error;
  }
}
```

I have logged the requests in Reactotron and it looks like `user-agent` was changed successfully:

![screen shot 2018-03-22 at 3 12 07 pm](https://user-images.githubusercontent.com/17556945/38044793-aad3749a-326f-11e8-90c2-72a037097a75.png)

However, on the server side, the `ua` logged from the requests is still the default for android and ios devices, such as below:

```
Mozilla/5.0 (iPad; CPU OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D100 Safari/604.1

okhttp/3.6.0

Dalvik/2.1.0 (Linux; U; Android 5.1.1; Coolpad 3622A Build/LMY47V)
```

So is it possible to change the `user-agent` with fetch in React Native? If so what's the proper way to do it?

**Comment by mislav** [comment]
Browsers will typically disallow you from changing the `User-agent` string. It's a security restriction. There is no way around it; you'll have to use a different header name, e.g. `X-Custom-user-agent`, and configure the server to read it.

**Comment by ericksprengel** [comment]
@ethanyuwang Try to `Stop Remote JS Debug` to test it.

I was dealing with the same problem too.
