### ISSUE TITLE
body  string appended to formData auto replace `+`  to ` ` cause formData message transformed error

### ISSUE THREAD

**Issue by slashhuang** [github/fetch#615]
## how to produce this issue

```js
      let str = `a=+100`;
```
> using post method, `+` in `str` variable will be transformed  to ` `(a blank space)
> which is not expected for my usage case

## fetch source code position targeted below

> I check the source code and find below decode logic
```js
    var form = new FormData()
    body.trim().split('&').forEach(function(bytes) {
      if (bytes) {
        var split = bytes.split('=')
        var name = split.shift().replace(/\+/g, ' ')
        var value = split.join('=').replace(/\+/g, ' ')
        form.append(decodeURIComponent(name), decodeURIComponent(value))
      }
    })
    return form
```

> anyone can help to explain code logic above,  why fetch need to transform `+` which in my situation is not expected.

**Comment by mislav** [comment]
The `+` character is to be interpreted as a space. You can verify this behavior by checking how either URLSearchParams or Response are natively implemented in a modern browser such as Chrome:

```js
new URLSearchParams('a=+100').get('a') //=> " 100"

new Response('a=+100', { headers: {'content-type':'application/x-www-form-urlencoded'} })
  .formData().then(f => console.log(f.get('a'))) //=> " 100"
```
```
