### ISSUE TITLE
fetch with '' url rejects wth DOMException SyntaxError on IE

### ISSUE THREAD

**Issue by graingert** [github/fetch#618]
This is a bug in the IE XHR, another XHR wrapper has the same problem https://github.com/sstephenson/prototype/issues/234

**Comment by graingert** [comment]
@mislav any chance of looking at this?

**Comment by james-Ballyhoo** [comment]
Just ran into this and traced back to this library from polyfill.io

**Comment by graingert** [comment]
@mislav any chance of looking at this?
