### ISSUE TITLE
Fetch image from API

### ISSUE THREAD

**Issue by jazkh** [github/fetch#624]
Frontend: Reactjs
Backend: Nodejs
I am fetching an image from nodejs API after verifying with JWT token. I am getting GET 200 ok response in browser Network header and picture can be seen in Preview, but I cannot use it in my app.

I am surely doing something wrong. Please let me know the proper way to display image from API. On my backend nodejs, I am using res.sendFile to send the file.
```js
class Card extends Component {
  constructor({props, pic, token}) {
    super(props, pic, token);
    this.state = {
      pic: pic
    };
  }

  urlFetch(data) {
    fetch(data, {
      headers: new Headers({
        authorization: `Bearer ${this.props.token}`,
        'Content-Type': 'application/json'
      })
    }).then(response => {
      if (response.statusText === 'OK') {
        return data; // OR return response.url
      }
    });
  }

  render() {
    const {pic} = this.state;
    return (
      <div>
        <img style={{width: 175, height: 175}} className='tc br3' alt='none' src={ this.urlFetch(pic) } />
      </div>
    );
  }
}
```

**Comment by dgraham** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Body/blob
