### ISSUE TITLE
Form fetch issue

### ISSUE THREAD

**Issue by yoyo837** [github/fetch#625]
```js
options.headers = {
   'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
}
options.body = Object.keys(params)
  .map(key => `${encodeURIComponent(key)}=${encodeURIComponent(params[key])}`)
  .join('&')
```

Why  browser network `Form data` is `"mobile=15077778888&pwd=123456"`？

View parsed like this:

"mobile: 15077778888
pwd: 123456"

How can I make it without wrapper quotation marks?

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!

For what it's worth, it seems that your usage of `headers` and `body` is correct. The problem must be elsewhere.
