### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by afoysal** [github/fetch#632]
I am trying to upload file using `.fetch()` in ReactJS as Front End and Laravel as Back End. My ReactJS code is like below

    update= (event) => {
    let uploadImage =  event.target.file;
    let form = new FormData()
    form.append('uploadImage',uploadImage)

    fetch('http://127.0.0.1:8000/api/addresses/upload', {
      headers: {
        'Authorization': 'Bearer ' + Auth.getToken(),
        'Content-Type': 'multipart/form-data',
      },
      method: "POST",
      body: form,
    })
    .then(response => response.json())
    .catch(error => console.error('Error:', error))
    .then(response => console.log('Success:', response));
    }

  My Laravel code is like below

    public function fileUpload(StoreImageRequest $request)
        {
            $image           = $request->uploadImage;
            $imagename       = time() . $image->getClientOriginalName();
            $destinationPath = public_path('/images');
            $uploadValue     = $image->move($destinationPath, $imagename);
            if ($uploadValue) {
                return response()->json($imagename);
            }
        }

I am getting error like below

[![enter image description here][1]][1]

and

[![enter image description here][2]][2]

[![enter image description here][3]][3]

Where is the issue ?

  [1]: https://i.stack.imgur.com/7Dlv1.png
  [2]: https://i.stack.imgur.com/aTnxs.png
  [3]: https://i.stack.imgur.com/NXSAs.png

**Comment by mislav** [comment]
If you're passing a FormData object as `body`, you should not specify the `Content-type` header, and let the browser auto-fill it instead.
