### ISSUE TITLE
rasa nlu training

### ISSUE THREAD

**Issue by rishikesh1205** [github/fetch#633]
Rasa NLU version: 0.12.3
Operating system : linux
**Issue**:
i'm not able to classify the  conversations with multiple intents while training in Rasa-nlu and is it even possible??
the config file:
  pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

**Comment by keithamus** [comment]
Hi @rishikesh1205! I think you might have the wrong repository here. This is for the JavaScript `fetch` polyfill. I'm going to close this issue 😃
