### ISSUE TITLE
How to set body parameter when method is 'POST' and 'GET'?

### ISSUE THREAD

**Issue by MrZhang123** [github/fetch#635]
I use fetch in my project , when I set method is 'POST' , the body how to set ? in README, i find the body set like this:
```JS
  body: JSON.stringify({
    name: 'Hubot',
    login: 'hubot',
  })
```
but some article say the body need parameter like this:

```JS
body: "firstName=Nikhil&favColor=blue&password=easytoguess"
```
I have a question ,when the method set 'POST', body can set in two type like these ? 

Moreover, when method set 'GET', how to set body ?

**Comment by mislav** [comment]
Hello, this is a usage question and, as such, not appropriate to open issues about. Please use issues for bug reports.

`GET` requests can't have a body. `POST` requests can have a body which is either a string (such as the result of `JSON.stringify`), a URLSearchParams instance, a FormData instance, or some of the other types documented in https://github.github.io/fetch/#request-body.

When supplying a string `body`, you must also set an appropriate `content-type` header.

**Comment by tahir-jamil** [comment]
how can we set the value in body ?
 body: 'firstName=Nikhil&favColor=blue&password=easytoguess',
if i want to show Nikhil from a variable how can we do that?

**Comment by Babar-Memon** [comment]
let payload = {
      username: this.state.username,
      password: this.state.Password,
      type: "Login",
      AppVersion: "1.7"
  };
  let data = new FormData();
  data.append( "json", JSON.stringify( payload ) );
  fetch("https://concore.retailistan.com/app/teamlead/?",
  {
    method: 'post',
    body: JSON.stringify(data),
    headers: { 'Content-type': 'application/json' }
     })
  .then(function(res){ return res.json(); })
  .then(function(data){ alert( JSON.stringify( data ) ) 
    console.warn(data)
  })
   
  }

**Comment by Babar-Memon** [comment]
let payload = {
      username: this.state.username,
      password: this.state.Password,
      type: "Login",
      AppVersion: "1.7"
  };
  let data = new FormData();
  data.append( "json", JSON.stringify( payload ) );
  fetch("YOUR URL",
  {
    method: 'post',
    body: JSON.stringify(data),
    headers: { 'Content-type': 'application/json' }
     })
  .then(function(res){ return res.json(); })
  .then(function(data){ alert( JSON.stringify( data ) ) 
    console.warn(data)
  })
   
  }

**Comment by TaranAulakh** [comment]
how we send data in form without passing in input field
