### ISSUE TITLE
how to control timeout?

### ISSUE THREAD

**Issue by pisces22745** [github/fetch#637]
I want to get result in 3s, if error, I will give other page.

**Comment by keithamus** [comment]
Hey @pisces22745 thanks for the issue.

If you use the `AbortController` you can abort the fetch after a certain time has passed using the `AbortController#abort()`:

```js
const controller = new AbortController();
const signal = controller.signal;

const fetchPromise = fetch(url, {signal});

// 5 second timeout:
const timeoutId = setTimeout(() => controller.abort(), 5000);
```

I'll close this - as it should solve your question, and it isn't a bug within this repository. If you find any bugs please feel free to raise more issues!

**Comment by ianstormtaylor** [comment]
FWIW, I've opened an issue https://github.com/whatwg/fetch/issues/951 with a proposal for a `timeout` option that solves 90% of use cases, in case anyone's interested. I think it's super important to add to make sure calls to `fetch` (or `res.json()`) don't hang indefinitely.
