### ISSUE TITLE
Fetch won't retrieve cookie even with "same-origin" set in credentials.

### ISSUE THREAD

**Issue by aarondtaveras** [github/fetch#639]
Hi, I have a MERN + Passport.js application that is using fetch to make a call to my express API in order to retrieve data stored in a cookie. I have my React frontend routed to `localhost:3000`, and my backend routed to` localhost:3001 `My cookies are not being saved, and thus my session is not persisting within my browser. It is not an issue with the sessions, as when I use POSTMAN to execute the necessary calls to my API, the cookie is stored and the session persists. 

This is the line that I am using to save the cookie: 

```
handleLogin(event) {
        event.preventDefault();
        fetch("http://localhost:3001/users/login", {
            // credentials: 'include',
            credentials: 'same-origin',
            method: "post",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },   
        body: JSON.stringify({
            username: this.state.username,
            password: this.state.password
            })
        })
        // .then( (response) => response.json())
        .then( (response )=> {
            if(response.message){
                alert(response.message);
            }
        })
```

Which correctly calls my API, which logs the current session, user data, and cookie. 

Upon refreshing and making another request, I lose the cookie (it was never properly stored in the first place I think), and all session data. 

This is the get request that I make whenever I navigate to a new page: 

```
componentDidMount(){
        var current_user = "";
        fetch("http://localhost:3001/users/", {
            // credentials: 'include',
            credentials: 'same-origin',
            method: "get",
            headers: {
                'Accept':'application/json',
                'Content-Type': 'application/json'
            }        
        })
        // .then( (response)=> response.json())
        .then( (response)=> {
            if(response.user){
                current_user = response.user;
                this.setState({
                    user: current_user
                }), ()=> console.log(response);
            }
        })
    }
```
In response, I get an `undefined` user and no other response, and the cookie is never stored in my browser. But again, if I do this in POSTMAN, strictly doing the POST request followed by that GET request, the proper user data is returned and the cookie is shown in POSTMAN as well. 
Any idea as to why fetch is not passing the cookie information back to my front end? I have tried both `credentials: 'include'` and `credentials: same-origin`. 

Thank you!

**Comment by mislav** [comment]
You're making a request from `localhost:3000` to `localhost:3001`. These are not same origins. `credentials: same-origin` will only work if you're making a fetch request to the same host (meaning port numbers must match, too). `credentials: include` will only work if you familiarize yourself and implement CORS. See https://github.com/github/fetch#read-this-first
