### ISSUE TITLE
global way to handle errors like 401

### ISSUE THREAD

**Issue by aaronucsd** [github/fetch#645]
Is there a non- then.catch way of handling fetch errors? Like 401? Else i need to add `checkStatus` and then everywhere i use fetch.
https://github.com/github/fetch#handling-http-error-statuses

**Comment by aaronucsd** [comment]
i guess a `error:` substate works in actions. But still that is only for one route.

**Comment by mislav** [comment]
There is no global way. You will have to add something like `checkStatus` to every place you use fetch.
