### ISSUE TITLE
Can't find Variable Self error after y'day's update Expo React Native

### ISSUE THREAD

**Issue by davekedar** [github/fetch#658]
I am using Expo for react native, after y'day all my new project breaks while loading. please help, this is due to upgrade from 2.0.4 to 3.0.0

` "dependencies": {
    "expo": "^29.0.0",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz"
  }
}
`

**Comment by mislav** [comment]
#657
