### ISSUE TITLE
After update to 3.0.0, Webpack build is failing

### ISSUE THREAD

**Issue by belcherj** [github/fetch#659]
Updating from 2.0.4 to 3.0.0 webpack is failing, see error below. I assume I need to use a different loader but wanted to raise the issue since a quick web search and perusing the issues here did not result in any others having the issue.  This method of including fetch via webpack is shared a lot in examples so there will probably be others.

In my webpack config I include fetch globally like this:

```
new webpack.ProvidePlugin( {
	fetch: 'imports-loader?this=>global!exports-loader?global.fetch!whatwg-fetch',
} ),
```

```
    ERROR in ./node_modules/whatwg-fetch/fetch.js (./node_modules/imports-loader?this=>global!./node_modules/exports-loader?global.fetch!./node_modules/whatwg-fetch/fetch.js) 72:0
    Module parse failed: 'import' and 'export' may only appear at the top level (72:0)
    You may need an appropriate loader to handle this file type.
    | }
    |
    > export function Headers(headers) {
    |   this.map = {};
    |
     @ ./plugins/wccom-plugins/geo-page-replace/assets/setup.js 1:0-79
```

**Comment by belcherj** [comment]
webpack version 4.18.2 works with 2.0.4 but not with 3.0.0

**Comment by belcherj** [comment]
On my list to loop back here and figure out a solution.

**Comment by andrejpavlovic** [comment]
This worked for me:

```javascript
  plugins.push(
    new webpack.ProvidePlugin({
      fetch: 'exports-loader?self.fetch!whatwg-fetch/dist/fetch.umd',
    })
  );
```

**Comment by mbifulco** [comment]
@andrejpavlovic can you explain a bit more about your solution? Was it done as a fork to `fetch`, or in your own project's config? Apologies for my obvious ignorance here - I haven't spent much time configuring webpack at all.  Trying to get fetch 3 to work with a `create-react-app` project, which obfuscates webpack config, for the most part.

**Comment by mbifulco** [comment]
Sorry to be persistent here - @belcherj any chance you've got an update or workaround for this that might work with `create-react-app`?

**Comment by belcherj** [comment]
Sorry, got pulled onto another project and never ended up having time to figure out the solution.

**Comment by belcherj** [comment]
I just fixed it on the that project by using @andrejpavlovic 's solution:

- `fetch: 'imports-loader?this=>global!exports-loader?global.fetch!whatwg-fetch',`
+ `fetch: 'exports-loader?self.fetch!whatwg-fetch/dist/fetch.umd',`

**Comment by mislav** [comment]
Would this also work? `exports-loader?self.fetch!whatwg-fetch`

The problem with the `exports-loader?self.fetch!whatwg-fetch/dist/fetch.umd` approach is that it specifies the "main" file explicitly and will break again if the "main" file changes in a future major version.

**Comment by belcherj** [comment]
Tested and that works as well!

**Comment by scottmartin-ln** [comment]
@mislav: Trying your modification results in `TypeError: "exports" is read-only` for me.

**Comment by nikolas** [comment]
@mislav with `exports-loader?self.fetch!whatwg-fetch` I get the error:

```
fetch.js?f8ee:520 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.eval (fetch.js?f8ee:520)
    at eval (index.js?self.fetch!./node_modules/whatwg-fetch/fetch.js:527)
    at Module../node_modules/exports-loader/index.js?self.fetch!./node_modules/whatwg-fetch/fetch.js (bundle-k.js:1696)
    at __webpack_require__ (bundle-k.js:20)
    at eval (Xhr.js:181)
    at Module../src/Xhr.js (bundle-k.js:4995)
    at __webpack_require__ (bundle-k.js:20)
    at eval (JuxtaposeApplication.jsx:32)
    at Module../src/JuxtaposeApplication.jsx (bundle-k.js:4779)
    at __webpack_require__ (bundle-k.js:20)
```

but @belcherj's solution works in my case.
