### ISSUE TITLE
A beginner‘s question of cpp.

### ISSUE THREAD

**Issue by jecsi** [github/fetch#668]
#include <iostream>
using namespace std;

class CStu {
public:
	int a;
	char b;
	float c;
	CStu(){
		a = 12;
		b ="jecsi";
		c = 12.123f;
	}
};

int main()
{
	CStu stu;
	cout << stu.a << stu.b << stu.c << endl;
	system("pause");
	return 0;
}

**Comment by mislav** [comment]
Sorry, this is not a place to ask questions about CPP. Try asking at https://stackoverflow.com/search?q=cpp

Also note that you increase the likelikehood of getting an answer if you also write the actual question, not just paste code. Good luck!
