### ISSUE TITLE
no support for Headers interface

### ISSUE THREAD

**Issue by hakobpogh** [github/fetch#673]
I think that this polyfill should also polyfill the Headers interface of fetch API too: https://developer.mozilla.org/en-US/docs/Web/API/Headers

**Comment by mislav** [comment]
> I think that this polyfill should also polyfill the Headers interface of fetch API too

It does https://github.com/github/fetch/blob/899b155746630c32d83ee29a38642da16b314ecb/fetch.js#L513

> polyfilledFetch should work with the native Headers too

Theoretically, we could make that happen, but it's not something that want to invest resources in doing and maintaining. If someone uses the polyfilled fetch function, they need to use polyfilled Request and Headers as well, and _not_ native equivalents.
