### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by unformatt** [github/fetch#676]
npm 6.4.1
node 11.0.0
webpack 4.14
macOS High Sierra
whatwg-fetch 3.0.0
Chrome 70.0.3538.77 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/157132/48269299-3cc03900-e405-11e8-8fa6-2392f08c7c6f.png)

**Comment by mislav** [comment]
Hi could you try https://github.com/github/fetch/issues/659#issuecomment-426503387 please?

**Comment by unformatt** [comment]
@mislav Stumbled across this myself, removed the `new webpack.ProvidePlugin` entry and added 'whatwg-fetch` to Webpack `entry`. Will also try your suggestion.

My plugin was:
```
new webpack.ProvidePlugin({
      fetch: 'exports-loader?self.fetch!whatwg-fetch',
    }),
```
