### ISSUE TITLE
EvalError refused to evaluate because CSP is defined to script-src set to 'self' 'unsafe-inline'

### ISSUE THREAD

**Issue by lopesdasilva** [github/fetch#687]
Hi,

I need a clarification on this:

I'm using whatwg-fetch polyfill on a server with 'strict' CSP's
default-src 'none'; object-src 'self'; script-src 'self' 'unsafe-inline' ; connect-src 'self' ; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; frame-src 'self'

Currently i'm getting an error loading the script (although it's a browser with fetch support)
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'

![screenshot 2019-01-22 at 09 48 16](https://user-images.githubusercontent.com/1013126/51530428-d313d080-1e32-11e9-9ae2-6cccfd6146f6.png)

Thanks,
Rui

**Comment by mislav** [comment]
Hi @lopesdasilva,

Our project doesn't have any `eval` code. We use it on Github.com where we also have a strict CSP where we disallow unsafe-eval. Your exception comes from some other code, most likely whatever `stihl-react.js` is.
