### ISSUE TITLE
fetch can not send point

### ISSUE THREAD

**Issue by liutanrong** [github/fetch#690]
i want to send request with `http://gitlab.xxxxxx.com:4001/api/v3/users/liutanrong@gmail%2ecom`.but when use fetch ,it always is `http://gitlab.xxxxxx.com:4001/api/v3/users/liutanrong@gmail.com`.
```
const searchResponse = await fetch(
        `http://gitlab.xxxxxx.com:4001/api/v3/users/liutanrong@gmail%2ecom`,
        { headers: getHeaders() }
      );
```

**Comment by mislav** [comment]
`%2e` in URLs is the same as `.`. I don't know what you're asking, or what your problem is, but this is no place to ask. This is an issue tracker for a `fetch` polyfill used in old browsers that don't support `window.fetch` natively.
