### ISSUE TITLE
fetch api cors wrong error report

### ISSUE THREAD

**Issue by michaelyangbling** [github/fetch#695]
When my react frontend is on one server and node.js backend is on another, no reponse from my node.js api is always interpreted as " cors error", while actually it's other factors that lead to no reponse. This actually make me  misunderstood reason of the bug and spent several hours debugging on the "cors error", which is not the cause. Just feel like to let people know about this.

**Comment by michaelyangbling** [comment]
Just feel that if fetch api is not certain whether its " cors error" when connecting two different domains, it should not always say "cors error"

**Comment by keithamus** [comment]
Hey @michaelyangbling thanks for the issue.

Are you able to provide a reduced test case of this bug? It could be useful in fixing it. 

I'm going to close this issue for now as it's not actionable for us right now, but if you can come back with a reduced test case then I can re-open it and we can start establishing if a fix is needed. 👍
