### ISSUE TITLE
Is duplicate keys as query params supported?

### ISSUE THREAD

**Issue by richardhuf84** [github/fetch#697]
It looks like sending the same query param key multiple times in a get does not work. It just sends the last one.

The native fetch API supports this. Is this something that can be done with the whatwg-fetch polyfill, or are there plans to support this in future?

**Comment by mislav** [comment]
The whatwg-fetch polyfill doesn't process GET query parameters in any special way, and neither does the native fetch version either. All URLs are sent to the server as constructed, their query parameters untouched:

```js
fetch('http://example.com/path?foo=1&foo=2&foo=3')

Depending on which server parses this request, the server may choose to extract the last value of `foo` (common behavior), or it can choose to collect them in an array like `[1, 2, 3]`.

**Comment by richardhuf84** [comment]
Thanks @mislav. It was actually something else in my implementation. We're using Pretender to catch requests and mock responses, which was listening to fetches and turning the params into an object, stripping duplicates.

Thanks for the explanation, though!
