### ISSUE TITLE
whatwg--fetch is expecting "darwin" os and im on "win32"

### ISSUE THREAD

**Issue by YouceB** [github/fetch#699]
Hello everybody, I am learning to code online and I've ran into an issue with react
my code should work  but it seems to have issues with something I dont understand
 (TypeError: util_Yelp__WEBPACK_IMPORTED_MODULE_10_.default.searchYelp is not a function) 

I think that it is related to this error that I thought was not a big deal when I started the project
![sc npm](https://user-images.githubusercontent.com/48808241/55228454-6c3bda80-521a-11e9-9e11-30bf3c58946a.png)

It indicates that it is expecting the os to be “darwin” and mine is “win32”
so does any one know how to use this on windows ?

thanks a lot

**Comment by mislav** [comment]
Hello, [whatwg-fetch has 0 runtime dependencies](https://www.npmjs.com/package/whatwg-fetch?activeTab=dependencies) . Wherever fsevents is pulled from, it's not from our package. Please check your `package.json`
