### ISSUE TITLE
Unexpected use of 'self'

### ISSUE THREAD

**Issue by anxiaoyi** [github/fetch#702]
![2019_05_02_14_29_38](https://user-images.githubusercontent.com/4382796/57059233-e2829f80-6ce6-11e9-9490-0a5ca67753fe.png)

```
import 'promise-polyfill/src/polyfill';
import 'whatwg-fetch';
```

**Comment by koddsson** [comment]
Hey @anxiaoyi 👋 

If you set your linter to not lint 3rd party modules these will go away. This is a issue with your project setup and not with `github/fetch`.
