### ISSUE TITLE
 Fatal error: Uncaught Error: Call to undefined function mysql_query() in D:\XAMP\htdocs\mehar\Assignment.php:114 Stack trace: #0 {main} thrown in D:\XAMP\htdocs\mehar\Assignment.php on line 114

### ISSUE THREAD

**Issue by tayyabhanif03** [github/fetch#707]
<table cellpadding="5" border="1">
	
	<tr>
		<th>Name</th>   <th>Last Name</th>   <th>Email</th>   <th>Phone</th> <th>Update</th> <th>Delete</th>
	</tr>

	<?php 
      
      $show=mysql_query("SELECT * FROM users");
      while ($res=mysql_fetch_array($show)) {
      	# code...
      
      ?>
      <tr>
      <td><?php echo $res['Name']; ?></td>    <td><?php echo $res['LName']; ?></td>     <td><?php echo $res['Email']; ?></td>     <td>Alo<?php echo $res['PhoneNo']; ?></td> <td><a href="Update.php">Update</a></td> <td><a href="delete.php">Delete </a></td>

      </tr>
      <?php 

}

      ?>
	 
</table>

**Comment by mislav** [comment]
This is an issue tracker for a JavaScript library called `fetch`.
