### ISSUE TITLE
For those who are writing Firefox __addon__, the [solution here](https://www.reddit.com/r/firefox/comments/5yhwob/fetch_api_not_working_in_firefox_addon/) helped me, I have to add `"*://localhost/*"`

### ISSUE THREAD

**Issue by aishoo1612** [github/fetch#709]
For those who are writing Firefox __addon__, the [solution here](https://www.reddit.com/r/firefox/comments/5yhwob/fetch_api_not_working_in_firefox_addon/) helped me, I have to add `"*://localhost/*"`
to `permissions` key in `manifest.json`:

```

  "permissions": [
    "storage",
    "*://localhost/*"
  ],
```

Chrome just works without the need to add this permission...

_Originally posted by @hantatsang in https://github.com/github/fetch/issues/310#issuecomment-454662463_

**Comment by mislav** [comment]
Thank you for sharing your workaround!

Closing since this issue tracker is for reporting bugs with the polyfill only.
