### ISSUE TITLE
(UMD) Cannot set property 'WHATWGFetch' of undefined

### ISSUE THREAD

**Issue by tristanlins** [github/fetch#710]
If `fetch.umd.js` is loaded as classic JavaScript, it will work correctly.

```html
<!-- works -->
<script nomodule src="fetch.umd.js"></script>
```

But if you try to load them as JavaScript modules (ES modules), this will fail.

```html
<script type="module" src="/metropolis-tokio/:webjars/whatwg-fetch/dist/fetch.umd.js"></script>
<!-- or -->
<script type="module">
  import "/metropolis-tokio/:webjars/whatwg-fetch/dist/fetch.umd.js";
</script>
```

The error message: `Uncaught TypeError: Cannot set property 'WHATWGFetch' of undefined`

In other UMD modules, the `global` variable is set explicitly again. This makes it seem compatible.

```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
  typeof define === 'function' && define.amd ? define(['exports'], factory) :
  (/* begin change */ global = global || self, /* end change */ factory((global.WHATWGFetch = {})));
}(this, (function (exports) { 'use strict';
// ...
})));

```

**Comment by dgraham** [comment]
Browsers that support `<script type="module">` also have full support for the Fetch API, so loading this fetch polyfill isn't required in those browsers.

**Comment by tristanlins** [comment]
Oh, you're right, of course.
Sometimes you can not see the solution anymore because of polyfills. 🤣
Sorry for the noise.
