### ISSUE TITLE
25 اغسطس

### ISSUE THREAD

**Issue by monahasan** [github/fetch#714]
الريتويت على الطفل ما نزل اليوم شي 

رتيوت على كلو العظيمة عملت 11

الفلو على حساب التويتر

الفلو على حساب الانستا مع التلعيقات الي اكتر من خمسة  بلس ما نزلت شي بس رديت على استفسارت

الداتا عوضت عن اليوم والخميس

عملت 80 داتا 

ايش ضايل كمان بس هي الي اشتغلتو لليوم

![image](https://user-images.githubusercontent.com/52409260/63649982-93f18900-c74d-11e9-8fd2-3070f459cca6.png)

![image](https://user-images.githubusercontent.com/52409260/63649984-9f44b480-c74d-11e9-8102-39a408eb6795.png)

![image](https://user-images.githubusercontent.com/52409260/63649992-a7045900-c74d-11e9-97ac-5c8b2eca117e.png)

![image](https://user-images.githubusercontent.com/52409260/63649994-aec3fd80-c74d-11e9-9ebe-0cf5cfe33c1a.png)

**Comment by monahasan** [comment]
26 اغسطس


الريتويت عالطفل وبال فوركس



 مع الفلو


نزلت تلات بوستات على جدة والرياض وستوري الشرقية

مع متابعه الحسابات والتعليق الخماسي

![image](https://user-images.githubusercontent.com/52409260/63692810-2d3aa100-c81b-11e9-9cba-9aa9c28e0f71.png)

![image](https://user-images.githubusercontent.com/52409260/63692826-36c40900-c81b-11e9-9d73-bda656fc5f14.png)

![image](https://user-images.githubusercontent.com/52409260/63692834-3deb1700-c81b-11e9-9df1-0016b1d22d67.png)



![image](https://user-images.githubusercontent.com/52409260/63692844-45122500-c81b-11e9-9899-1f4587d694bb.png)

**Comment by koddsson** [comment]
I ran the text through Google Translate (since I don't speak arabic) and it looks like spam to me so I'm going to close this.

قمت بتشغيل النص من خلال الترجمة من Google (حيث أنني لا أتحدث اللغة العربية) ويبدو لي أنه بريد مزعج ، لذا سأغلق هذا.
