### ISSUE TITLE
IE11 syntax error

### ISSUE THREAD

**Issue by clxmstaab** [github/fetch#719]
since version 3.0 the /fetch.js contained in the npm package reports syntax errors within IE11.

in the past 2.x version we used the /fetch.js file as a 1:1 copy in our projects (which was easily done in our build step).

is it expected that this file now contains syntax which IE does not understand?

![image](https://user-images.githubusercontent.com/47448731/66406127-686bea80-e9eb-11e9-96db-c0690db7b3d6.png)

![image](https://user-images.githubusercontent.com/47448731/66406148-71f55280-e9eb-11e9-9dde-b5240977cd0e.png)

**Comment by dgraham** [comment]
The compiled file distributed in the package at `dist/fetch.umd.js` is compatible with IE11.
