### ISSUE TITLE
Refactor DOMException handling code to avoid redundant exceptions generation

### ISSUE THREAD

**Issue by RedMickey** [github/fetch#724]
Hello, we are the development team of VS Code extension for debugging React Native apps ([vscode-react-native](https://github.com/microsoft/vscode-react-native)). `whatwg-fetch` package is used in React Native lib. In our extension we debug React Native apps as a Node.js processes. Node JS global context doesn't contain `DOM` modules, so `"exports.DOMException is not a constructor"` exception is generated in `whatwg-fetch` package if fetch function is used in a React Native project. 
Could it be better to firstly verify if there is `DOMException` module in environment global context and only after that use [try/catch](https://github.com/github/fetch/blob/37d10362687492868548c4d70c5c12e4a671771e/fetch.js#L427-L439) construction? If `DOMException` module doesn’t exist it can be better to create this module without exception generation.
Here is the [issue](https://github.com/microsoft/vscode-react-native/issues/1133) for the corresponding case in the debugger extension repository.

**Comment by canpoyrazoglu** [comment]
This really becomes counterproductive when `All Exceptions` checkbox is enabled as this is hit everytime the app is restarted. I'd like to leave `All Exceptions` on, but can't because of this being hit each time, causing me to lose my focus, hit continue, go back to the file that I was working on etc.

**Comment by andrekovac** [comment]
Would be great if this issue could be taken into consideration!

**Comment by canpoyrazoglu** [comment]
@andrekovac exactly. I've got so many dependencies, none of them causing anything like this. It's only fetch, and no one is even willing to fix it. I think I'll just switch to something else like axios if none of my dependencies explicitly depend on fetch.

**Comment by JakeChampion** [comment]
> and no one is even willing to fix it.

@canpoyrazoglu, you yourself are not willing to fix this. This is an open source project worked on by people in their spare time. You can just as easily fix the issue yourself.

**Comment by JakeChampion** [comment]
That took 3 minutes to fix. https://github.com/github/fetch/pull/797
