### ISSUE TITLE
Outdated spec implementation. "fetch" spec changed in 2017 - Does not lowercase headers

### ISSUE THREAD

**Issue by leebradley** [github/fetch#737]
This polyfill is an outdated implementation of the fetch standard.

See this change to the fetch standard in 2017: https://github.com/whatwg/fetch/pull/476

To come back in compliance with the standard, the polyfill needs to stop lowercasing headers, regardless how headers are meant to be interpreted in RFC2616.

Browser implementations such as Chrome are already in compliance and do not lowercase headers for fetch calls.

**Comment by naclcaleb** [comment]
Are you primarily speaking of this function?
https://github.com/github/fetch/blob/7232090c04e1ddefb806910bbd0a756bc8aac2f0/fetch.js#L43-L51

**Comment by azooooo909** [comment]
Pubg

**Comment by leebradley** [comment]
@naclcaleb Sort of? But we can't just remove the lowercasing in normalization. I'm guessing we also need to implement a byte-insensitive match like annevk created in his whatwg PR.

**Comment by leebradley** [comment]
The reason why this spec update is important is while a server might be expected to handle headers a certain way (as outlined in RFC2616), they do not always comply. I recently came across such an issue.

**Comment by erhankaradeniz** [comment]
In our case it was the character `:` being seen as an illegal character. We added `https://` to our headers and this was breaking our code. Since in the regex where the names are normalized, a `:` is seen as an illegal character.

Can I fill a PR patch for this? We've fixed it on our end and I can push the fix.

**Comment by JakeChampion** [comment]
Headers look to not be lowercase when declared via an object but are lowercased when declared via the `Header` class.

**Comment by JakeChampion** [comment]
PR to resolve this --> https://github.com/github/fetch/pull/798
