### ISSUE TITLE
not working with Bearer token

### ISSUE THREAD

**Issue by badcodercpp** [github/fetch#743]
<img width="866" alt="Screenshot 2019-12-08 at 4 14 20 PM" src="https://user-images.githubusercontent.com/16036902/70388303-d6299800-19d5-11ea-96d1-852216d95eaf.png">
only options call at cross-domain

**Comment by badcodercpp** [comment]
solved

**Comment by badcodercpp** [comment]
solved

**Comment by andonyo** [comment]
can you tell me how to solve that?
