### ISSUE TITLE
IE 11 vs preProcessedHeaders.split(/\r?\n/)

### ISSUE THREAD

**Issue by pierremanceaux** [github/fetch#748]
Hello devs, and thank you for this great polyfill.

I am facing a strange bug in IE 11 (on Browserstack, no access to and old Windows system).

In short, the behaviour of [preProcessedHeaders.split(/\r?\n/).forEach(...)](https://github.com/github/fetch/blob/master/fetch.js#L373) seem to be inconsistent between for instance Chrome's last version (my reference point) and IE11 on Browserstack.

**IE 11** -> Incorrect
![image](https://user-images.githubusercontent.com/4114535/72547076-32f95780-388c-11ea-91a2-7bbba7578442.png)

**Chrome** -> Correct
![image](https://user-images.githubusercontent.com/4114535/72547173-66d47d00-388c-11ea-9415-e46c0d4842c4.png)

Meaning that the polyfill simply doesn't work for me on IE 11.

If you want to try yourself assuming you have an access to an IE 11 browser:
```
'preProcessedHeaders'.split(/\r?\n/)
'preProcessedHeaders\n'.split(/\r?\n/)
'preProcessedHeaders\r'.split(/\r?\n/)
'preProcessedHeaders\r\n'.split(/\r?\n/)
```

Is anyone able to reproduce this?

Thank you for your time in advance.

**Note**
Polyfill version: 3.0.0
Here is the IE11 build I tested with:
![image](https://user-images.githubusercontent.com/4114535/72547459-fda13980-388c-11ea-848a-d590a52f9a86.png)

**Comment by dgraham** [comment]
The regular expression works for me in a newer patch version of IE 11, so this might be a bug in the older version Browserstack seems to be using.

![Screen Shot 2020-01-24 at 08 42 49](https://user-images.githubusercontent.com/122102/73081942-c1ba3580-3e85-11ea-83eb-b86a60663d4a.png)

**Comment by pierremanceaux** [comment]
Thank you for having taken the time to test! More tests from more people are welcome here, as it is nearly impossible to obtain information about IE11 builds market shares.
I will notify Browserstack about it, and if they provide me with any interesting information I'll add it in here for other people.

**Comment by charlesbjohnson** [comment]
I'm running into the same thing on the newer version of IE 11 that was posted.

![screenshot](https://user-images.githubusercontent.com/4823640/74371514-8cc34380-4d9e-11ea-89d1-bba51fd2a3e5.png)

**Comment by pierremanceaux** [comment]
@charlesbjohnson your version is exactly the same as mine.

**Comment by charlesbjohnson** [comment]
> @charlesbjohnson your version is exactly the same as mine. Edit: or do you simply confirm that you run into this issue too?

Confirming that I'm running into this issue on the same version that you posted. I  don't know how to confirm if this is the latest IE 11, but I downloaded it today [from here](https://www.microsoft.com/en-us/download/details.aspx?id=41628).

**Comment by charlesbjohnson** [comment]
Correction: My version is the same as @dgraham's, and not the version @pierremanceaux posted in the PR description.

**Comment by pierremanceaux** [comment]
Yeah, didn't find a way to confirm the build date either, but for everything I see, seems pretty recent to me, if not the last one. I would bet it is the last one because:
- Well, I expect Browserstack to keep things up to date
- All google results are from end of last year until now
- Also just found a similar issue here: https://github.com/zloirock/core-js/issues/751

Seems like something is broken in IE11's last build...

**Comment by ansbar** [comment]
@pierremanceaux I use a newer version it seems, see image.

![image](https://user-images.githubusercontent.com/10725782/75024616-07284d80-549a-11ea-8719-f76de8c4d8ff.png)

Cant reproduce your problem but still have the problem in fetch:

![image](https://user-images.githubusercontent.com/10725782/75024593-f37ce700-5499-11ea-8a4c-15bddf29e881.png)

**Comment by pierremanceaux** [comment]
Interesting @ansbar , so in your version, `preProcessedHeaders\r\n'.split(/\r?\n/)` would work fine?

**Comment by pierremanceaux** [comment]
@dgraham maybe we should re-open this issue?

**Comment by ansbar** [comment]
preProcessedHeaders.split(/\r?\n/) works with your examples but not in my real life test.
For now I use:
preProcessedHeaders.split('\r\n')
which works.

**Comment by RamboKBR** [comment]
Rambo

czw., 16 sty 2020, 18:21 użytkownik Pierre Manceaux <
notifications@github.com> napisał:

**Comment by steveworkman** [comment]
The core-js ticket isn't getting any progress right now. Is there a way to work around this issue by not using the polyfilled regex and doing it a different way?

**Comment by JakeChampion** [comment]
This project does not use core-js at all, the issue you are seeing is one from core-js itself I believe and not something in this project.

**Comment by steveworkman** [comment]
@JakeChampion we do know of the issue though and it's common to use core-js polyfills and this polyfill. If we can use different code that doesn't trigger the bug - surely that's a win?
