### ISSUE TITLE
Handling of server header responses with carriage return \r (IE11) 

### ISSUE THREAD

**Issue by ansbar** [github/fetch#750]
Hi, this is a copy of the closed #422

I hope I can deliver a better explaination later on when speaking to the backend fellows I work with, but the core problem seems to be that some of our pages returns response headers with carriage returns or something (they all look simular but the result differs).

Line 374 in fetch.js

    preProcessedHeaders.split(/\r?\n/).forEach(function(line) {
makes the normalizeName throw an error
If I change it to

    preProcessedHeaders.split('\r\n').forEach(function(line) {
The result looks the same and works again.

This might be a problem in our application that sends weird headers but you might want to check it out, again? =)

Regards Per

**Comment by soda0289** [comment]
The problem with IE11 is that it doesnt handle split with regex correctly. I was able to add in a pollyfill for split() to handle the regex correctly.

Split polyfill: https://gist.github.com/slevithan/2048056

**Comment by dgraham** [comment]
This is discussed in #748.
