### ISSUE TITLE
Handling json content-type in IE11 response.

### ISSUE THREAD

**Issue by joetidee** [github/fetch#753]
A while ago we implemented a workaround for IE11 ignoring the `application/json` content-type (https://github.com/naugtur/xhr/issues/123) by defaulting to parsing the response using `.text()`:

```
const contentType = response.headers.get('content-type');
    const parsedResponseByContentType =
        contentType && contentType.includes('application/json') ? response.json() : response.text();

```
Is this still needed, or has the a polyfill been written to ensure that IE11 returns the raw response object instead of an empty string?

**Comment by dgraham** [comment]
This polyfill does not use `responseType: json` and just [parses the text response body](https://github.com/github/fetch/blob/7232090c04e1ddefb806910bbd0a756bc8aac2f0/fetch.js#L295).
