### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'this._initBody(body)')

### ISSUE THREAD

**Issue by nbrustein** [github/fetch#763]
We're using whatwg-fetch in production, and seeing the following error in our error reporting system occasionally in the wild.  It's happening in Chrome, where I wouldn't really expect `fetch` to be polyfilled.  Any idea what's causing it?

`TypeError: undefined is not a function (evaluating 'this._initBody(body)')`

**Comment by JakeChampion** [comment]
Something must be called `Request` as a normal function and not a Constuctor function. I.E. Without using `new Request`.

Do you have a code example and stacktrace for the times the error happens?

**Comment by JakeChampion** [comment]
This should be fixed by https://github.com/github/fetch/pull/796

**Comment by JakeChampion** [comment]
https://github.com/github/fetch/pull/796 is now merged
