### ISSUE TITLE
url field of Request is not normalized

### ISSUE THREAD

**Issue by bschlenk** [github/fetch#764]
If I create a new `Request` object with a relative url using this polyfill, the request's `url` field will be that same relative url.

In a browser that supports `fetch` natively, the `Request` object's `url` field will be a normalized url, containing the domain name and everything.

This is the code I'm using to verify:

```js
import 'whatwg-fetch';

const r = new Request('/abc/def');
document.write(r.url);
```

In chrome, this prints out `http://localhost:5000/abc/def`. In ie11, it prints out `/abc/def`. This is an issue when passing the url to the `URL` constructor, which expects a full url. I can't reliably do something like

```js
const r = new Request('/abc/def');
const url = new URL(r.url);
```

because it fails in older browsers (Error: Invalid scheme). I'm not a fetch master, so maybe this url normalization is non-standard?

**Comment by bschlenk** [comment]
A workaround if anybody else needs it:

```js
const r = new Request('/abc/def');
const url = new URL(r.url, window.location.origin);
```

**Comment by dgraham** [comment]
Another workaround is to create the Request with a URL object.

```js
const url = new URL('/abc/def', window.location.origin)
const request = new Request(url);
```
