### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by wheresrhys** [github/fetch#777]
There are a number of pull requests awaiting review. In particular this https://github.com/github/fetch/pull/736 is affecting a number of projects' ability to test projects using this fetch polyfill in IE11, and this PR (which I believe woudl fix CI, which is currently broken on master) has a response saying 'looks good, but I no longer maintain the project' https://github.com/github/fetch/pull/698

Abandoned open source projects is kinda to be expected, but I'd expect Github to do better

**Comment by JakeChampion** [comment]
It is not abandoned :-) I accidentally stopped watching the repository, which meant I got no notifications for issue and pull-requests. I've now rewatched it and am going through the pull-requests and issues.
