### ISSUE TITLE
What is new in 3.1.0?

### ISSUE THREAD

**Issue by shirotech** [github/fetch#789]
https://www.npmjs.com/package/whatwg-fetch/v/3.1.0
https://unpkg.com/browse/whatwg-fetch@3.1.0/

Can't seem to find any changelog or release notes, would be good to know what is new in this npm release. Thanks.

**Comment by joelharkes** [comment]
Idem, i'm missing release notes and any info.

**Comment by mobilutz** [comment]
It seems, that this is the diff for this release:
https://github.com/github/fetch/compare/v3.0.0...74e4fe8a4731b4e233ac7da42c960a351fd3400f
Unfortunately, there are no releases/tags here on GitHub.

But maybe @JakeChampion can help out here?

**Comment by JakeChampion** [comment]
I've made a GitHub release which lists all the updates -- https://github.com/github/fetch/releases/tag/v3.1.0

I'm a new maintainer of this polyfill as GitHub no longer use a `fetch` polyfill they thought it was best to transfer ownership/maintership to a person who maintains other polyfills. I work on https://polyfill.io and maintain most of the polyfills which are used in the service 👍
