### ISSUE TITLE
TypeError: Fetch event is destroyed. Safari bug tracked by Sentry after updating to latest whatwg-fetch@3.1.0

### ISSUE THREAD

**Issue by JustFly1984** [github/fetch#790]
IOS 13.5.1
Mobile Safari 13.1.1

error on attempt to load css file from same origin

Never seen error like that before today.

<img width="1335" alt="Screenshot 2020-06-30 19 58 43" src="https://user-images.githubusercontent.com/2255993/86173130-b1e80100-bb49-11ea-8d75-ef4ec032b36b.png">

I've posted by accident to https://github.com/whatwg/fetch/issues/1048

**Comment by JakeChampion** [comment]
iOS 13 would be using a native fetch and not a polyfill. Are you sure it is using the polyfill?

**Comment by JustFly1984** [comment]
@JakeChampion  I'm sure I'm importing "whatwg-fetch": "3.1.0" polyfill before everything else in the code, and removing window.fetch for IE to fix bug:

```
<script type='application/javascript'>
          {'if(/Edge/.test(navigator.userAgent)){delete window.fetch}'}
        </script>
```

**Comment by JakeChampion** [comment]
I'm quite confused about this one because we don't have an error which uses the phrase "event is destroyed", which makes me think the polyfill is not being applied but the code you've posted makes me also think it can't be the native fetch due to `delete window.fetch`. Could you post the full stacktrace for the error please? That should hopefully help us figure out what is going on

**Comment by JustFly1984** [comment]
@JakeChampion  basically there is one async request for css file with fonts. 
It looks like safari 13.1.1, and it happened only once by now.

<img width="1301" alt="Screenshot 2020-07-04 13 06 18" src="https://user-images.githubusercontent.com/2255993/86506178-3e6b1b80-bdf7-11ea-9669-e99dc7d0d359.png">

**Comment by JakeChampion** [comment]
Do you have the full stacktrace for the error? Sentry usually captures the full stack trace to help with debugging.

The stacktrace is usually between the "exception" section and the "breadcrumbs" section. If there is no captured stack trace then I don't know how to help debug this situation, sorry 😔 

Here is a screenshot of what the sentry page looks like with a stacktrace
<img width="802" alt="showing stacktrace on sentry for a captured exception" src="https://user-images.githubusercontent.com/1569131/86519880-0f749a00-be37-11ea-9c10-05b6bc0a4abb.png">

**Comment by JakeChampion** [comment]
Okay, looking into the webkit source code I can see the same error message "Fetch event is destroyed", which is an error message that we don't have in this fetch polyfill. I am very confident that for the specific fetch request, it used the native fetch and not the polyfill.

Here is the patch to webkit which added the error message -- https://www.mail-archive.com/webkit-changes@lists.webkit.org/msg129765.html

**Comment by JustFly1984** [comment]
So why didn't polyfill worked out?

**Comment by JakeChampion** [comment]
You are only deleting native fetch for edge but this bug was in native fetch for iOS

**Comment by JustFly1984** [comment]
@JakeChampion  If I remove window.fetch for IOS, should polyfill work in this case? Is there guaranty way to detect safari same way as I detect Edge?

**Comment by JustFly1984** [comment]
@dgraham  please reopen, cos there is no solution to resolve an issue. I understand that it is a bug with webkit, but is it possible to solve it by using fetch polyfill, and if yes, how?
