### ISSUE TITLE
IE11 fails with Syntax error on line 78 

### ISSUE THREAD

**Issue by ericnewton76** [github/fetch#791]
Using https://cdnjs.cloudflare.com/ajax/libs/fetch/3.1.0/fetch.js

IE fails to load the fetch polyfill with
```
SCRIPT1002: Syntax error
fetch.js (78,1)
```

Line 78:
```javascript
export function Headers(headers) {
```

**Comment by ericnewton76** [comment]
version 2.0.4 works btw.  I love IE.

**Comment by dgraham** [comment]
Loading the module file from a third-party server isn’t a supported distribution format. The module needs to be compiled into a bundle using Rollup or Webpack in the host app.
