### ISSUE TITLE
Undefined self

### ISSUE THREAD

**Issue by ctomczyk** [github/fetch#817]
**Actual**

It seems that sometimes `self` becomes `undefined` and therefore fetch throws an error every time `self` is being used.

**Steps to reproduce**

1. Go to https://www.cresa.com/
2. Open developer console
3. Type `self`
4. It gets `undefined`.

**Comment by JakeChampion** [comment]
That looks like a problem with the code of cresa.com and not a problem with this fetch polyfill. the global variable `self` should always be a reference to the global environment, making it point to something else such as `undefined` will break lots of code, not just this polyfill.

**Comment by ctomczyk** [comment]
That's true, but in case of undefined `self` fetch should imho check if `window` is available and use it. That way at least code won't throw a runtime error.
