### ISSUE TITLE
fetch.umd.js is outdated.

### ISSUE THREAD

**Issue by Directory** [github/fetch#819]
Im trying to link the js from the release page but fetch.umd.js is nowehre on it. It took me forever to find its only under v3.0.0. What about v3.3.1?

**Comment by JakeChampion** [comment]
Hi, thanks for bring this to my attention.
I added a umd file for 3.3.1 release -- https://github.com/github/fetch/releases/download/v3.3.1/fetch.umd.js

Another way to get the file is from npm or from an npm web CDN such as unpkg like so -- https://unpkg.com/whatwg-fetch@3.3.1/dist/fetch.umd.js
