### ISSUE TITLE
What's the reason of using setTimeout for resolving/rejecting fetch promise?

### ISSUE THREAD

**Issue by SirwanAfifi** [github/fetch#831]
Looking through the code I just noticed you have used `setTimeout` for resolving/rejecting the promise. Can't we just immediately call the resolve/reject callback instead of using a [setTimeout](https://github.com/github/fetch/blob/master/fetch.js#L514) with  0 ms? 

```js
xhr.onload = function() {
      var options = {
        status: xhr.status,
        statusText: xhr.statusText,
        headers: parseHeaders(xhr.getAllResponseHeaders() || '')
      }
      options.url = 'responseURL' in xhr ? xhr.responseURL : options.headers.get('X-Request-URL')
      var body = 'response' in xhr ? xhr.response : xhr.responseText
      resolve(new Response(body, options));
}
```

I know, setTimeout's callback is not going to get executed immediately, it moves the callback down into Callback queue. I just want to know what the reason to do that.

**Comment by JakeChampion** [comment]
Because the resolved or rejected Promise _needs_ to happen asynchronously and if we did not put the `resolve` and `reject` call inside a `setTimeout` then they _could_ happen synchronously.
