### ISSUE TITLE
release v3.4.0 do not contain a fetch.umd.js

### ISSUE THREAD

**Issue by KingAmo** [github/fetch#833]
the latest `fetch.umd.js` is ` v3.3.1 `

**Comment by JakeChampion** [comment]
It does contain it --> https://unpkg.com/browse/whatwg-fetch@3.4.0/dist/fetch.umd.js

**Comment by KingAmo** [comment]
@JakeChampion oh, it does not show a link in [github release](https://github.com/github/fetch/releases)

**Comment by JakeChampion** [comment]
Ah yes, thank you for pointing that out, I've now fixed that 👍
