### ISSUE TITLE
Is FetchEvent() supported? [question]

### ISSUE THREAD

**Issue by genderev** [github/fetch#836]
Can you addEventListener for the fetch polyfill?

**Comment by JakeChampion** [comment]
could you give some more details about this feature request please?

**Comment by genderev** [comment]
> could you give some more details about this feature request please?


The [fetch](https://w3c.github.io/ServiceWorker/#fetchevent) [event](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent)?

**Comment by JakeChampion** [comment]
No, this is not supported and likely to not be supported by this project

**Comment by AlucarD08081986S** [comment]
😀

**Comment by AlucarD08081986S** [comment]
😀
