### ISSUE TITLE
"Already read" error while posting

### ISSUE THREAD

**Issue by surajts** [github/fetch#837]
If I use the following code, I am getting an error "Already read" when accessing .json() . If we post using the pollyfill can we can we not read the json that is returned back? 

```js
var param = {name: 'Bob'};
fetch('/api', {
  method: 'POST', // or 'PUT'
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify(param)
})
  .then(function(response) {
    if (response.ok) {
      return response.json();
    } else {
      var error = new Error(response.statusText);
      error.response = response;
      throw error;
    }
  })
  .then(function(json) {
    console.log('parsed json', json);
    document.getElementById('divresponse').innerText = JSON.stringify(json);
  })
  .catch(function(ex) {
    console.log('parsing failed', ex);
  });
```
Below is the IE version.
![image](https://user-images.githubusercontent.com/7926724/93648396-4c7d1100-f9d0-11ea-9b32-cd956fb8994e.png)

**Comment by dgraham** [comment]
The response body may be [consumed only a single time](https://github.com/github/fetch/blob/5e3aa109b5d23a982c4a01718469e2c63bc6815f/fetch.js#L161-L166). Calling the `response.json()`, `response.text()`, etc methods can only be done once and only one of them may be called on the response object.

I don't see anything in your code example that consumes the response body multiple times. However, attaching the response object to the exception allows multiple `catch` blocks to consume the response body, which may be causing this error. You can clone the response with `response.clone()` to consume the body again.

**Comment by surajts** [comment]
Looks like it is a developer tools issue. While debugging just accessing response is doing the read I believe.
