### ISSUE TITLE
this.append is not a function

### ISSUE THREAD

**Issue by himmelmaus** [github/fetch#844]
I'm encountering this error when trying to use the latest version 
![image](https://user-images.githubusercontent.com/17053773/94438553-2e18d180-0197-11eb-8d9e-736ece226aab.png)
Is this a known issue? I've attempted various rejiggings to see if I am doing something wrong but I cannot see anything - the code I'm using for the fetch is shown below:
```
fetch("/api/result/csv?export_number=" + encodeURIComponent(export_number), {
        method: "GET",
        credentials: "same-origin",
        headers: {
            "X-CSRFToken": event.target.dataset.csrfToken,
            "Content-Type": "application/json",
            Accept: "application/json",
        },
    })
```
I originally tried this without the "Content-Type" and "Accept" headers, which seem to make no difference. Any help would be appreciated as I'm stumped, thanks in advance.

ETA: This occurs both on chrome, firefox, and ie 10.

**Comment by thor174** [comment]
> I'm encountering this error when trying to use the latest version 
> ![image](https://user-images.githubusercontent.com/17053773/94438553-2e18d180-0197-11eb-8d9e-736ece226aab.png)
> Is this a known issue? I've attempted various rejiggings to see if I am doing something wrong but I cannot see anything - the code I'm using for the fetch is shown below:
> ```
> fetch("/api/result/csv?export_number=" + encodeURIComponent(export_number), {
>         method: "GET",
>         credentials: "same-origin",
>         headers: {
>             "X-CSRFToken": event.target.dataset.csrfToken,
>             "Content-Type": "application/json",
>             Accept: "application/json",
>         },
>     })
> ```
> I originally tried this without the "Content-Type" and "Accept" headers, which seem to make no difference. Any help would be appreciated as I'm stumped, thanks in advance.
> 
> ETA: This occurs both on chrome, firefox, and ie 10.
> 

4.4

**Comment by thor174** [comment]
> I'm encountering this error when trying to use the latest version 
> ![image](https://user-images.githubusercontent.com/17053773/94438553-2e18d180-0197-11eb-8d9e-736ece226aab.png)
> Is this a known issue? I've attempted various rejiggings to see if I am doing something wrong but I cannot see anything - the code I'm using for the fetch is shown below:
> ```
> fetch("/api/result/csv?export_number=" + encodeURIComponent(export_number), {
>         method: "GET",
>         credentials: "same-origin",
>         headers: {
>             "X-CSRFToken": event.target.dataset.csrfToken,
>             "Content-Type": "application/json",
>             Accept: "application/json",
>         },
>     })
> ```
> I originally tried this without the "Content-Type" and "Accept" headers, which seem to make no difference. Any help would be appreciated as I'm stumped, thanks in advance.
> 
> ETA: This occurs both on chrome, firefox, and ie 10.
> 

👍

**Comment by findoslice** [comment]
@thor174 I don't understand what you mean sorry?

**Comment by thor174** [comment]
6b57397b5b8efc5bdcaa8ff0292dcb32c295102f

**Comment by evheniyrz** [comment]
@findoslice 

try to assign the headers via next way
```
headers: new Headers({
        "header_name": "header_value"
            })
```

**Comment by ashokirla** [comment]
comment123

**Comment by KVROHITH098** [comment]
hey Jake what's up!

can I help?

**Comment by JakeChampion** [comment]
Sure thing @KVROHITH098 - I'm happy to review a PR for this

**Comment by KVROHITH098** [comment]
Thanks
