### ISSUE TITLE
fetch not working if device's date is set to future. wrong date issue

### ISSUE THREAD

**Issue by krunalbad** [github/fetch#854]
I am working on RN app 0.63
Consider Today's date 22-OCT-2020
- if device's date is set to past it is working fine i.e; 21-OCT-2020
- if device's date is today's date and only time is change like -1hour or +1hour then also it is working fine
- if device's date is set to future then the fetch won't work i.e; 25-OCT-2020 like 2-3 days or more

Note: Other apps on play store i have tested working fine. So i am expecting there must be a solution for this

**Comment by joojoodamn** [comment]
I have jessica gibbons over here at my place and her and a friend are
always willing to work. If you like her let me know

**Comment by JakeChampion** [comment]
What happens to the fetch? Is the request never made? Does it return a rejected promise? Could you create a small piece of code which shows  the issue please?

**Comment by krunalbad** [comment]
```
import React, { Component } from 'react';
import { View, Text, SafeAreaView } from 'react-native';

class App extends Component {

  componentDidMount() {
    try {
      // let url = 'https://gorest.co.in/public-api/users';
      console.clear();
      fetch(url)
        .then((res) => res.json())
        .then((json) => console.log(json));
    } catch (error) {
      console.log(error)
    }
  }

  render() {
    return (
      <SafeAreaView>
        <View>
          <Text style={{ color: 'white', fontSize: 90 }}> App </Text>
        </View>
      </SafeAreaView>
    );
  }
}

export default App;

```
![Uploading Screenshot 2020-10-23 at 4.36.22 PM.png…]()

**Comment by JakeChampion** [comment]
@krunalbad Can you add a .catch to the promise returned from fetch and test that out please?

I don't know anything about react-native or how to develop with it.

```js
import React, { Component } from 'react';
import { View, Text, SafeAreaView } from 'react-native';

class App extends Component {

  componentDidMount() {
    try {
      const url = 'https://gorest.co.in/public-api/users';
      console.clear();
      fetch(url)
        .then((res) => res.json())
        .then((json) => console.log(json));
    } catch (error) {
      console.log(error)
    }
  }

  render() {
    return (
      <SafeAreaView>
        <View>
          <Text style={{ color: 'white', fontSize: 90 }}> App </Text>
        </View>
      </SafeAreaView>
    );
  }
}

export default App;
```

**Comment by krunalbad** [comment]
You can use the try-catch block of code I have provided
If you are running on React.js or Vanilla JS project this should be good I guess!
```
   try {
      const url = 'https://gorest.co.in/public-api/users';
      console.clear();
      fetch(url)
        .then((res) => res.json())
        .then((json) => console.log(json))
		.catch((error) => console.error(error));
    } catch (error) {
      console.log(error)
    }
```

**Comment by JakeChampion** [comment]
The error returned is from the network/security stack of the browser, it is not something which can be resolved in this project. The only way to fix it is to correct the date and time on the device.

The error code firefox gives is `SEC_ERROR_OCSP_FUTURE_RESPONSE`.

Closing the issue as there is nothing we can do to fix this.

**Comment by krunalbad** [comment]
okay 😞
