### ISSUE TITLE
fetch polyfill throwing Type error for valid header field name

### ISSUE THREAD

**Issue by shishirarora3** [github/fetch#878]
fetch polyfill throwing Type error for valid header field name

The headers I am passing are 

'X-OWA-CANARY': "somer value",
'Content-Type': "some value"

**Comment by janast1975** [comment]
wow

**Comment by JakeChampion** [comment]
@shishirarora3 could you provide a minimal example code which reproduces the issue please?

**Comment by wessam526652** [comment]
> fetch polyfill throwing Type error for valid header field name
> 
> The headers I am passing are
> 
> 'X-OWA-CANARY': "somer value",
> 'Content-Type': "some value"
