### ISSUE TITLE
application/json content type and Chrome Canary implementation

### ISSUE THREAD

**Issue by adamschoenemann** [github/fetch#88]
I'm having some issues with different behaviour of this polyfill vs. Canary's implementation.

When accessing a JSON endpoint that responds with Content-Type: application/json I get the following results:
```javascript
fetch('http://my/api/json-endpoint').then(resp => {
	console.log(resp);
})
// Canary output:
Response {bodyUsed: false, headers: Headers, statusText: "OK", ok: true, status: 200, type: "basic"}
// Polyfill output
Object { _bodyInit: Blob, _bodyBlob: Blob, type: "default", url: "http://taarn-net.dev/api/user/1", status: 200, statusText: "OK", headers: Object, bodyUsed: true }
```
I can still use resp.text(), but isn't it weird that the Canary output says no body is used and type is "basic" rather than "default"?

**Comment by dgraham** [comment]
The `bodyUsed` flag should only be marked `true` after the body has been consumed by a call to `response.json()` or `response.text()`.

**Comment by adamschoenemann** [comment]
Aha, I see! Sorry, I was confused by some unrelated bugs I was experiencing with Marty.js' fork of fetch.
