### ISSUE TITLE
fetch.js uses Promise() -- how to use this on IE9?

### ISSUE THREAD

**Issue by Jeff17Robbins** [github/fetch#90]
The browser support icons suggest IE9+ support.  But fetch.js uses Promise() objects.  How is this meant to work?

**Comment by dgraham** [comment]
It requires the polyfill described in the readme: https://github.com/github/fetch#installation

**Comment by Jeff17Robbins** [comment]
I see it now -- sorry for missing it!

You'll also need a Promise polyfill for older browsers.
> $ bower install es6-promise
