### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by tigger9flow** [github/fetch#901]
Seems like `whatwg-fetch` has a memory leak. Tested in the browser (Google Chrome, 88). The issue is reproduced by simple script (ignore CORS errors, it behaves the same when request is resolved) which fires requests in interval:
```
<script>
  // Delete native fetch api to force the polyfill installation
  delete window.fetch
  delete window.Request
  delete window.Response
  delete window.Headers
</script>
<script src="https://unpkg.com/whatwg-fetch@3.5.0/dist/fetch.umd.js"></script>
<script>
  setInterval(() => {
    fetch('https://www.google.com').then(console.log, console.log)
  }, 250)
</script>
```
After profiling around 1 minute, we can see that event listeners are constantly growing:

![image](https://user-images.githubusercontent.com/18001933/107024723-1094ed80-67b1-11eb-9907-b5c7ebb7a30b.png)

While they are fine with native `fetch`:

![image](https://user-images.githubusercontent.com/18001933/106926837-2e634380-671a-11eb-8324-6471b9b97a38.png)

**Comment by tigger9flow** [comment]
Did some research - looks like it's an issue with Chrome DevTools itself. Here are some links:
https://stackoverflow.com/questions/46695853/javascript-listeners-keep-increasing
https://bugs.chromium.org/p/chromium/issues/detail?id=576302

**Comment by JakeChampion** [comment]
> Did some research - looks like it's an issue with Chrome DevTools itself. Here are some links:
> https://stackoverflow.com/questions/46695853/javascript-listeners-keep-increasing
> https://bugs.chromium.org/p/chromium/issues/detail?id=576302

As you found it is a Chrome Devtools issue, shall we close this issue?

**Comment by tigger9flow** [comment]
@JakeChampion Yeah, I think it can be closed, I've reproduced the same behavior in Chrome DevTools even with simple XHR requests, so it doesn't seem to be a `fetch` problem
