### ISSUE TITLE
const in fetch.js causing crashes in older browsers

### ISSUE THREAD

**Issue by MilosRasic** [github/fetch#915]
Not sure about what versions of Chrome are intended to be supported, but this line is new in the latest release (3.6.0):
https://github.com/github/fetch/blob/1fce243d23b2aa2e44abf58c39f54097d8a9917c/fetch.js#L249

It's causing crashes in LG webOS 3.x (Chrome v38) and Tizen 2.x (webkit equivalent to Safari 6) TV apps. Was also able to reproduce in normal Chrome browser v38.

We can work around this problem by transpiling the package, but if polyfill is intended for older browsers, might make sense to remove consts from build output.

**Comment by alexbakum** [comment]
Possibly, I already created the PR to fix the issue https://github.com/github/fetch/pull/914

**Comment by MilosRasic** [comment]
Not the same problem @alexbakum

`Array.includes()` is fine in old webkit but `const` is not.

**Comment by alexbakum** [comment]
@MilosRasic yup. I've misread your issue. That's why I've removed my comment
