### ISSUE TITLE
version 3.6.0 breaks Electron 80 (Chromium 80)

### ISSUE THREAD

**Issue by hans2520** [github/fetch#922]
Verified that `POST` request works prior to upgrading to whatwg-fetech 3.6.0. Behavior the same with 3.6.1. Afterwards, with no other changes, we can see server receive Content-Length of 0 and empty body.

I found the offending line of code, simply commenting it out fixes things:
https://github.com/github/fetch/commit/5c6b055e6ae6f718f416c94bfcdc89693d0abdcb#r47472637

The branch system above is quite convoluted, but I think if you can ensure the original body is preserved when you assign here, things will still work. From what I can tell, my code was hitting the final branch (https://github.com/github/fetch/commit/5c6b055e6ae6f718f416c94bfcdc89693d0abdcb#diff-3fc6f1265a180d15035618e36ca1da88d092bacb4fc10a423938fa62e4f5f58fR246) and body being re-assigned there. But I tried a simple case of removing the body assignment there, and using body as the assignment instead on line 262, but it doesn't work. Making a new variable `var origBody = body` at the top of the branches and assigning that on line 262 _does_ work however. 

So probably want to look at cleaning up those branches. In the meantime, will be stuck at v3.5

**Comment by JakeChampion** [comment]
Could you please post a small piece of code which would reproduce the problem you are seeing? With a small example, I should be able to help fix this issue. Without one, I will struggle a lot.

**Comment by hans2520** [comment]
Well the issue seems to be with this line of code (line 246) because we are modifying the contents of `body` & `_bodyText`: https://github.com/github/fetch/commit/5c6b055e6ae6f718f416c94bfcdc89693d0abdcb#diff-3fc6f1265a180d15035618e36ca1da88d092bacb4fc10a423938fa62e4f5f58fR246

Then you are saying you are going to "save" the original body content into `_bodyInit`, but by this time it isn't true that `body` & `_bodyText` have the original contents. In fact it seems that in my case, the original contents of `_bodyInit` were already correct, and what's being assigned in line 246 is in fact wiping `body` and `_bodyInit` out entirely and that's why an empty body is sent to the server with this change.

SImply making this assignment on line 227 (
https://github.com/github/fetch/commit/5c6b055e6ae6f718f416c94bfcdc89693d0abdcb#diff-3fc6f1265a180d15035618e36ca1da88d092bacb4fc10a423938fa62e4f5f58fR227), a new line:
```
var origBody = body
```

Then changing line 262 (https://github.com/github/fetch/commit/5c6b055e6ae6f718f416c94bfcdc89693d0abdcb#diff-3fc6f1265a180d15035618e36ca1da88d092bacb4fc10a423938fa62e4f5f58fR262) to 
```
 this._bodyInit = origBody
```

Also fixes the issue.

However, that is very much a hack for what is a very convoluted conditional branch tree that really should just be re-worked altogether. There's too much leaky logic going on in there.

**Comment by JakeChampion** [comment]
This was fixed in https://github.com/github/fetch/releases/tag/v3.6.2

**Comment by saifalislam** [comment]
What are this things ??
