### ISSUE TITLE
Unable to use .clone() in 3.6.0 or 3.6.1

### ISSUE THREAD

**Issue by Darkmyr** [github/fetch#923]
I believe this has to do with this snippet of code. We're finding that the JSON body is either overwritten/wiped out or inaccessible.
```js
    var contentType = this.headers.get('content-type')

    if (!contentType) {
      if (typeof body === 'string') {
        this.headers.set('content-type', 'text/plain;charset=UTF-8')
      } else if (this._bodyBlob && this._bodyBlob.type) {
        this.headers.set('content-type', this._bodyBlob.type)
      } else if (support.searchParams && URLSearchParams.prototype.isPrototypeOf(body)) {
        this.headers.set('content-type', 'application/x-www-form-urlencoded;charset=UTF-8')
      }
    } else if (contentType.indexOf('json') >= 0 && typeof this._bodyInit !== 'string') {
      // Always pass a text representation of a non-stringified JSON body
      // to `XMLHttpRequest.send` to retain a compatible behavior with the browser.
      this._bodyInit = this._bodyText
    }
```
There appears to be no issues when we run in version `3.5.0`.

Found in conjunction with @georgeloring / @katerynapalchykova

**Comment by Taranehpasha** [comment]
> I believe this has to do with this snippet of code. We're finding that the JSON body is either overwritten/wiped out or inaccessible.
> 
> ```js
>     var contentType = this.headers.get('content-type')
> 
>     if (!contentType) {
>       if (typeof body === 'string') {
>         this.headers.set('content-type', 'text/plain;charset=UTF-8')
>       } else if (this._bodyBlob && this._bodyBlob.type) {
>         this.headers.set('content-type', this._bodyBlob.type)
>       } else if (support.searchParams && URLSearchParams.prototype.isPrototypeOf(body)) {
>         this.headers.set('content-type', 'application/x-www-form-urlencoded;charset=UTF-8')
>       }
>     } else if (contentType.indexOf('json') >= 0 && typeof this._bodyInit !== 'string') {
>       // Always pass a text representation of a non-stringified JSON body
>       // to `XMLHttpRequest.send` to retain a compatible behavior with the browser.
>       this._bodyInit = this._bodyText
>     }
> ```
> 
> There appears to be no issues when we run in version `3.5.0`.
> 
> Found in conjunction with @georgeloring / @katerynapalchykova

**Comment by hans2520** [comment]
Yes this is the same issue I wrote about here -- 
https://github.com/github/fetch/issues/922
