### ISSUE TITLE
Fetch doesnt work with cookies in react at all!

### ISSUE THREAD

**Issue by h110m** [github/fetch#926]
So I am referring to my own stackoverflow issue here --> https://stackoverflow.com/questions/66404690/fetch-api-doesnt-work-with-cookies-in-react-at-all

Since it is a fetch issue I thought posting it also on GitHub under the fetch repo would make sense.

So I don't really know if this is a problem that just occurs to me but I read a lot about it in some other issues but since the answers of these didn't help me I now have to make my own StackOverflow post ._.

I will try to keep it as short as possible.

So i am trying to make a simple fetch request to my backend but with including the current cookies from the browser. It just looks like this:
```js
var rsp = await fetch("/api/basicRegistrationInfos", {
  method: "POST",
  credentials: "same-origin",
  headers: new Headers({ Cookie: document.cookie }),
});
```
This isn't my original code.<br/>
The original code just contained `var rsp = await fetch("/api/basicRegistrationInfos");`.<br/>
I modified it because the cookie header wasn't working at all.<br/>
I tried setting every value of the `credentials` option but this didn't send any cookies.<br/>
Then I tried changing the `GET` to a `POST` request. Worked neither.<br/>
The last thing I tried was to set the cookie header myself. And this surprised me the most: it just deleted my cookie header before sending the request. And it actually just happens with the cookie header. I tried it with 'cookies' (`cookie` with an additional `s`) and it just set's the header.

A couple more things:<br/>
I can execute that it could be that I can't access the cookies because I tried it with `document.cookie` and got the right cookies back.<br/>
Also, my setup (frontend-backend) looks like this:

The browser makes a GET request to `/home` --> `/home` goes through the express backend, since it didn't include `/api/*` it requests a site and I can load my prod version of my react app via `express.sendFile()`<br/><br/>
I don't really think my backend has something to do with it but I thought it's better to also post this.

I hope someone can help me with this problem. I am struggling for 3 days on this cookie problem and it's driving me crazy. I also didn't seem to find someone with the same problem so I guess I am the first one to have it. <br/><br/>Anyways... <br/>Thanks in advance for any help or suggestions that anyone can give to me and have a nice day ^-^

**Comment by JakeChampion** [comment]
This repo is for a polyfill for fetch for older browsers.
Hopefully someone on stackoverflow can help you
