### ISSUE TITLE
Did I make any mistake in using Node Fetch Code?

### ISSUE THREAD

**Issue by zydjohnHotmail** [github/fetch#982]
Hello:
I am learning Fetch API now, and I found something strange. 
Usually, when I use Google Chrome, and visit some web pages, I can inspect the elements and view all the network requests via Chrome’s Developer Tools, and from Network tab, I can see all the network request, and I can copy the request as either curl or fetch; then use the copied command, from Console Tab, I can launch the command and get the exactly the same result.
However, from one specific web page, I can’t even reproduce the result.
The web page: https://sport.betregal.com/en/sports/
From the web page, I can click on and inspect any element, and I clicked on any EURO 2020 soccer game, like this one: England vs Scotland, then on this soccer game page, click on “Players” market, then checked the Network Tab from Developer Tools.
I found this HTTP Post request:
Request URL: https://sport.betregal.com/pagemethods_ros.aspx/UpdateEvents
I looked at the response, and found the response is basically a JSON format data.
Therefore, I have installed Node Fetch NPM package (Version 2.6.1), and wrote the following code:

const fetch = require('node-fetch');

function update_event1()
{
   fetch('https://sport.betregal.com/pagemethods_ros.aspx/UpdateEvents',
   {
         method: 'POST', headers: {
         'Accept': '*.*',
         'sec-fetch-mode': 'no-cors',
         'Access-Control-Allow-Origin': '*',
         'x-jwtoken': 'ey…...ig',
        'cookie': 'cApi=https://cdn.aspireglobal.com/secure/…...Fig',
         'Content-Type': 'application/x-www-form-urlencoded'},
         body: "requestString=56945445" })
     .then(res => console.log(res.text()))
}
update_event1();

However, when I run the above Node JS code, I got the response is totally different from the response I can view from Network tab, the Network tab I can see some JSON format data, but the response I get from Node Fetch code, is something like ordinary text.
Note: in the cookie, and x-jwtoken parts, I omit many letters to make my description cleaner.
Please advise, if I made any mistake in my Node Fetch code or is there any other issue will incur such different responses.
Thanks,

**Comment by Gara312** [comment]
> Здравствуйте: я сейчас изучаю Fetch API и обнаружил кое-что странное. Обычно, когда я использую Google Chrome и посещаю некоторые веб-страницы, я могу проверять элементы и просматривать все сетевые запросы с помощью инструментов разработчика Chrome, а на вкладке «Сеть» я вижу все сетевые запросы и могу скопировать запрос как либо curl, либо fetch; затем используйте скопированную команду из вкладки консоли, я могу запустить команду и получить точно такой же результат. Однако с одной конкретной веб-страницы я даже не могу воспроизвести результат. Веб-страница: https://sport.betregal.com/en/sports/ На веб-странице я могу щелкнуть и проверить любой элемент, и я щелкнул любой футбольный матч Евро-2020, например, этот: Англия против Шотландии, затем на этой странице футбольного матча щелкните рынок «Игроки», затем проверил Сеть. Вкладка из инструментов разработчика. Я нашел этот HTTP-запрос Post: URL-адрес запроса: https://sport.betregal.com/pagemethods_ros.aspx/UpdateEvents Я просмотрел ответ и обнаружил, что ответ в основном представляет собой данные в формате JSON. Поэтому я установил пакет Node Fetch NPM (версия 2.6.1) и написал следующий код:
> 
> const fetch = require ('узел-выборка');
> 
> function update_event1 () { fetch (' https://sport.betregal.com/pagemethods_ros.aspx/UpdateEvents ', { метод: 'POST', заголовки: { 'Accept': ' _._ ', 'sec-fetch-mode' : 'no-cors', 'Access-Control-Allow-Origin': '*', 'x-jwtoken': 'ey… ... ig', 'cookie': 'cApi = [https: //cdn.aspireglobal .com / secure /… ... Fig](https://cdn.aspireglobal.com/secure/%E2%80%A6...Fig) ', ' Content-Type ':' application / x-www-form-urlencoded '}, body: "requestString = 56945445"}) .then (res => console.log ( res.text ())) } update_event1 ();
> 
> Однако, когда я запускаю приведенный выше код Node JS, я получил ответ, который полностью отличается от ответа, который я могу просмотреть на вкладке «Сеть», на вкладке «Сеть» я вижу некоторые данные формата JSON, но ответ, который я получаю от кода извлечения узла, является что-то вроде обычного текста. Примечание: в частях cookie и x-jwtoken я опускаю много букв, чтобы сделать описание более понятным. Пожалуйста, сообщите, если я допустил ошибку в коде Node Fetch или возникнут какие-либо другие проблемы, ответы на них будут отличаться. Спасибо,

### ****
### **** # @ @
### ****
### ****

**Comment by Gara312** [comment]
### ****
### ****

**Comment by Gara312** [comment]
> Здравствуйте: я сейчас изучаю Fetch API и обнаружил кое-что странное. Обычно, когда я использую Google Chrome и посещаю некоторые веб-страницы, я могу проверить элементы и просмотреть все сетевые запросы с помощью инструментов разработчика Chrome, а на вкладке «Сеть» я могу увидеть все сетевые запросы и скопировать запрос как либо curl, либо fetch; затем используйте скопированную команду из вкладки консоли, я могу запустить команду и получить точно такой же результат. Однако с одной конкретной веб-страницы я даже не могу воспроизвести результат. Веб-страница: https://sport.betregal.com/en/sports/ На веб-странице я могу щелкнуть и проверить любой элемент, и я щелкнул любой футбольный матч Евро-2020, например, этот: Англия против Шотландии, затем на этой странице футбольного матча щелкните рынок «Игроки», затем проверил Сеть. Вкладка из инструментов разработчика. Я нашел этот HTTP-запрос Post: URL-адрес запроса: https://sport.betregal.com/pagemethods_ros.aspx/UpdateEvents Я просмотрел ответ и обнаружил, что ответ в основном представляет собой данные в формате JSON. Поэтому я установил пакет Node Fetch NPM (версия 2.6.1) и написал следующий код:
> 
> const fetch = require ('узел-выборка');
> 
> function update_event1 () { fetch (' https://sport.betregal.com/pagemethods_ros.aspx/UpdateEvents ', { метод: 'POST', заголовки: { 'Accept': ' _._ ', 'sec-fetch-mode' : 'no-cors', 'Access-Control-Allow-Origin': '*', 'x-jwtoken': 'ey… ... ig', 'cookie': 'cApi = [https: //cdn.aspireglobal .com / secure /… ... Fig](https://cdn.aspireglobal.com/secure/%E2%80%A6...Fig) ', ' Content-Type ':' application / x-www-form-urlencoded '}, body: "requestString = 56945445"}) .then (res => console.log ( res.text ())) } update_event1 ();
> 
> Однако, когда я запускаю приведенный выше код Node JS, я получил ответ, который полностью отличается от ответа, который я могу просмотреть на вкладке «Сеть», на вкладке «Сеть» я вижу некоторые данные формата JSON, но ответ, который я получаю от кода извлечения узла, является что-то вроде обычного текста. Примечание: в частях cookie и x-jwtoken я опускаю много букв, чтобы сделать описание более понятным. Пожалуйста, сообщите, если я допустил ошибку в коде Node Fetch или возникнут какие-либо другие проблемы, ответы на них будут отличаться. Спасибо,

### ****
