### ISSUE TITLE
public class child data removal requests 

### ISSUE THREAD

**Issue by saan5** [github/fetch#991]
public class MainActivity extends AppCompatActivity {

    TextView tvResult;
    ProgressDialog progressDialog;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        progressDialog = new ProgressDialog(this);
        progressDialog.setMessage("Loading...");
        progressDialog.setCancelable(false);
        progressDialog.setCanceledOnTouchOutside(false);
        progressDialog.create();
        progressDialog.show();

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                progressDialog.dismiss();
                tvResult.setVisibility(View.VISIBLE);
            }
        },2000);
    }
}

_Originally posted by @saan5 in https://github.com/github/docs/issues/8119#issuecomment-878632540_

**Comment by saan5** [comment]
TextView tvResult;
ProgressDialog progressDialog;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    progressDialog = new ProgressDialog(this);
    progressDialog.setMessage("Loading...");
    progressDialog.setCancelable(false);
    progressDialog.setCanceledOnTouchOutside(false);
    progressDialog.create();
    progressDialog.show();

    new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
            progressDialog.dismiss();
            tvResult.setVisibility(View.VISIBLE);
        }
    },2000);
}

**Comment by KVROHITH098** [comment]
Ok so we should change the script down below!!!
