### ISSUE TITLE
Thanks for opening this issue! I agree that we should mention time limits here. The text in [Workflow syntax for GitHub Actions - GitHub Docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) could be changed to something like:

### ISSUE THREAD

**Issue by mjsweet01** [github/fetch#993]
Thanks for opening this issue! I agree that we should mention time limits here. The text in [Workflow syntax for GitHub Actions - GitHub Docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) could be changed to something like:

```
The maximum number of minutes to let a job run before GitHub automatically cancels it. Default: 360

If the timeout exceeds the job execution time limit for the runner, the job will be canceled when the execution time limit is met instead. For more information about job execution time limits, see "[Usage limits, billing, and administration](/actions/reference/usage-limits-billing-and-administration#usage-limits)."
```

You or anyone else is welcome to open a PR with this addition.

Although you are correct that changing 6 hours to 360 minutes in [Usage limits, billing, and administration](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits) would be more consistent across articles, I recommend keeping it as 6 hours so that unit comparison within the article is easier (e.g. job limit is 6 hours, and workflow limit is 72 hours).

_Originally posted by @skedwards88 in https://github.com/github/docs/issues/7984#issuecomment-879298243_

**Comment by irene459** [comment]
I want to unsubscribe . Am the owner of this phone and I have mentioned that I've been hacked and who ever is doing this is really destroying my life .I know nothing about all this software stuff I've never studied on computers . But this person is being deceitful and using my information for there selfish desires I had to Change my whole bank account and I can't even down load the mobile app or do it on line to look at my bank account . This person is using my Apple ID to purchase things and knows everything I do to my location . Basically they device they are using is the platform of my iPhone 11 that are use a Mac computer or using windows just different browsers to use my phone how ever they do it. Can you please fix everything that is not legal and then unsubscribe me . Erase everything so no one or my self can get back on thanks
